### PR TITLE
psa_asymmetric_encrypt() doesn't work with opaque driver

### LINKED ISSUE #8461: psa_asymmetric_encrypt() doesn't work with opaque driver
### Summary

I am creating an opaque driver which talks to a secure element (in our case it's TF-M). The driver supports entries `asymmetric_encrypt` and `asymmetric_decrypt`.

In the application, we generated a key at first with the driver successfully, then we tried to call `psa_asymmetric_encrypt()` with the key. But the check failed here https://github.com/Mbed-TLS/mbedtls/blob/91aaba0172dfa1c740bc67a12bc201bad4cd509c/library/psa_crypto.c#L1146C4-L1146C4 in `psa_get_and_lock_transparent_key_slot_with_policy()`. 

Seemingly the `psa_asymmetric_encrypt()` assumes that key must be a transparent one and can not be external. The limitation doesn't work with an opaque driver.

### System information

Mbed TLS version: v3.4.0
Operating system and version: Linux Ubuntu 22.04
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

In `psa_asymmetric_encrypt()`, the checks before invoking `psa_driver_wrapper_asymmetric_encrypt()` should pass.

### Additional information

Same problem is also seen in `psa_asymmetric_decrypt()`

### PR DESCRIPTION
**Pull request by valeriosetti**
## Description

This PR enabled asymmetric encryption/decryption with opaque keys.

Resolves #8461

## PR checklist

- [x] **changelog** provided
- [x] **backport** not required
- [x] **tests** provided

### CODE REVIEW

**Comment by valeriosetti** [comment]
### Note to reviewers

In addition to allowing usage of opaque keys with `psa_asymmetric_[en|de]crypt`, this PR also fixes limitations in `test_driver_asymmetric_[en|de]cryption`. So far only a single test is performed in `test_suite_psa_crypto.data` with opaque key. However if the overall pattern looks reasonably good, I can add more test for it (different key sizes, failing cases, etc)

**Review by minosgalanakis — APPROVED** [review]
LGTM.

I do not feel a changelog is needed in this case. This pr is fixing the opaque driver support.

Since @gilles-peskine-arm is happy with adding the single test at this stage, we are good to go.

**Comment by gilles-peskine-arm** [comment]
> I do not feel a changelog is needed in this case. This pr is fixing the opaque driver support.

That's a library bug (or missing feature), which has been reported by a user, so we do need a changelog entry.

**Review by minosgalanakis — APPROVED** [review]
LGTM

File: tests/src/drivers/test_driver_key_management.c [hunk 1]
```diff
@@ -125,7 +125,7 @@ static size_t mbedtls_test_opaque_get_base_size()
  * The argument wrapped_key_buffer_length is filled with the wrapped
  * key_size on success.
  * */
-static psa_status_t mbedtls_test_opaque_wrap_key(
+psa_status_t mbedtls_test_opaque_wrap_key(
```
Comment (tom-daubney-arm) [inline tests/src/drivers/test_driver_key_management.c:128]: I am not totally sure why the wrap function is no longer static. It is not used in the tests I don't think. Is this just to keep it consistent with the unwrap function?

**Review by tom-daubney-arm — CHANGES_REQUESTED** [review]
Small typo in the changelog and a question in the comments.

File: tests/src/drivers/test_driver_key_management.c (hunk 1 above)
Comment (valeriosetti) [reply tests/src/drivers/test_driver_key_management.c:128]: Oh, you are totally right. I probably moved both functions from `static` to public, but actually only the unwrap function is needed for opaque drivers. I'm reverting the change for the wrapping key.

**Review by tom-daubney-arm — APPROVED** [review]
Thanks for the changes. LGTM now.
