### PR TITLE
TLS 1.3: Fix anti replay fail from GnuTLS

### LINKED ISSUE #6623: Early data test case will fail randomly cause the anti-play protection from gnutls server
### Summary
We have one test case in tests/opt-testcases/tls13-misc.sh, it will fail randomly when the anti-replay protection is triggered by gnutls server. 
It's one test case during development, and only test the early data indication writing in client hello, we should dig more about the gnutls server to find what cause the protection be triggered.

### System information

Mbed TLS version (number or commit id):  development
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

Test case passed

### Actual behavior

Random failed.

### Steps to reproduce

It's one random issue. 
Please run the test case "TLS 1.3 m->G: EarlyData: basic check, good" in he file tests/opt-testcases/tls13-misc.sh.

### PR DESCRIPTION
**Pull request by yuhaoth**
## Description

fix #6623 

preceding-pr: #6891 

### ROOT CAUSE

TIME RESOLUTION OF TICKET AGE

The time precision of ticket_age is milliseconds(RFC 8446). But our precision is senconds, we caculate
ticket age with (mbedtls_time( NULL ) - ticket_recived)*1000 .
If the ticket is sent/received near the end of a second and client send ticket at the beggining of
next second, ticket age of client is 1000 ms, but ticket age of server is less than it. As a result,
it offends the anit replay ruler.

Workaround solution: Add 1 second to ticket_received and do reconnect 1 second later.

The issue can be reproduce and verified with https://github.com/Mbed-TLS/mbedtls/pull/6712 . That PR include test script and test result.
This PR is to fix that.

- [x] Add platform time function with milliseconds.
- [x] Change the time resolution from seconds to milliseconds for `ticket->start` and `ticket->ticket_received`

The commit is come from #6712 and verified in that PR

## Gatekeeper checklist

I am not sure if it needs backport.

- [ ] **changelog** provided, or not required
- [ ] **backport** done, or not required
- [ ] **tests** provided, or not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]

File: ChangeLog.d/gnutls_anti_replay_fail.txt [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Bugfix
+    * Fixes #6623. That is time unit issue. The unit of ticket age is seconds in
+      MBedTLS and milliseconds in GnuTLS. If the real age is 10ms, it might be
+      1s(1000ms), as a result, the age of MBedTLS is bigger than GnuTLS server.
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply ChangeLog.d/gnutls_anti_replay_fail.txt:4]: I have reopen #6787 . And I think we should postpone this PR.

> we have to think about the new platform function carefully and probably do that separately. 

Do you mean move `mbedtls_ms_time` to another PR?

[the remark this answers is not in the document]
Comment (yuhaoth) [reply ChangeLog.d/gnutls_anti_replay_fail.txt:4]: This PR has been re-organized. 

Now it preceding #6891 and the `mbedtls_ms_time` relative commits have been moved to the PR.

[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply ChangeLog.d/gnutls_anti_replay_fail.txt:4]: That's all good. Thanks for creating a dedicating PR for `mbedtls_ms_time` and as I think you mentioned let's postpone the review of #6891 and of this PR.

**Comment by yuhaoth** [comment]
ABI-API-checking is a dedicate fail

**Comment by yuhaoth** [comment]
Rebase to re-trigger CI

**Comment by yuhaoth** [comment]
Rebase to re-trigger CI

**Comment by yuhaoth** [comment]
Rebase to retrigger CI. 
#7795  is weak relative to this PR. So Rebase it to ask new review.

**Comment by yuhaoth** [comment]
Rebase to re-trigger CI

**Comment by yuhaoth** [comment]
Rebased

File: library/ssl_tls13_server.c [hunk 2]
```diff
@@ -208,10 +208,10 @@ static int ssl_tls13_offered_psks_check_identity_match_ticket(
      *
      * For time being, the age MUST be less than 604800 seconds (7 days).
      */
-    if (age_in_s > 604800) {
+    if (server_age > 604800*1000) {
```
Comment (xkqian) [inline library/ssl_tls13_server.c:211]:
```suggestion
    if (server_age > 604800 * 1000) {
```

File: programs/ssl/ssl_server2.c [hunk 3]
```diff
@@ -1430,16 +1430,16 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
...
-            session->start = mbedtls_time(NULL) - 10 - 7 * 24 * 3600;
+            session->start = mbedtls_ms_time() - 10 * 1000 - 7 * 24 * 3600 * 1000;
             break;
         case 5:
-            session->start = mbedtls_time(NULL) - 10;
+            session->start = mbedtls_ms_time() - 10 * 1000;
             break;
         case 6:
-            session->start = mbedtls_time(NULL);
+            session->start = mbedtls_ms_time();
```
Comment (xkqian) [inline programs/ssl/ssl_server2.c:1442]: Though it's not the change of this PR, does it worth one description where is the **"%11"** from and what's the meaning of `1, 2, 3... `

File: library/ssl_tls13_server.c [hunk 4]
```diff
@@ -222,18 +222,19 @@ static int ssl_tls13_offered_psks_check_identity_match_ticket(
...
-    if (age_diff_in_ms <= -1000 ||
-        age_diff_in_ms > MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE) {
+    client_age = obfuscated_ticket_age - session->ticket_age_add;
+    age_diff = server_age - client_age;
+    if (age_diff < -1000 ||
+        age_diff > MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE) {
         MBEDTLS_SSL_DEBUG_MSG(
-            3, ("Ticket age outside tolerance window ( diff=%d )",
-                (int) age_diff_in_ms));
+            3, ("Ticket age outside tolerance window ( diff=%" MBEDTLS_PRINTF_MS_TIME ")",
```
Comment (xkqian) [inline library/ssl_tls13_server.c:236]:
```suggestion
            3, ("Ticket age outside tolerance window ( diff = %" MBEDTLS_PRINTF_MS_TIME ")",
```

File: library/ssl_tls13_server.c [hunk 5]
```diff
@@ -185,17 +186,16 @@ static int ssl_tls13_offered_psks_check_identity_match_ticket(
...
-    now = mbedtls_time(NULL);
+    now = mbedtls_ms_time();
 
     if (now < session->start) {
         MBEDTLS_SSL_DEBUG_MSG(
-            3, ("Invalid ticket start time ( now=%" MBEDTLS_PRINTF_LONGLONG
-                ", start=%" MBEDTLS_PRINTF_LONGLONG " )",
-                (long long) now, (long long) session->start));
+            3, ("Invalid ticket start time ( now=%" MBEDTLS_PRINTF_MS_TIME
+                ", start=%" MBEDTLS_PRINTF_MS_TIME " )", now, session->start));
```
Comment (xkqian) [inline library/ssl_tls13_server.c:194]:
```suggestion
            3, ("Invalid ticket start time ( now = %" MBEDTLS_PRINTF_MS_TIME
                ", start = %" MBEDTLS_PRINTF_MS_TIME " )", now, session->start));
```

File: library/ssl_tls13_server.c [hunk 6]
```diff
@@ -222,18 +222,19 @@ static int ssl_tls13_offered_psks_check_identity_match_ticket(
...
+     *       be invalid.
      */
-    age_diff_in_ms = age_in_s * 1000;
-    age_diff_in_ms -= (obfuscated_ticket_age - session->ticket_age_add);
-    if (age_diff_in_ms <= -1000 ||
-        age_diff_in_ms > MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE) {
+    client_age = obfuscated_ticket_age - session->ticket_age_add;
+    age_diff = server_age - client_age;
+    if (age_diff < -1000 ||
+        age_diff > MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE) {
```
Comment (xkqian) [inline library/ssl_tls13_server.c:234]: Since we get one more precise timer in the unit of `ms`,  should we change the tolerance window smaller?

**Review by xkqian — COMMENTED** [review]
This looks quite good to me except some minor improvements.

File: library/ssl_tls13_server.c (hunk 6 above)
Comment (yuhaoth) [reply library/ssl_tls13_server.c:234]: That's a configuration value, user can change it base on their situation. The default value is the maximum time shift. I do not think we should change it.

**Review by xkqian — DISMISSED** [review]
LGTM

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
One thing I'd like to clarify before to go further in the review.

File: include/mbedtls/ssl.h [hunk 7]
```diff
@@ -1209,7 +1209,7 @@ struct mbedtls_ssl_session {
     mbedtls_ssl_protocol_version MBEDTLS_PRIVATE(tls_version);
 
 #if defined(MBEDTLS_HAVE_TIME)
-    mbedtls_time_t MBEDTLS_PRIVATE(start);       /*!< starting time      */
+    mbedtls_ms_time_t MBEDTLS_PRIVATE(start);    /*!< starting time      */
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply include/mbedtls/ssl.h:1212]: > in `ssl_write_server_hello()` 

It is part of `Random random` , it is defined as `gmt_unix_time` in RFC5246 7.4.1.2. So it should not be changed. 

But in `ssl_write_client_hello_body()` it does not follow the RFC definition. And in RFC8446 the field is different. So I think we should raise another PR to discuss and fix the issue.

```
/* RFC5246 7.4.1.2 */
         struct {
             uint32 gmt_unix_time;
             opaque random_bytes[28];
         } Random;

/* RFC 8446 B.3.1 */
      opaque Random[32];

```

[the remark this answers is not in the document]
Comment (yuhaoth) [reply include/mbedtls/ssl.h:1212]: > Probably that we should have a specific field for the time of creation of a ticket (ticket_creation_time?). Currently in TLS 1.3 for ticket purposes we anyway use this field not as the session starting time (abuse of semantic) when we update it with the current time before to send a ticket (in ssl_tls13_prepare_new_session_ticket()).

Agree. I will create it in this PR. 

Beside that, I think we can remove `session->start` in future. That is not scope of this PR.

[the remark this answers is not in the document]
Comment (yuhaoth) [reply include/mbedtls/ssl.h]: For the time issue in `ssl_write_server_hello()`, it does not need change.  But it is not easily understand, I just raise #8458 to improve the readability. 

That PR also includes a change on `supported_versions` , please check the PR if you have bandwidth.

File: programs/ssl/ssl_server2.c [hunk 8]
```diff
@@ -1426,35 +1426,44 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
...
             session->ticket_age_add -= 1000;
-#endif
             break;
-#if defined(MBEDTLS_SSL_PROTO_TLS1_3)
         case 7:
+            /* Built-in check, ticket permission check. */
             session->ticket_flags = MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_NONE;
             break;
         case 8:
+            /* Built-in check, ticket permission check. */
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_server2.c:1458]:
```suggestion
```

File: programs/ssl/ssl_server2.c [hunk 9]
```diff
@@ -1426,35 +1426,44 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
 
     switch (opt.dummy_ticket % 11) {
         case 1:
+            /* Callback function return INVALID_MAC */
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_server2.c:1429]:
```suggestion
```
This comment does not bring much.

File: programs/ssl/ssl_server2.c [hunk 10]
```diff
@@ -1426,35 +1426,44 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
...
             return MBEDTLS_ERR_SSL_INVALID_MAC;
         case 2:
+            /* Callback function return ticket expired */
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_server2.c:1432]:
```suggestion
```

File: programs/ssl/ssl_server2.c [hunk 11]
```diff
@@ -1426,35 +1426,44 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
...
         case 7:
+            /* Built-in check, ticket permission check. */
             session->ticket_flags = MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_NONE;
             break;
         case 8:
+            /* Built-in check, ticket permission check. */
             session->ticket_flags = MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK;
             break;
         case 9:
+            /* Built-in check, ticket permission check. */
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_server2.c:1462]:
```suggestion
```

File: programs/ssl/ssl_server2.c [hunk 12]
```diff
@@ -1426,35 +1426,44 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
...
             session->ticket_flags = MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL;
             break;
         case 10:
+            /* Built-in check, ticket permission check. */
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_server2.c:1466]:
```suggestion
```

File: programs/ssl/ssl_server2.c [hunk 13]
```diff
@@ -1426,35 +1426,44 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
...
         case 1:
+            /* Callback function return INVALID_MAC */
             return MBEDTLS_ERR_SSL_INVALID_MAC;
         case 2:
+            /* Callback function return ticket expired */
             return MBEDTLS_ERR_SSL_SESSION_TICKET_EXPIRED;
+#if defined(MBEDTLS_SSL_PROTO_TLS1_3)
         case 3:
-            session->start = mbedtls_time(NULL) + 10;
+            /* Built-in check, the start time is in future. */
```
[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply programs/ssl/ssl_server2.c:1436]: Otherwise as comment, what about to rather describe the check in the library that the case is targeting for failure? Ditto for case 4, 5, 6.

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
A few things I would like to improve.

File: include/mbedtls/ssl.h [hunk 14]
```diff
@@ -1240,6 +1240,9 @@ struct mbedtls_ssl_session {
     uint8_t MBEDTLS_PRIVATE(ticket_flags);      /*!< Ticket flags */
     uint32_t MBEDTLS_PRIVATE(ticket_age_add);               /*!< Randomly generated value used to obscure the age of the ticket */
     uint8_t MBEDTLS_PRIVATE(resumption_key_len);            /*!< resumption_key length */
+#if defined(MBEDTLS_HAVE_TIME)
+    mbedtls_ms_time_t MBEDTLS_PRIVATE(ticket_creation);     /*!< create time of ticket */
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply include/mbedtls/ssl.h:1244]: That change the structure of serialization. I must think about that.

File: library/ssl_tls13_server.c [hunk 15]
```diff
@@ -208,10 +209,10 @@ static int ssl_tls13_offered_psks_check_identity_match_ticket(
      *
      * For time being, the age MUST be less than 604800 seconds (7 days).
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply library/ssl_tls13_server.c:210]: This line is duplicated with above. I just remove it.

File: programs/ssl/ssl_server2.c (hunk 13 above)
[the remark this answers is not in the document]
Comment (yuhaoth) [reply programs/ssl/ssl_server2.c:1436]: I also changed the context of tests.

File: library/ssl_tls13_server.c [hunk 16]
```diff
@@ -222,18 +223,20 @@ static int ssl_tls13_offered_psks_check_identity_match_ticket(
...
+     *       MUST sync up system time every 16 hours. Otherwise, the ticket will
+     *       be invalid.
      */
-    age_diff_in_ms = age_in_s * 1000;
-    age_diff_in_ms -= (obfuscated_ticket_age - session->ticket_age_add);
-    if (age_diff_in_ms <= -1000 ||
-        age_diff_in_ms > MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE) {
+    client_age = obfuscated_ticket_age - session->ticket_age_add;
+    age_diff = server_age - client_age;
+    if (age_diff < -1000 ||
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply library/ssl_tls13_server.c:234]: I just update the bottom bound and document of `MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE` . 

`MBEDTLS_SSL_TLS_ESTIMATED_RTT` is outside of this PR and I does not understand it now.

File: library/ssl_tls13_client.c [hunk 17]
```diff
@@ -945,28 +945,10 @@ int mbedtls_ssl_tls13_write_identities_of_pre_shared_key_ext(
     if (ssl_tls13_ticket_get_identity(
             ssl, &hash_alg, &identity, &identity_len) == 0) {
 #if defined(MBEDTLS_HAVE_TIME)
-        mbedtls_time_t now = mbedtls_time(NULL);
+        mbedtls_ms_time_t now = mbedtls_ms_time();
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply library/ssl_tls13_client.c:948]: >But when receiving a new session ticket we do not check that the ticket age is lower than 7 days.

Done

File: library/ssl_tls.c [hunk 18]
```diff
@@ -2468,7 +2468,7 @@ mbedtls_ssl_mode_t mbedtls_ssl_get_mode_from_ciphersuite(
  *       opaque resumption_key<0..255>;
  *       select ( endpoint ) {
  *            case client: ClientOnlyData;
- *            case server: uint64 start_time;
+ *            case server: uint64 ticket_creation_time_time;
```
Comment (xkqian) [inline library/ssl_tls.c:2471]: Is it one type error of `ticket_creation_time`?

File: library/ssl_tls13_client.c [hunk 19]
```diff
@@ -945,28 +945,14 @@ int mbedtls_ssl_tls13_write_identities_of_pre_shared_key_ext(
...
         mbedtls_ssl_session *session = ssl->session_negotiate;
+        /* The ticket age has been checked to be smaller that the
```
Comment (xkqian) [inline library/ssl_tls13_client.c:950]:
```suggestion
        /* The ticket age has been checked to be smaller than the
```

**Review by xkqian — COMMENTED** [review]
Minor nitpick improvements.

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]

File: programs/ssl/ssl_server2.c [hunk 20]
```diff
@@ -1429,22 +1429,32 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
             return MBEDTLS_ERR_SSL_INVALID_MAC;
         case 2:
             return MBEDTLS_ERR_SSL_SESSION_TICKET_EXPIRED;
+#if defined(MBEDTLS_SSL_PROTO_TLS1_3)
         case 3:
-            session->start = mbedtls_time(NULL) + 10;
+            /* Creation time in the future. */
+            session->ticket_creation_time = mbedtls_ms_time() +
+                                            MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE +
+                                            4 * 1000;
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply programs/ssl/ssl_server2.c:1437]: Yes.

File: programs/ssl/ssl_server2.c [hunk 21]
```diff
@@ -1429,22 +1429,32 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
...
             break;
         case 4:
-            session->start = mbedtls_time(NULL) - 10 - 7 * 24 * 3600;
+            /* Ticket reaches the end of lifetime. */
+            session->ticket_creation_time = mbedtls_ms_time() - session->ticket_lifetime -
+                                            MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE - 4 * 1000;
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply programs/ssl/ssl_server2.c]: I just create #8525 .  TLS 1.3 server should save the field also. Otherwise, client can resume session with an expired ticket.

File: include/mbedtls/mbedtls_config.h [hunk 22]
```diff
@@ -4082,19 +4082,21 @@
...
+ *   received the ticket from the server.
+ * - The server ticket age is the time difference between the time when the
+ *   server receives a proposition from the client to use the ticket and the
+ *   time when the ticket was created by the server.
+ *
+ * The ages might be different due to accuracy of RTC crypstal. The typical
+ * accuracy of an RTC crystal is ±100 to ±20 parts per million (360 to 72
+ * milliseconds per hour). Default tolerance windows is 6s, thus in the worst
+ * case client and servers must sync up their system time every 6000/360/2~=8
+ * hours.
```
[the remark this answers is not in the document]
Comment (yuhaoth) [reply include/mbedtls/mbedtls_config.h]: Should we add another option to cover it ?

File: library/ssl_misc.h [hunk 23]
```diff
@@ -2773,8 +2773,6 @@ int mbedtls_ssl_session_set_hostname(mbedtls_ssl_session *session,
 
 #if defined(MBEDTLS_SSL_PROTO_TLS1_3) && defined(MBEDTLS_SSL_SESSION_TICKETS)
 
-#define MBEDTLS_SSL_TLS1_3_MAX_ALLOWED_TICKET_LIFETIME (604800)
```
Comment (ronald-cron-arm) [inline library/ssl_misc.h]: Why have you removed it? It was a good improvement.

File: include/mbedtls/mbedtls_config.h (hunk 22 above)
[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply include/mbedtls/mbedtls_config.h]: In this PR, just add at the end: "See section 8.3 of the TLS 1.3 specification for more information."
Then in a follow up PR we can take into account the round trip time in the age difference calculation.

File: library/ssl_tls13_server.c [hunk 24]
```diff
@@ -223,15 +222,14 @@ static int ssl_tls13_offered_psks_check_identity_match_ticket(
...
      * within a small tolerance of the time since the ticket was issued.
      *
-     * NOTE: Typical crystal RTC accuracy specifications are from ±100 to ±20
-     *       parts per million (360 to 72 million seconds per hour). Defualt
-     *       tolerance windows is 6000 millionsections, that means client host
-     *       MUST sync up system time every 16 hours. Otherwise, the ticket will
-     *       be invalid.
+     * NOTE: The typical accuracy of an RTC crystal is ±100 to ±20 parts per
+     *       million (360 to 72 milliseconds per hour). Default tolerance
+     *       windows is 6s, thus in the worst case client and servers must
```
[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply library/ssl_tls13_server.c:227]: no uploaded it seems

File: library/ssl_misc.h (hunk 23 above)
Comment (yuhaoth) [reply library/ssl_misc.h]: misunderstand your feedback

File: include/mbedtls/mbedtls_config.h [hunk 25]
```diff
@@ -4082,20 +4082,23 @@
...
+ * server and client. Default value is 6000. This is not used in TLS 1.2.
+ *
+ * - The client ticket age is the time difference between the time when the
+ *   client proposes to the server to use the ticket and the time the client
+ *   received the ticket from the server.
+ * - The server ticket age is the time difference between the time when the
+ *   server receives a proposition from the client to use the ticket and the
+ *   time when the ticket was created by the server.
+ *
+ * The ages might be different due to the client and server clocks not running
```
Comment (xkqian) [inline include/mbedtls/mbedtls_config.h:4095]:
```suggestion
 * The ages might be different due to the client and server clocks don't run
```

File: library/ssl_tls13_server.c [hunk 26]
```diff
@@ -206,12 +207,11 @@ static int ssl_tls13_offered_psks_check_identity_match_ticket(
...
      * the "ticket_lifetime" value which was provided with the ticket.
      *
-     * For time being, the age MUST be less than 604800 seconds (7 days).
      */
-    if (age_in_s > 604800) {
+    if (server_age > MBEDTLS_SSL_TLS1_3_MAX_ALLOWED_TICKET_LIFETIME * 1000) {
         MBEDTLS_SSL_DEBUG_MSG(
-            3, ("Ticket age exceeds limitation ticket_age=%lu",
-                (long unsigned int) age_in_s));
+            3, ("Ticket age exceeds limitation ticket_age=%" MBEDTLS_PRINTF_MS_TIME,
```
Comment (xkqian) [inline library/ssl_tls13_server.c:213]:
```suggestion
            3, ("Ticket age exceeds limitation ticket_age = %" MBEDTLS_PRINTF_MS_TIME,
```

File: programs/ssl/ssl_server2.c [hunk 27]
```diff
@@ -1429,22 +1429,29 @@ int dummy_ticket_parse(void *p_ticket, mbedtls_ssl_session *session,
...
         case 3:
-            session->start = mbedtls_time(NULL) + 10;
+            /* Creation time in the future. */
+            session->ticket_creation_time = mbedtls_ms_time() + 1000;
             break;
         case 4:
-            session->start = mbedtls_time(NULL) - 10 - 7 * 24 * 3600;
+            /* Ticket has reached the end of lifetime. */
+            session->ticket_creation_time = mbedtls_ms_time() -
+                                            (7 * 24 * 3600 * 1000 + 1000);
```
Comment (xkqian) [inline programs/ssl/ssl_server2.c:1440]:
```suggestion
                                            (MBEDTLS_SSL_TLS1_3_MAX_ALLOWED_TICKET_LIFETIME * 1000 + 1000);
```

File: tests/suites/test_suite_ssl.function [hunk 28]
```diff
@@ -2155,16 +2178,22 @@ void ssl_serialize_session_save_buf_size(int ticket_len, char *crt_file,
...
+    }
 #endif
-    {
+
+#if defined(MBEDTLS_SSL_PROTO_TLS1_2)
+    if (tls_version == MBEDTLS_SSL_VERSION_TLS1_2) {
         TEST_ASSERT(mbedtls_test_ssl_tls12_populate_session(
                         &session, ticket_len, crt_file) == 0);
     }
+#endif
```
Comment (xkqian) [inline tests/suites/test_suite_ssl.function:2195]: If we merge these two blocks into one like this, will it be better (And we can add more such as tls1_4, etc. into one code block)?


if (tls_version == MBEDTLS_SSL_VERSION_TLS1_3) {
    #if defined(MBEDTLS_SSL_PROTO_TLS1_3)
        TEST_ASSERT(mbedtls_test_ssl_tls13_populate_session(&session, 0, endpoint_type) == 0);
    #endif
}
else if (tls_version == MBEDTLS_SSL_VERSION_TLS1_2) {
    #if defined(MBEDTLS_SSL_PROTO_TLS1_2)
        TEST_ASSERT(mbedtls_test_ssl_tls12_populate_session(&session, ticket_len, crt_file) == 0);
    #endif
}

File: tests/suites/test_suite_ssl.function [hunk 29]
```diff
@@ -2266,11 +2301,15 @@ void ssl_session_serialize_version_check(int corrupt_major,
...
 #endif
-    TEST_ASSERT(mbedtls_test_ssl_tls12_populate_session(
-                    &session, 0, NULL) == 0);
 
+#if defined(MBEDTLS_SSL_PROTO_TLS1_2)
+    if (tls_version == MBEDTLS_SSL_VERSION_TLS1_2) {
+        TEST_ASSERT(mbedtls_test_ssl_tls12_populate_session(
+                        &session, 0, NULL) == 0);
+    }
+#endif
```
Comment (xkqian) [inline tests/suites/test_suite_ssl.function:2312]: ditto

File: programs/ssl/ssl_server2.c (hunk 27 above)
Comment (yuhaoth) [reply programs/ssl/ssl_server2.c:1440]: The macro is internal only.

File: include/mbedtls/mbedtls_config.h (hunk 25 above)
Comment (yuhaoth) [reply include/mbedtls/mbedtls_config.h:4095]: `due to` needs present participle of verb.

File: tests/suites/test_suite_ssl.function (hunk 28 above)
Comment (yuhaoth) [reply tests/suites/test_suite_ssl.function]: Change to `switch .. case `

**Review by xkqian — COMMENTED** [review]
This looks good to me except two minor improvements.

File: ChangeLog.d/gnutls_anti_replay_fail.txt (hunk 1 above)
Comment (ronald-cron-arm) [inline ChangeLog.d/gnutls_anti_replay_fail.txt:4]: What about rather something like:
```suggestion
    * Switch to milliseconds as the unit for ticket creation and reception time
       instead of seconds. That avoids rounding errors when computing the
       age of tickets compared to peer using a millisecond clock (observed
       with GnuTLS). Fixes #6623.
```

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
Final comments on my side. Next time I will only check things relative to these comments.

**Review by ronald-cron-arm — DISMISSED** [review]
LGTM, thanks.

File: tests/suites/test_suite_ssl.function [hunk 30]
```diff
@@ -2092,16 +2116,22 @@ void ssl_serialize_session_load_save(int ticket_len, char *crt_file,
...
 #endif
-    {
+
+#if defined(MBEDTLS_SSL_PROTO_TLS1_2)
+    if (tls_version == MBEDTLS_SSL_VERSION_TLS1_2) {
+
         TEST_ASSERT(mbedtls_test_ssl_tls12_populate_session(
                         &session, ticket_len, crt_file) == 0);
     }
+#endif
```
Comment (xkqian) [inline tests/suites/test_suite_ssl.function:2134]: Sorry, still find one left which doesn't align with the comment https://github.com/Mbed-TLS/mbedtls/pull/6788#discussion_r1395088092.

**Review by xkqian — APPROVED** [review]
LGTM

Thanks for addressing the comments.

**Comment by ronald-cron-arm** [comment]
There is a conflict with `development`. Please resolve it.

**Comment by yuhaoth** [comment]
Rebased to resolve conflicts

**Review by xkqian — APPROVED** [review]
LGTM

**Comment by yuhaoth** [comment]
internal CI reports pip install fail and open CI pass

**Review by ronald-cron-arm — APPROVED** [review]
I've checked the rebase, LGTM.
