### PR TITLE
Fix preprocessor guards for C99 format size specifiers

### LINKED ISSUE #10017: Wrong MSVC version guard for C99 format size specifiers
### Summary
In include/mbedtls/debug.h we have the following `#ifdef guard` for using C99 format size specifiers:

```c
#if (defined(__MINGW32__) && __USE_MINGW_ANSI_STDIO == 0) || (defined(_MSC_VER) && _MSC_VER < 1800)
   #include <inttypes.h>
   #define MBEDTLS_PRINTF_SIZET     PRIuPTR
   #define MBEDTLS_PRINTF_LONGLONG  "I64d"
#else \
    /* (defined(__MINGW32__)  && __USE_MINGW_ANSI_STDIO == 0) || (defined(_MSC_VER) && _MSC_VER < 1800) */
   #define MBEDTLS_PRINTF_SIZET     "zu"
   #define MBEDTLS_PRINTF_LONGLONG  "lld"
#endif \
    /* (defined(__MINGW32__)  && __USE_MINGW_ANSI_STDIO == 0) || (defined(_MSC_VER) && _MSC_VER < 1800) */
```

However, `_MSC_VER = 1800` corresponds to Visual Studio 2013, which doesn't support several C99 size specifiers, including `zu`, causing runtime failures.

### PR DESCRIPTION
**Pull request by bensze01**
## Description

This PR fixes the preprocessor guards protecting the use of `%zu` in `MBEDTLS_PRINTF_SIZET`
It also adds a non-regression test to `test_suite_debug`.

Fixes #10017
Unblocks #9976

## PR checklist

- [ ] **changelog** provided
- [ ] **TF-PSA-Crypto PR** Mbed-TLS/TF-PSA-Crypto#192
- [ ] **framework PR** not required
- [ ] **3.6 PR** #10043
- [ ] **2.28 PR** #10044 
- [ ]  **tests**  provided

### CODE REVIEW

**Comment by mpg** [comment]
I tried cherry-picking 81ea6a6b9065a602a5b66d7b4c9f82a7c8c5260a in the branch (based on 3.6) where I originally uncovered the issue. It fixed the windows -cmake tests but broke the the windows -shipped tests with lots of compile errors like: `error C2146: syntax error : missing ')' before identifier 'PRIuPTR'` ([full log](https://mbedtls.trustedfirmware.org/blue/organizations/jenkins/mbed-tls-pr-head/detail/PR-9976-head/13/pipeline/8047)).

I can see that the windows -shipped tests are passing here, so perhaps I didn't cherry-pick correctly, or the problem I'm observing is specific to 3.6?

(Unrelated: this is labeled "needs preceding PR" but I can't see a link to the preceding PR it needs in the description.)

**Comment by bensze01** [comment]
@mpg Both your issues and the 'Needs preceding pr' are because one of the commits (https://github.com/Mbed-TLS/mbedtls/pull/10020/commits/5fbffa25bc1e0ea7e8117d97c06cb36f3bbc35e6) updates the tf-psa-crypto submodule, which I haven't filed a PR for yet. You need to cherry-pick

**Comment by mpg** [comment]
Ok, thanks.

**Comment by mpg** [comment]
@bensze01 How is this progressing? This is needed for the TLS defragmentation work which is the top priority for 3.6.3 and the code freeze is next Friday (14 Mar) - hard deadline.

If this can't be ready in time we can look for workarounds but we need to know.

**Comment by bensze01** [comment]
@mpg Sorry for the delay - it should be ready for review now. Will post the framework pr in a moment.

**Review by minosgalanakis — DISMISSED** [review]
LGTM

**Review by minosgalanakis — DISMISSED** [review]
LGTM

File: include/mbedtls/debug.h [hunk 1]
```diff
@@ -108,16 +108,16 @@
  *
  * This module provides debugging functions.
  */
-#if (defined(__MINGW32__) && __USE_MINGW_ANSI_STDIO == 0) || (defined(_MSC_VER) && _MSC_VER < 1800)
+#if defined(__MINGW32__) || (defined(_MSC_VER) && _MSC_VER < 1900)
```
Comment (gilles-peskine-arm) [inline include/mbedtls/debug.h:111]: I've been wondering: is it really meaningful to have these conditional definitions in a public header? Doesn't it depend on what libc mbedtls is linked against? Which could even be determined at runtime if the application is linked dynamically, which is pretty likely on Windows.

Mind you, in the LTS branches, we probably can't change anything, at most we might want to document any potential problems. And in development, we probably should make parts of `debug.h` private — those macros are really only intended to be used from TLS, not from applications. Filed as https://github.com/Mbed-TLS/mbedtls/issues/10054.

Comment (gilles-peskine-arm) [inline include/mbedtls/debug.h:111]: Does modern mingw still need the nonstandard definitions?

Note that in 3.6, we already require Visual Studio 2017 or above. So in 3.6 and development, the only reason to still support VS 2013 is our own CI scripts, which test with VS 2013 because that's what we want on 2.28. But 2.28 is reaching EOL so that soon won't be a concern anymore.

Comment (gilles-peskine-arm) [inline include/mbedtls/debug.h:111]: https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-140#size-prefixes-for-printf-and-wprintf-format-type-specifiers and https://stackoverflow.com/questions/15610053/correct-printf-format-specifier-for-size-t-zu-or-iu/44055215#44055215 confirm that `_MSC_VER == 1900` is enough to get `%zu` and `%lld`.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
This mostly looks good to me, and thank you very much for writing a non-regression test.

However, I'm uncomfortable with the way we're smuggling a string via a string literal whose address is passed via an integer. I'm afraid this might break on mildly exotic platforms or with changes to `generate_test_code.py`. I would really prefer a more conventional approach.

File: include/mbedtls/debug.h (hunk 1 above)
Comment (bensze01) [reply include/mbedtls/debug.h:111]: >Does modern mingw still need the nonstandard definitions?

That's what it looks like, at least for the combination of Mingw-w64 8.3.0 and vsnprintf. We have the same check for MinGW in [platform.h](https://github.com/Mbed-TLS/TF-PSA-Crypto/blob/7d941e84a5b5c77f642186075ef45b3cc3214d57/drivers/builtin/include/mbedtls/platform.h#L52-L55)

File: tests/suites/test_suite_debug.function [hunk 2]
```diff
@@ -44,14 +59,78 @@ static void string_debug(void *data, int level, const char *file, int line, cons
...
  * END_DEPENDENCIES
  */
 
 /* BEGIN_CASE */
+void printf_int_expr(intmax_t smuggle_format_expr, /* TODO: teach test framework about string expressions */
+                     intmax_t sizeof_x, intmax_t x, char *result)
+{
+#if defined(_WIN32)
+    /* Windows treats any invalid format specifiers passsed to the CRT as fatal assertion failures.
+       Disable this behaviour temporarily, so the rest of the test cases can complete. */
```
[the remark this answers is not in the document]
Comment (mpg) [reply tests/suites/test_suite_debug.function:93]: Pretty much what we were observing initially and that we were finding quite mysterious.

File: include/mbedtls/debug.h (hunk 1 above)
Comment (bensze01) [reply include/mbedtls/debug.h:111]: It should be sufficient to use the macros from `inttypes.h` everywhere, now that we have dropped support for Visual Studio 2010, and removed the compat header that shadowed `inttypes.h` - but transitioning to this strategy in the development feels out of scope for this PR.

**Review by gilles-peskine-arm — APPROVED** [review]
Thanks for simplifying the test data. LGTM

**Comment by minosgalanakis** [comment]
LGTM

**Review by minosgalanakis — APPROVED** [review]
LGTM
