### PR TITLE
Fix compilation with MinGW32

### LINKED ISSUE #2087: mingw doesn't have gmtime_s()
### Description
- Type: Bug
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
linux|windows

**mbed TLS build:**  
Version: 0592ea772aee48ca1e6d9eb84eca8e143033d973

Building with mingw32, with the default configuration fails because mingw doesn't have `gmtime_s()`.

Extract from the build:
```
"  CC    platform.c"
"  CC    platform_util.c"
platform_util.c: In function 'mbedtls_platform_gmtime_r':
platform_util.c:109:15: warning: implicit declaration of function 'gmtime_s' [-W
implicit-function-declaration]
     return( ( gmtime_s( tm_buf, tt ) == 0 ) ? tm_buf : NULL );
               ^~~~~~~~
"  CC    poly1305.c"
"  CC    ripemd160.c"
"  CC    rsa_internal.c"
"  CC    rsa.c"
"  CC    sha1.c"
"  CC    sha256.c"
"  CC    sha512.c"
"  CC    threading.c"
"  CC    timing.c"
"  CC    version.c"
"  CC    version_features.c"
"  CC    xtea.c"
"  AR    libmbedcrypto.a"
"  CC    certs.c"
"  CC    pkcs11.c"
"  CC    x509.c"
"  CC    x509_create.c"
"  CC    x509_crl.c"
"  CC    x509_crt.c"
"  CC    x509_csr.c"
"  CC    x509write_crt.c"
"  CC    x509write_csr.c"
"  AR    libmbedx509.a"
"  CC    debug.c"
"  CC    net_sockets.c"
"  CC    ssl_cache.c"
"  CC    ssl_ciphersuites.c"
"  CC    ssl_cli.c"
"  CC    ssl_cookie.c"
"  CC    ssl_srv.c"
"  CC    ssl_ticket.c"
"  CC    ssl_tls.c"
"  AR    libmbedtls.a"
"  Gen   test_suite_x509parse.c"
"  CC    test_suite_x509parse.c"
../library/libmbedcrypto.a(platform_util.o):platform_util.c:(.text+0x44): undefi
ned reference to `gmtime_s'
collect2.exe: error: ld returned 1 exit status
Makefile:102: recipe for target 'test_suite_x509parse.exe' failed
mingw32-make[1]: *** [test_suite_x509parse.exe] Error 1
Makefile:21: recipe for target 'tests' failed
mingw32-make: *** [tests] Error 2
```

Mingw version:
```
C:\mbedtls\>gcc --version
gcc (MinGW.org GCC-6.3.0-1) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The build should work out of the box (or tarball).

### PR DESCRIPTION
**Pull request by ccawley2011**
## Description
Fixes #2087. MinGW-w64 should be unaffected by this change.

## Status
READY

## Requires Backporting

No - not worth backporting to an LTS

## Migrations

NO

## Todos
- [x] Tests
- [x] Changelog updated

### CODE REVIEW

File: library/platform_util.c [hunk 1]
```diff
@@ -103,7 +105,7 @@ void mbedtls_platform_zeroize( void *buf, size_t len )
 struct tm *mbedtls_platform_gmtime_r( const mbedtls_time_t *tt,
                                       struct tm *tm_buf )
 {
-#if defined(_WIN32) && !defined(EFIX64) && !defined(EFI32)
+#if defined(_WIN32) && !defined(PLATFORM_UTIL_USE_GMTIME)
     return( ( gmtime_s( tm_buf, tt ) == 0 ) ? tm_buf : NULL );
 #elif !defined(PLATFORM_UTIL_USE_GMTIME)
     return( gmtime_r( tt, tm_buf ) );
```
Comment (chris-jones-arm) [inline library/platform_util.c:111]: There is a bug in this if/elif statement (not created by you, this is already there). Firstly `#if defined(_WIN32) && !defined(EFIX64) && !defined(EFI32)` is exactly the same as `!defined(PLATFORM_UTIL_USE_GMTIME)` so the if statement can be shortened to just `!defined(PLATFORM_UTIL_USE_GMTIME)`.

Secondly this means that the if condition is identical to the elif section and it will not and has never run. In terms of what it should be I'm not entirely sure because I'm not too familiar with what mingw32 does and does not support, from what I can tell neither `gmtime_s` or `gmtime_r`. Any other opinions would be appreciated on this.

File: tests/suites/helpers.function [hunk 2]
```diff
@@ -46,9 +46,12 @@ typedef UINT32 uint32_t;
...
 #include <string.h>
 
+#if defined(__unix__) || (defined(__APPLE__) && defined(__MACH__)) || defined(__MINGW32__)
+#include <strings.h>
+#endif
+
 #if defined(__unix__) || (defined(__APPLE__) && defined(__MACH__))
 #include <unistd.h>
-#include <strings.h>
 #endif
```
Comment (chris-jones-arm) [inline tests/suites/helpers.function:55]: If `__MINGW32__` is not defined but the rest of these definitions are defined then `strings.h` should still be included.

**Review by chris-jones-arm — COMMENTED** [review]
A few things to address here including a bug (although it was not created by you). Unfortunately my knowledge is limited when it comes to mingw and windows builds so if you or anyone else can provide some suggestions that would be appreciated.

File: tests/suites/helpers.function (hunk 2 above)
Comment (gilles-peskine-arm) [reply tests/suites/helpers.function:55]: About `strings.h` specifically, it's only needed for one call to `strcasecmp` in `test_suite_mpi.function`. (In past versions that are now all out of support, it was used in many more places.) It would be easy to do without it, so if the use of `strings.h` or the aliasing of `strcmp` to `_stricmp` is a problem, we can just get rid of it.

**Comment by daverodgman** [comment]
Added fix for #4015 

I think all review comments have been addressed, so should be ready for review.

**Comment by gilles-peskine-arm** [comment]
> If this is a bug fix does it need backporting?

The primary audience of long-term support branches is people who are already using Mbed TLS in a particular setting, and want it to keep working. The focus is on problems that these people always had, but didn't know they were having, such as bad behavior on certain inputs which had always been possible but had never been noticed.

In terms of platform portability, this means that fixing an incompatibility with a newer version of an already-supported platform is important — we want users to be able to upgrade their compiler or operating system and keep running their application. Fixing an incompatibility that had always existed is less important since it only affects users who are doing something new (porting their application to a new platform). 

Since this patch is of the latter kind, and there's some risk that it would break a platform where the library does work, I'm inclined to not backport.

**Comment by daverodgman** [comment]
Rebased against development to try and address CI issue

File: library/platform_util.c [hunk 3]
```diff
@@ -74,6 +74,7 @@ void mbedtls_platform_zeroize( void *buf, size_t len )
 #endif /* MBEDTLS_PLATFORM_ZEROIZE_ALT */
 
 #if defined(MBEDTLS_HAVE_TIME_DATE) && !defined(MBEDTLS_PLATFORM_GMTIME_R_ALT)
+#define __STDC_WANT_LIB_EXT1__ 1
```
Comment (tom-cosgrove-arm) [inline library/platform_util.c:77]: Is it useful to say

```suggestion
#define __STDC_WANT_LIB_EXT1__ 1    /* Gets us gmtime_s() under Visual Studio */
```

**Review by tom-cosgrove-arm — APPROVED** [review]

File: tests/suites/helpers.function (hunk 2 above)
Comment (chris-jones-arm) [reply tests/suites/helpers.function:53]: My previous comment is wrong, as `string.h` is still included when `__MINGW32__` is not defined.

**Review by chris-jones-arm — APPROVED** [review]
Looks like all the comments are addressed so LGTM.
