### PR TITLE
Fix compilation when memcpy() is a function-like macro

### LINKED ISSUE #8994: error: memcpy(): too few arguments provided to function-like macro invocation
### Summary

mbedtls 3.6.0 fails to build on macOS 10.12 and earlier due to wrong number of arguments to `memcpy`, because `memcpy()` is a function-like macro there.

### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: macOS 10.12
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): from Xcode 9.2
```
$ /usr/bin/clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Additional environment information: 

### Expected behavior

successful build

### Actual behavior

https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/266113/steps/install-port/logs/stdio

```
[ 82%] Building C object library/CMakeFiles/mbedtls_static.dir/ssl_tls13_generic.c.o
cd /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/build/library && /usr/bin/clang  -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/include -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/library -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/build/library -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/3rdparty/everest/include -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/3rdparty/p256-m -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/3rdparty/p256-m/p256-m -pipe -Os -DNDEBUG -I/opt/local/include -Wall -Wextra -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wvla -Wformat=2 -Wno-format-nonliteral -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -std=c99 -arch x86_64 -mmacosx-version-min=10.12 -MD -MT library/CMakeFiles/mbedtls_static.dir/ssl_tls13_generic.c.o -MF CMakeFiles/mbedtls_static.dir/ssl_tls13_generic.c.o.d -o CMakeFiles/mbedtls_static.dir/ssl_tls13_generic.c.o -c /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/library/ssl_tls13_generic.c
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/library/ssl_tls13_generic.c:196:79: error: too few arguments provided to function-like macro invocation
        memcpy(verify_buffer + idx, MBEDTLS_SSL_TLS1_3_LBL_WITH_LEN(client_cv));
                                                                              ^
/usr/include/secure/_string.h:64:9: note: macro 'memcpy' defined here
#define memcpy(dest, src, len)                                  \
        ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/library/ssl_tls13_generic.c:196:9: warning: expression result unused [-Wunused-value]
        memcpy(verify_buffer + idx, MBEDTLS_SSL_TLS1_3_LBL_WITH_LEN(client_cv));
        ^~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/library/ssl_tls13_generic.c:199:79: error: too few arguments provided to function-like macro invocation
        memcpy(verify_buffer + idx, MBEDTLS_SSL_TLS1_3_LBL_WITH_LEN(server_cv));
                                                                              ^
/usr/include/secure/_string.h:64:9: note: macro 'memcpy' defined here
#define memcpy(dest, src, len)                                  \
        ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/library/ssl_tls13_generic.c:199:9: warning: expression result unused [-Wunused-value]
        memcpy(verify_buffer + idx, MBEDTLS_SSL_TLS1_3_LBL_WITH_LEN(server_cv));
        ^~~~~~
2 warnings and 2 errors generated.
```

### Steps to reproduce

Build mbedtls 3.6.0 on macOS 10.12 or earlier

### Additional information

Here is how a similar bug was fixed in another project:

https://redmine.lighttpd.net/issues/2772

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
Fixes #8994

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **backport 2.28** not required - this code is in TLS 1.3, which is not present in 2.28
- [x] **backport 3.6** done - #9000
- [x] **tests** ~provided, or~ not required

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
CI failure on `all_u16-test_default_psa_crypto_client_without_crypto_provider` appears to be an infrastructure problem, and the OpenCI PR tests job completed successfully

File: ChangeLog.d/fix-compilation-when-memcpy-is-function-like-macro.txt [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Bugfix
+   * Fix compilation error when memcpy() is a function-like macros. Fixes #8994.
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/fix-compilation-when-memcpy-is-function-like-macro.txt:2]: Unfortunately this might come back by accident, possibly on a different standard library function. (With internal functions, it's ok, we know that they aren't macros.) It's not really practical to test for this in the CI (I don't think this unusual platform justifies a new test component).

Maybe we can at least document it? `MBEDTLS_SSL_TLS1_3_LBL_WITH_LEN` doesn't have documentation at all. It would be nice to have some usage guidance.

(And more generally, I'm not fond of unhygienic macros like `MBEDTLS_SSL_TLS1_3_LBL_WITH_LEN`, but in this case I think it's a lesser evil compared with the risk of mismatching pointer and size, which has a very high security impact.)

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM (although ideally I'd like some documentation in lieu of a non-regression test).

File: ChangeLog.d/fix-compilation-when-memcpy-is-function-like-macro.txt (hunk 1 above)
Comment (tom-cosgrove-arm) [reply ChangeLog.d/fix-compilation-when-memcpy-is-function-like-macro.txt:2]: > this might come back by accident

Actually, I disagree - I think this type of macro is very unusual, and matching it up to a C library call even more unusual, so I don't think we lose anything by addressing any such failures if and when they arise.

> Maybe we can at least document it?

Yes, it needs to be documented, but that is clearly out of scope of this PR. I'll raise an issue if you like

**Review by paul-elliott-arm — APPROVED** [review]
LGTM
