### PR TITLE
Misc. clean-ups in `check_config.h`

### LINKED ISSUE #8796: check_config.h should only check, not adjust
In Mbed TLS 3.5 and still on development as of 1d7bc1ecdf04db9b137931442fd46fe278813f2b, [`check_config.h`](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/check_config.h) doesn't only perform checks but also defines helper symbols, e.g.

```
#if defined(MBEDTLS_SHA256_C) || \
    (defined(MBEDTLS_PSA_CRYPTO_C) && defined(PSA_WANT_ALG_SHA_256))
#define MBEDTLS_MD_HAVE_SHA256
#endif
```

These definitions should be in `include/config_adjust_*.h` (or `include/psa/crypto_adjust_*.h` if defining a `PSA_WANT` symbol, but there are no instances of that at the moment). Having them in `check_config.h` is a problem because:

* It's surprising to maintainers (it's unexpected that “check” can change things).
* It may cause bugs because the symbols are defined after some other place that consumes them. I don't know if any of the symbols currently defined in `check_config.h` are affected, but it has been a problem in the past, which led to the creation of the `adjust` headers with a carefully planned inclusion order. See https://github.com/Mbed-TLS/mbedtls/issues/7609, https://github.com/Mbed-TLS/mbedtls/pull/8159.
* It relies on `check_config.h` being always included, which [is something we're planning to stop](https://github.com/Mbed-TLS/mbedtls/issues/8105) (though this won't happen in 3.x, and in 4.0 many of the auxiliary symbols will be obsolete).

### PR DESCRIPTION
**Pull request by mpg**
## Description

Resolves #8796 - systematically chasing `#define`s in `check_config.h` -  but also a few more things I had noticed while looking at #8797.

## PR checklist

- [x] **changelog** not required - internal changes
- [x] **backport** not required - only in development (mostly leftovers from driver-only work)
- [x] **tests** not required - covered by existing `all.sh` components

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
The CI's unhappy about ECJPAKE.

**Comment by gilles-peskine-arm** [comment]
Now the tests are happy but DCO isn't.

**Review by valeriosetti — APPROVED** [review]
LGTM

File: include/mbedtls/check_config.h [hunk 1]
```diff
@@ -468,23 +468,19 @@
...
+    !defined(MBEDTLS_MD_CAN_RIPEMD160) && \
+    !defined(MBEDTLS_MD_CAN_SHA1) && \
+    !defined(MBEDTLS_MD_CAN_SHA224) && \
+    !defined(MBEDTLS_MD_CAN_SHA256) && \
+    !defined(MBEDTLS_MD_CAN_SHA384) && \
+    !defined(MBEDTLS_MD_CAN_SHA512) && \
+    !defined(MBEDTLS_MD_CAN_SHA3_224) && \
+    !defined(MBEDTLS_MD_CAN_SHA3_256) && \
+    !defined(MBEDTLS_MD_CAN_SHA3_384) && \
+    !defined(MBEDTLS_MD_CAN_SHA3_512)
```
Comment (gilles-peskine-arm) [inline include/mbedtls/check_config.h:399]: > Fix: SHA-3 was forgotten.

Hmmm. It's the job of `depends.py` to tell us this. Unfortunately it gives up too easily:

```
            # Hash algorithms. Excluding exclusive domains of MD, RIPEMD, SHA1,
            # SHA224 and SHA384 because MBEDTLS_ENTROPY_C is extensively used
            # across various modules, but it depends on either SHA256 or SHA512.
            # As a consequence an "exclusive" test of anything other than SHA256
            # or SHA512 with MBEDTLS_ENTROPY_C enabled is not possible.
```

I'm not sure about this comment. `MBEDTLS_ENTROPY_C` is used extensively in _programs_, so a build without it will cause a lot of programs to be unusable, but that's the case of many of the builds in our CI. `MBEDTLS_ENTROPY_C` is only used in a few test cases, and is not used by any other library module except PSA. Furthermore PSA can do without it if `MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG`.

So I think there's an easy fix here in `depends.py`. It's out of scope in this pull request. I'm going to try it out and see if there are surprises.

File: include/mbedtls/config_adjust_legacy_crypto.h [hunk 2]
```diff
@@ -22,6 +22,22 @@
 #ifndef MBEDTLS_CONFIG_ADJUST_LEGACY_CRYPTO_H
 #define MBEDTLS_CONFIG_ADJUST_LEGACY_CRYPTO_H
 
+/* Ideally, we'd set those as defaults in mbedtls_config.h, but
+ * putting an #ifdef _WIN32 in mbedtls_config.h would confuse config.py.
+ *
+ * So, adjust it here.
+ * Not related to crypto, but this is the bottom of the stack. */
```
Comment (gilles-peskine-arm) [inline include/mbedtls/config_adjust_legacy_crypto.h:29]: We should probably have a `config_adjust_platform.h`. But that can wait until 4.0.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM
