### PR TITLE
3.6: Disable new session tickets at runtime

### LINKED ISSUE #8749: How to handle TLS 1.3 new session ticket errors
Lately I've been seeing some failed connection in TLS1.3 with mbedtls v3.3 because I was getting a MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET returned from a mbedtls_ssl_write() call.

According to the API doc write() should lead to a reset whenever an error different from WANT_READ, WANT_WRITE, ASYNC_IN, CRYPTO_IN_PROGRESS or CLIENT_RECONNECT is received. So the app was rightfully closing the connection with the new session ticket error. Note that this was both with session tickets enabled and disabled client side.

The only documentation I found about this error just says it's experimental and may go away but says nothing as far as I could find about how to handle it.

Now reading here and there it seems it is indeed safe to ignore this error, at least in mbedtls_ssl_handshake_step(), mbedtls_ssl_handshake() and mbedtls_ssl_read()) according to this [comment](https://github.com/Mbed-TLS/mbedtls/issues/8591#issuecomment-1895225797).

Unfortunately mbedtls_ssl_write is not included in that list so it's still not conclusive about how to handle it in this case.

I'd say if this error is going to stay in future releases it deserves to be better documented.

---

Edit (mpg): [status summary](https://github.com/Mbed-TLS/mbedtls/issues/8749#issuecomment-2324087214).

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description
Fix #8749 

## PR checklist
- [x] **changelog** provided
- [ ] **development PR** TODO (content TBD; can wait until after the 3.6.1 release)
- [x] **framework PR** not required
- [x] **3.6 PR** here
- [x] **2.28 PR** not required because: no TLS 1.3
- **tests**  partly provided, partly manual (merge with #9505 and run `programs/ssl/tls13_client_demo.sh`)

### CODE REVIEW

File: include/mbedtls/ssl.h [hunk 1]
```diff
@@ -4478,6 +4492,20 @@ void mbedtls_ssl_conf_preference_order(mbedtls_ssl_config *conf, int order);
  *                                         MBEDTLS_SSL_SESSION_TICKETS_DISABLED)
  */
 void mbedtls_ssl_conf_session_tickets(mbedtls_ssl_config *conf, int use_tickets);
+
+#if defined(MBEDTLS_SSL_PROTO_TLS1_3)
+/**
+ * \brief Enable / Disable TLS 1.3 handling of NewSessionTicket messages (client and TLS 1.3 only).
+ *        (Default: MBEDTLS_SSL_ENABLE_NEW_SESSION_TICKETS_DISABLED)
```
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:4499]: Please document somewhere (here would be a good place) that this defaults off for backward compatibility with non-1.3-aware applications written before 3.6.0. (Similar to e.g. [this](https://github.com/Mbed-TLS/mbedtls/pull/9501/files#diff-b9b23ef0e168bb80241e10e0308a5e7859922a01c0090984b484f2e9f388ce92R1894).)

File: include/mbedtls/ssl.h [hunk 2]
```diff
@@ -4887,6 +4915,13 @@ int mbedtls_ssl_get_session(const mbedtls_ssl_context *ssl,
  * \return         #MBEDTLS_ERR_SSL_HELLO_VERIFY_REQUIRED if DTLS is in use
  *                 and the client did not demonstrate reachability yet - in
  *                 this case you must stop using the context (see below).
+ * \return         #MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET if a TLS 1.3
```
[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:4918]: > Please document that after this error, the context remains usable and, after optionally retrieving the ticket data, you may continue using the connection as if this error hadn't happened.

This is done below with the other error codes of the same kind.

File: include/mbedtls/ssl.h [hunk 3]
```diff
@@ -84,8 +84,13 @@
 #define MBEDTLS_ERR_SSL_BAD_CERTIFICATE                   -0x7A00
 /* Error space gap */
 /**
```
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:86]: Missing: changelog entry

Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:86]: Testing: with the merge of https://github.com/Mbed-TLS/mbedtls/commit/6179f6d456ba94384292cd282cf3359bc3ba1d12 and https://github.com/Mbed-TLS/mbedtls/pull/9505/commits/f0eaaa01c12807fce59832fcc5a1a27bf58aa31b, `programs/ssl/tls13_client_demo.sh` passes.

File: programs/ssl/ssl_client2.c [hunk 4]
```diff
@@ -198,7 +199,8 @@ int main(void)
 
 #if defined(MBEDTLS_SSL_SESSION_TICKETS)
 #define USAGE_TICKETS                                       \
-    "    tickets=%%d          default: 1 (enabled)\n"
+    "    tickets=%%d              default: 1 (enabled)\n"    \
+    "    new_session_tickets=%%d  default: 1 (enabled)\n"
```
Comment (mpg) [inline programs/ssl/ssl_client2.c:203]: Minor: as a matter of principle, options in `ssl_client2` should default to "library default", that is, not calling the corresponding `conf` function at all. That's the only way to test the the library defaults are what we think they are.

(Not a blocker for the release, as we've agreed on manual testing for now anyway, but wanted to point it out for future reference.)

File: include/mbedtls/ssl.h (hunk 3 above)
Comment (mpg) [reply include/mbedtls/ssl.h:86]: In particular, for people (if any) who had working code handling 1.3 session tickets with 3.6.0, we must explicitly draw attention to the fact that they need to change their code. (Having to change your working code to keep it working is extremely unexpected in an LTS.)

File: include/mbedtls/ssl.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (mpg) [reply include/mbedtls/ssl.h:4918]: I agree with Ronald that the transient nature of this error is already documented to the same level as the other transient errors.

Regarding Gilles's 2nd point, may I suggest changing the last sentence to "You may either call [...] data, or immediately call this function again with the same parameters if you do not wish to save this ticket now."

File: programs/ssl/ssl_client2.c [hunk 5]
```diff
@@ -1226,6 +1230,11 @@ int main(int argc, char *argv[])
             if (opt.tickets < 0) {
                 goto usage;
             }
+        } else if (strcmp(p, "new_session_tickets") == 0) {
+            opt.tickets = atoi(q);
```
Comment (mpg) [inline programs/ssl/ssl_client2.c:1234]: Copy-pasta: I assume you mean `opt.new_session_tickets` here. (This also highlights the lack of testing. Again, not a blocker, but we'll probably want a follow-up.)

**Review by mpg — COMMENTED** [review]
I'm happy with the core of the fix and only have minor feedback.

File: include/mbedtls/ssl.h [hunk 6]
```diff
@@ -84,8 +84,13 @@
...
- * Received NewSessionTicket Post Handshake Message.
- * This error code is experimental and may be changed or removed without notice.
+ * A TLS 1.3 NewSessionTicket message has been received.
+ * This error code can be returned only on client side if and only if handling
+ * of TLS 1.3 NewSessionTicket messages has been enabled through the
+ * mbedtls_ssl_conf_enable_new_session_tickets() API. This error
+ * code can then be returned by mbedtls_ssl_handshake(),
+ * mbedtls_ssl_handshake_step(), mbedtls_ssl_read(), mbedtls_ssl_write() and
+ * mbedtls_ssl_write_early_data().
```
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:93]: We can't have long error descriptions because of a [limitation in `generate_errors.pl`: it grabs the whole thing](https://github.com/Mbed-TLS/mbedtls/issues/8783). (Preexisting problem for `MBEDTLS_ERR_SSL_CANNOT_READ_EARLY_DATA` by the way.)

File: include/mbedtls/ssl.h [hunk 7]
```diff
@@ -1447,6 +1455,12 @@ struct mbedtls_ssl_config {
 #if defined(MBEDTLS_SSL_SESSION_TICKETS) && \
     defined(MBEDTLS_SSL_CLI_C)
     uint8_t MBEDTLS_PRIVATE(session_tickets);   /*!< use session tickets? */
+#if defined(MBEDTLS_SSL_PROTO_TLS1_3)
+    /** Whether we handle NewSessionTicket TLS 1.3 messages (<>0) or just ignore them (==0)
+     *  They are ignored by default.
+     */
+    uint8_t MBEDTLS_PRIVATE(new_session_tickets_enabled);
```
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:1462]: BLOCKER: We cannot change the size or layout of `mbedtls_ssl_config` in an LTS branch: it's an ABI break. For example, `mbedtls_ssl_config` might be on the application stack.

We can piggyback on `session_tickets` which currently only uses two values in an 8-bit field.

File: include/mbedtls/ssl.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply include/mbedtls/ssl.h:4918]: I'm not going to insist on polishing the documentation in an emergency fix, but “other parts of the documentation suck” is not a good reason to have new documentation that sucks. Especially when it's a surprising change in an LTS, which requires helping users more than usual. But I'm ok with keeping what we have here for this pull request and filing a documentation improvement as a 3.6.2 blocker.

File: library/ssl_msg.c [hunk 8]
```diff
@@ -5595,11 +5595,17 @@ static int ssl_tls13_handle_hs_message_post_handshake(mbedtls_ssl_context *ssl)
         if (ssl_tls13_is_new_session_ticket(ssl)) {
 #if defined(MBEDTLS_SSL_SESSION_TICKETS)
             MBEDTLS_SSL_DEBUG_MSG(3, ("NewSessionTicket received"));
-            ssl->keep_current_message = 1;
+            if (ssl->conf->new_session_tickets_enabled ==
+                MBEDTLS_SSL_ENABLE_NEW_SESSION_TICKETS_ENABLED) {
```
Comment (gilles-peskine-arm) [inline library/ssl_msg.c:5599]: Not a blocker, but `xxx_enabled` looks like a boolean setting to me, so I'd expect
```suggestion
            if (ssl->conf->new_session_tickets_enabled) {
```

File: include/mbedtls/ssl.h [hunk 9]
```diff
@@ -324,6 +329,9 @@
 #define MBEDTLS_SSL_SESSION_TICKETS_DISABLED     0
 #define MBEDTLS_SSL_SESSION_TICKETS_ENABLED      1
 
+#define MBEDTLS_SSL_ENABLE_NEW_SESSION_TICKETS_DISABLED  0
+#define MBEDTLS_SSL_ENABLE_NEW_SESSION_TICKETS_ENABLED   1
```
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:333]: This looks like a boolean setting. Why are we defining aliases for true and false? Are we going to add `MBEDTLS_SSL_ENABLE_NEW_SESSION_TICKETS_FILE_NOT_FOUND` later?

File: library/ssl_msg.c [hunk 10]
```diff
@@ -5595,11 +5595,17 @@ static int ssl_tls13_handle_hs_message_post_handshake(mbedtls_ssl_context *ssl)
...
+                ssl->keep_current_message = 1;
 
-            mbedtls_ssl_handshake_set_state(ssl,
-                                            MBEDTLS_SSL_TLS1_3_NEW_SESSION_TICKET);
-            return MBEDTLS_ERR_SSL_WANT_READ;
+                mbedtls_ssl_handshake_set_state(ssl,
+                                                MBEDTLS_SSL_TLS1_3_NEW_SESSION_TICKET);
+                return MBEDTLS_ERR_SSL_WANT_READ;
+            } else {
+                MBEDTLS_SSL_DEBUG_MSG(3, ("Ignore NewSessionTicket, disabled."));
```
Comment (gilles-peskine-arm) [inline library/ssl_msg.c:5606]: “Ignore” sounds like an instruction for the user, rather than a commentary on what is happening. Also “disabled” written as a second part of the sentence looks like it might mean “I have disabled it” rather than “[because] it is disabled”.
```suggestion
                MBEDTLS_SSL_DEBUG_MSG(3, ("Ignoring NewSessionTicket (signal disabled)."));
```

File: tests/src/test_helpers/ssl_helpers.c [hunk 11]
```diff
@@ -2543,6 +2543,9 @@ int mbedtls_test_get_tls13_ticket(
                                          server_options, NULL, NULL, NULL);
     TEST_EQUAL(ret, 0);
 
+    mbedtls_ssl_conf_enable_new_session_tickets(
+        &client_ep.conf, MBEDTLS_SSL_ENABLE_NEW_SESSION_TICKETS_ENABLED);
```
Comment (gilles-peskine-arm) [inline tests/src/test_helpers/ssl_helpers.c:2547]: Test coverage: as of 0e5d4fdfc56540ecc23809f006e83f5cea3c26a5:

* Unit tests have the NewSessionTickets error enabled.
* All the ssl-opt test cases have the NewSessionTickets error enabled.
* `ssl_client1.c` has the NewSessionTickets error disabled, but does not run on the CI.

I'm ok with this as an emergency fix for 3.6.1. For 3.6.2, we must have proper test coverage. At the very least, we must merge https://github.com/Mbed-TLS/mbedtls/pull/9505, which will give us coverage of NewSessionTickets error disabled on the CI. Preferably we should also have unit tests for this setting. It's a setting added to an LTS in a hurry, so good test coverage is especially important to make sure we don't accidentally screw it up more.

File: programs/ssl/ssl_client2.c (hunk 5 above)
Comment (ronald-cron-arm) [reply programs/ssl/ssl_client2.c:1234]: Oops, thanks.

File: include/mbedtls/ssl.h (hunk 3 above)
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:86]: We need a two changelog entries:

* Bug fix: some connections that worked in 3.5 no longer work in 3.6.0.
* Behavior change: applications that were relying on the semi-documented behavior of `MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET` now need to call a function to enable this behavior.

File: include/mbedtls/ssl.h (hunk 1 above)
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:4499]: (Repeating an earlier comment so it doesn't get forgotten) Please document somewhere (here would be a good place) that this defaults off for backward compatibility with non-1.3-aware applications written before 3.6.0. (Similar to e.g. [this](https://github.com/Mbed-TLS/mbedtls/pull/9501/files#diff-b9b23ef0e168bb80241e10e0308a5e7859922a01c0090984b484f2e9f388ce92R1894).)

File: include/mbedtls/ssl.h (hunk 9 above)
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl.h:333]: Naming: we aren't really enabling “new session tickets”, we're enabling the error code that signals that a NewSessionTicket message was received.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
* Blocker: ABI break.
* Blocker: changelog entries.
* Should be improved in 3.6.1, must be improved in 3.6.2: documentation.
* Ok for 3.6.1, must be improved in 3.6.2: test coverage.

Manual testing: on the merge of 0e5d4fdfc5 with f0eaaa01c1 (from #9505), `programs/ssl/tls13_client_demo.sh` passes.

File: include/mbedtls/ssl.h (hunk 6 above)
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:93]: okay what is the usual way to deal with that then?

File: include/mbedtls/ssl.h (hunk 9 above)
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:333]: It is not only enabling the error code, if disabled we do not parse the NewSessionTicket message at all.

File: include/mbedtls/ssl.h (hunk 6 above)
Comment (gilles-peskine-arm) [reply include/mbedtls/ssl.h:93]: The usual way is to write a simple sentence as the error description, and lobby our management for time to fix our technical debt.

File: include/mbedtls/ssl.h (hunk 9 above)
Comment (gilles-peskine-arm) [reply include/mbedtls/ssl.h:333]: What does “we do not parse the NewSessionTicket message at all” mean? That we silently discard any message whose header says it's a NewSessionTicket, regardless of whether it's valid or not?

Comment (gilles-peskine-arm) [reply include/mbedtls/ssl.h:333]: For example, if an application calls `mbedtls_ssl_session_save` after each successful call to `mbedtls_ssl_handshake` or `mbedtls_ssl_read`, would it get updated session tickets? I thought it would, since the [code that changes depending on the configuration](https://github.com/Mbed-TLS/mbedtls/pull/9507/files#diff-67127675c5612072a0cb4c12b6dd40b0cfdcc6cdb23839f48ce9e3a2257e77e7) is only code that raises the error, not parsing code.

File: library/ssl_msg.c (hunk 8 above)
Comment (ronald-cron-arm) [reply library/ssl_msg.c:5599]: `new_session_tickets_enabled` has been removed thus things are different here now.

File: include/mbedtls/ssl.h (hunk 9 above)
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:333]: I've just followed what we have for `mbedtls_ssl_conf_session_tickets` and the definition of `MBEDTLS_SSL_SESSION_TICKETS_DISABLED` and `MBEDTLS_SSL_SESSION_TICKETS_ENABLED`.

File: tests/src/test_helpers/ssl_helpers.c (hunk 11 above)
Comment (ronald-cron-arm) [reply tests/src/test_helpers/ssl_helpers.c:2547]: I've added two ssl-opt.sh tests with NewSessionTicket handling disabled at runtime similar to the two ones we have for tickets being disabled at build time.

File: include/mbedtls/ssl.h (hunk 9 above)
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:333]: discussed offline, I think we have covered that.

Comment (mpg) [reply include/mbedtls/ssl.h:333]: At this point we should emulate what other similar settings are doing, which is have the enabled/disabled macros.

(In the future, I'd be happy to `#include <stdbool.h>` and remove all these aliases for true and false.)

File: include/mbedtls/ssl.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (mpg) [reply include/mbedtls/ssl.h:4918]: > “other parts of the documentation suck” is not a good reason to have new documentation that sucks

Agreed, but that's not what I was saying. I think the current structure "return X for success, Y if yyy and then you should do YYY, etc. - anything else is a fatal error and means you must stop using the context" + "warning: if this function returns anything other than X, Y, etc. then you must stop using the context" is clear enough.

If you're unhappy with this structure, OK, we can improve it, but then let's revisit the whole structure, not just this part.

PS: though as I said above, I think being clear on what you should do when receiving this error would be useful. Thinking about it, my previous suggestion was incomplete: "You may either call [...] data _and then call this function again with the same arguments_, or immediately call this function again with the same arguments if you do not wish to save this ticket now." (Emphasis to highlight the part I added, not to be included in the documentation.)

File: programs/ssl/ssl_client2.c (hunk 4 above)
Comment (ronald-cron-arm) [reply programs/ssl/ssl_client2.c:203]: Otherwise I would have to enable the new session tickets in all ssl-opt.sh resumption tests. Not changed yet but I can if you think it is worth it.

Comment (mpg) [reply programs/ssl/ssl_client2.c:203]: Not now, let's leave that to a follow-up.

**Comment by ronald-cron-arm** [comment]
@mpg @gilles-peskine-arm I believe I have addressed all the comments. The CI seems green included the ABI/API checks. Thus this seems in a proper state for further review, thanks.

File: include/mbedtls/ssl.h [hunk 12]
```diff
@@ -4498,8 +4498,31 @@ void mbedtls_ssl_conf_session_tickets(mbedtls_ssl_config *conf, int use_tickets)
...
- *        (Default: MBEDTLS_SSL_ENABLE_NEW_SESSION_TICKETS_DISABLED)
+ * \brief Enable / Disable handling of TLS 1.3 NewSessionTicket messages (client and TLS 1.3 only).
+ *
+ *        The handling of TLS 1.3 NewSessionTicket messages is disabled by
+ *        default.
+ *
+ *        Contrary to TLS 1.2 tickets, the default value is disabled in Mbed TLS
+ *        3.6.x for backward compatibility with applications based on the Mbed TLS
+ *        client in the default configuration connecting to TLS 1.3 servers
+ *        supporting NewSessionTicket messages.
```
Comment (mpg) [inline include/mbedtls/ssl.h:4502]: Sorry, I don't understand this sentence, in particular "applications based on the Mbed TLS client".

File: include/mbedtls/ssl.h [hunk 13]
```diff
@@ -4496,6 +4490,16 @@ void mbedtls_ssl_conf_preference_order(mbedtls_ssl_config *conf, int order);
...
 
+/**
+ * \brief          Get if TLS 1.2 session tickets usage is enabled or not
+ *
+ * \param conf     SSL configuration
+ *
+ * \return         MBEDTLS_SSL_SESSION_TICKETS_ENABLED or
+ *                 MBEDTLS_SSL_SESSION_TICKETS_DISABLED
+ */
+int mbedtls_ssl_conf_get_session_tickets(const mbedtls_ssl_config *conf);
```
Comment (mpg) [inline include/mbedtls/ssl.h:4490]: Does this need to be a public function?

File: include/mbedtls/ssl.h [hunk 14]
```diff
@@ -4525,12 +4529,23 @@ void mbedtls_ssl_conf_session_tickets(mbedtls_ssl_config *conf, int use_tickets)
...
+
+/**
+ * \brief          Get if usage of TLS 1.3 NewSessionTicket messages is enabled or not
+ *
+ * \param conf     SSL configuration
+ *
+ * \return         MBEDTLS_SSL_NEW_SESSION_TICKETS_ENABLED or
+ *                 MBEDTLS_SSL_NEW_SESSION_TICKETS_DISABLED
+ */
+int mbedtls_ssl_conf_is_new_session_tickets_enabled(const mbedtls_ssl_config *conf);
```
Comment (mpg) [inline include/mbedtls/ssl.h:4536]: Does this need to be a public function? Also, naming is inconsistent with `mbedtls_ssl_conf_get_session_tickets()`.

File: include/mbedtls/ssl.h [hunk 15]
```diff
@@ -5121,9 +5110,16 @@ int mbedtls_ssl_renegotiate(mbedtls_ssl_context *ssl);
...
- *                 #MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET documentation
- *                 for more information.
+ *                 NewSessionTicket message has been received.
+ *                 This error code can be returned only on client side if and
+ *                 only if handling of TLS 1.3 NewSessionTicket messages has
+ *                 been enabled through the
+ *                 mbedtls_ssl_conf_enable_new_session_tickets() API. A TLS 1.3
+ *                 NewSessionTicket message has been received and parsed
+ *                 successfully by the client. Ticket data is available in the
+ *                 SSL context and remain available as long as the client does
```
Comment (mpg) [inline include/mbedtls/ssl.h:5120]: Typo: and _will_ remain

**Review by mpg — CHANGES_REQUESTED** [review]

File: include/mbedtls/ssl.h (hunk 12 above)
Comment (mpg) [reply include/mbedtls/ssl.h:4502]: Suggestion: "Contrary to TLS 1.2 tickets, the default value is disabled in Mbed TLS 3.6.x for backward compatibility with client applications developed using Mbed TLS 3.5 or earlier with the default configuration." (then perhaps merge with the next paragraph).

Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:4502]: I mean an application that is using the Mbed TLS TLS client like ssl_client2 I'd say.

File: include/mbedtls/ssl.h (hunk 13 above)
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:4490]: It is used outside ssl_tls.c. It could be a "static inline" function but then I would have to move the definition of  MBEDTLS_SSL_SESSION_TICKETS_TLS1_2/3_BIT/MASK in ssl.h. Can do if you prefer.

Comment (mpg) [reply include/mbedtls/ssl.h:4490]: I think we have `ssl_misc.h` for this kind of things (functions used in more than one C file but that don't need to be public).

File: include/mbedtls/ssl.h (hunk 14 above)
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:4536]: ditto and yes I know the name is inconsistent but the setting function is named `mbedtls_ssl_conf_enable_new_session_tickets()` and not `mbedtls_ssl_conf_new_session_tickets()`. It is not mbedtls_ssl_conf_new_session_tickets()` because it already exists (setting the number of tickets to send after the handshake on server side). That's why I felt uncomfortable to name it `mbedtls_ssl_conf_get_new_session_tickets()` as I felt it would be associated with `mbedtls_ssl_conf_new_session_tickets()` which is not the case.

File: include/mbedtls/ssl.h (hunk 13 above)
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:4490]: Ah yes I did not think about that, That's better, thanks. I will change it.

File: include/mbedtls/ssl.h (hunk 14 above)
Comment (mpg) [reply include/mbedtls/ssl.h:4536]: Ah right, makes sense. Anyway, I'll care much less about the name as soon as it's a private function :)

**Comment by gilles-peskine-arm** [comment]
Manual testing: on the merge of https://github.com/Mbed-TLS/mbedtls/commit/ with https://github.com/Mbed-TLS/mbedtls/pull/9507/commits/48a9f562ba9a172961af05146039d33e4e14689a (from https://github.com/Mbed-TLS/mbedtls/pull/9505), `programs/ssl/tls*_demo.sh` pass.

File: include/mbedtls/ssl.h [hunk 16]
```diff
@@ -4465,11 +4465,10 @@ int mbedtls_ssl_conf_max_frag_len(mbedtls_ssl_config *conf, unsigned char mfl_co
...
 #endif /* MBEDTLS_SSL_SRV_C */
 
-#if defined(MBEDTLS_SSL_SESSION_TICKETS) && \
-    defined(MBEDTLS_SSL_CLI_C)
+#if defined(MBEDTLS_SSL_SESSION_TICKETS) && defined(MBEDTLS_SSL_CLI_C)
 /**
- * \brief          Enable / Disable session tickets (client only).
- *                 (Default: MBEDTLS_SSL_SESSION_TICKETS_ENABLED.)
+ * \brief          Enable / Disable TLS 1.2 session tickets (client and TLS 1.2 only).
+ *                 Disabled by default.
```
Comment (mpg) [inline include/mbedtls/ssl.h:4471]: Should be "Enabled".

**Review by mpg — CHANGES_REQUESTED** [review]
Looks good to me (as far as 3.6.1 is concerned) except for one documentation mistake.

File: include/mbedtls/ssl.h (hunk 16 above)
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:4471]: Indeed, thanks.

File: ChangeLog.d/disable-new-session-tickets.txt [hunk 17]
```diff
@@ -0,0 +1,13 @@
+Bugfix
+   * Fix TLS connection abortion in applications using an Mbed TLS client in
```
[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply ChangeLog.d/disable-new-session-tickets.txt:2]: Yes better thanks.

File: include/mbedtls/ssl.h [hunk 18]
```diff
@@ -5045,6 +5088,17 @@ int mbedtls_ssl_renegotiate(mbedtls_ssl_context *ssl);
...
  *                 new connection using the same source port. See below.
+ * \return         #MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET if a TLS 1.3
+ *                 NewSessionTicket message has been received.
+ *                 This error code can be returned only on client side if and
+ *                 only if handling of TLS 1.3 NewSessionTicket messages has
+ *                 been enabled through the
+ *                 mbedtls_ssl_conf_enable_new_session_tickets() API. A TLS 1.3
+ *                 NewSessionTicket message has been received and parsed
+ *                 successfully by the client. Ticket data is available in the
+ *                 SSL context and remain available as long as the client will
```
[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:5099]: "since there's no way to control when a message is received"
good point

File: include/mbedtls/ssl.h [hunk 19]
```diff
@@ -4478,8 +4477,46 @@ void mbedtls_ssl_conf_preference_order(mbedtls_ssl_config *conf, int order);
...
+ *        an Mbed TLS client with the default configuration establishes a
+ *        TLS 1.3 connection with a TLS 1.2 and TLS 1.3 capable server. If
+ *        following the handshake the TLS 1.3 server sends NewSessionTicket
+ *        messages and the Mbed TLS client processes them, this results in
+ *        Mbed TLS high level APIs (mbedtls_ssl_read(),
+ *        mbedtls_ssl_handshake(), ...) to eventually return an
+ *        #MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET non fatal error code
+ *        (see the documentation of mbedtls_ssl_read() for more information on
+ *        that error code). Applications unaware of that TLS 1.3 specific non
+ *        fatal error code are then failing.
```
[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply include/mbedtls/ssl.h:4508]: moved to `mbedtls_ssl_config_defaults()` where we disable the handling of NewSessionTicket messages.

File: library/ssl_misc.h [hunk 20]
```diff
@@ -2934,8 +2934,37 @@ static inline void mbedtls_ssl_tls13_session_clear_ticket_flags(
...
+#if defined(MBEDTLS_SSL_SESSION_TICKETS) && defined(MBEDTLS_SSL_CLI_C)
+#define MBEDTLS_SSL_SESSION_TICKETS_TLS1_2_BIT 0
+#define MBEDTLS_SSL_SESSION_TICKETS_TLS1_3_BIT 1
+
+#define MBEDTLS_SSL_SESSION_TICKETS_TLS1_2_MASK \
+    (1 << MBEDTLS_SSL_SESSION_TICKETS_TLS1_2_BIT)
+#define MBEDTLS_SSL_SESSION_TICKETS_TLS1_3_MASK \
+    (1 << MBEDTLS_SSL_SESSION_TICKETS_TLS1_3_BIT)
+
+static inline int mbedtls_ssl_conf_get_session_tickets(
```
[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply library/ssl_misc.h:2949]: CI is happy, not changed.

**Comment by ronald-cron-arm** [comment]
@gilles-peskine-arm @davidhorstmann-arm I've just pushed three new commits addressing Gilles and Manuel comments. Please have a look.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM as an incremental review on Manuel's. All feedback seems to be addressed

File: ChangeLog.d/disable-new-session-tickets.txt [hunk 21]
```diff
@@ -0,0 +1,14 @@
+Bugfix
+   * Fix TLS connection failure in applications using an Mbed TLS client in
+     the default configuration connecting to a TLS 1.3 server sending tickets.
+     See the documentation of
+     mbedtls_ssl_conf_tls13_enable_signal_new_session_tickets() for more
+     information.
+     Fixes #8749.
+
+Changes
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/disable-new-session-tickets.txt:9]: This entry should be under “Default behavior changes”.

I only noticed just now and I don't want to go through another round of rework here, so let's fix it during release prep at the changelog polishing step.
