### PR TITLE
[3.6] Reduce performance regression in RSA public operations

### LINKED ISSUE #9232: Performance regression in mbedtls_mpi_exp_mod() (v3.6.0)
We observed that the `mbedtls_mpi_exp_mod()` function takes much more time to complete in v3.6.0 than in v3.5.2 (about 16 times more). The platform is OP-TEE OS running in QEMU (arm32). See https://github.com/OP-TEE/optee_os/pull/6797 and in particular this commit which brings the function back to the v3.5.2 and solves the issue: https://github.com/jforissier/optee_os/commit/f147fc17b69efc9f22d122466d7b6b9678a6ad61

Any idea what's wrong?

---
Edit (mpg): [status summary](https://github.com/Mbed-TLS/mbedtls/issues/9232#issuecomment-2324078780).

### PR DESCRIPTION
**Pull request by mpg**
## Description

Fix #9232 - partially, the low-hanging fruits (also those that don't make the code size go up by too much).

Status: work in progress.

TODO:
- [x] measure code size
- [x] measure perf on other platforms
- [x] currently the window size is based on the limbsize of E, should it use the actual bitsize instead when E is public?
- [x] decide on API
- [x] propagate to RSA functions

## PR checklist

- [x] **changelog** provided
- [ ] **development** TODO
- [ ] **3.6 backport** this is it
- [x] **2.28 backport** not required (we are fixing a regression in 3.6)
- [ ] **tests** partly provided, will be continued in https://github.com/Mbed-TLS/mbedtls/pull/9493

### CODE REVIEW

**Comment by mpg** [comment]
Initial performance measurements on my laptop (64-bit Intel):

**3.6.0**
```
1024/1024-bit exp_mod, cold r: 0.961081 ms
1024/1024-bit exp_mod,  hot r: 1.050500 ms
  17/1024-bit exp_mod, cold r: 0.100309 ms
  17/1024-bit exp_mod,  hot r: 0.177438 ms
```

**This PR**
```
1024/1024-bit exp_mod, cold r: 1.070629 ms
1024/1024-bit exp_mod,  hot r: 1.062271 ms
  17/1024-bit exp_mod, cold r: 0.034083 ms
  17/1024-bit exp_mod,  hot r: 0.027739 ms
```

**3.5.1**
```
1024/1024-bit exp_mod, cold r: 1.071714 ms
1024/1024-bit exp_mod,  hot r: 1.083624 ms
  17/1024-bit exp_mod, cold r: 0.022744 ms
  17/1024-bit exp_mod,  hot r: 0.016366 ms
```

**Review by yanesca — COMMENTED** [review]
The approach looks good to me, this should eliminate all the overhead. One opinion about the API: maybe it would be worth to keep the `_optionally_safe()` function static and have an `_unsafe()` version in the header instead.

File: include/mbedtls/bignum.h [hunk 1]
```diff
@@ -880,7 +896,38 @@ int mbedtls_mpi_mod_int(mbedtls_mpi_uint *r, const mbedtls_mpi *A,
...
+ *                 previous call to mbedtls_mpi_exp_mod(), and reuse it.
+ *
+ * \return         \c 0 if successful.
+ * \return         #MBEDTLS_ERR_MPI_ALLOC_FAILED if a memory allocation failed.
+ * \return         #MBEDTLS_ERR_MPI_BAD_INPUT_DATA if \c N is negative or
+ *                 even, or if \c E is negative.
+ * \return         Another negative error code on different kinds of failures.
+ *
+ */
+int mbedtls_mpi_exp_mod_optionally_safe(mbedtls_mpi *X, const mbedtls_mpi *A,
```
Comment (gilles-peskine-arm) [inline include/mbedtls/bignum.h:925]: If we're going to have a single function for both cases, I would prefer a more specific naming convention than `optionally_safe`. I don't like the use of “safe”, which could refer to many different things. I'd prefer [leaky](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6.0/3rdparty/p256-m/p256-m/p256-m.c#L976) or “public”.

File: library/bignum_core.h [hunk 2]
```diff
@@ -604,6 +604,44 @@ int mbedtls_mpi_core_random(mbedtls_mpi_uint *X,
...
+ * \param[in,out] T  Temporary storage of at least the number of limbs returned
+ *                   by `mbedtls_mpi_core_exp_mod_working_limbs()`.
+ *                   Its initial content is unused and its final content is
+ *                   indeterminate.
+ *                   It must not alias or otherwise overlap any of the other
+ *                   parameters.
+ *                   It is up to the caller to zeroize \p T when it is no
+ *                   longer needed, and before freeing it if it was dynamically
+ *                   allocated.
+ * \param[in] E_public Set to MBEDTLS_MPI_IS_PUBLIC to gain some performance
```
Comment (gilles-peskine-arm) [inline library/bignum_core.h:633]: I don't like the complexity of having functions whose security properties depend on a runtime argument. Neither [P256-m](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6.0/3rdparty/p256-m/p256-m/p256-m.c#L976) nor [BearSSL](https://bearssl.org/gitweb/?p=BearSSL;a=tree;f=src/rsa;h=e9efb5cd1e6dbd9570098cd101c64aed16bbcc10;hb=8ef7680081c61b486622f2d983c0d3d21e83caad) do that. I would prefer to have separate code paths for leaky and non-leaky, converging only on functions that have a single implementation either way. The only argument I can think of to merge the two is code size. Is the gain really worth it?

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Ok (with a few minor remarks) if we really have to have mixed-leakiness functions, but do we really have to do that? I find it harder to follow the code and reason about the function, and that's with a single function, I fear it won't scale to more complex algorithms.

**Comment by mpg** [comment]
> Ok (with a few minor remarks) if we really have to have mixed-leakiness functions, but do we really have to do that?

No, I don't think we absolutely have to do that, and that's one of the main points about which I was hoping to get feedback. I just has to make a temporary choice for prototyping.

> One opinion about the API: maybe it would be worth to keep the `_optionally_safe()` function static and have an `_unsafe()` version in the header instead.

Yes, I think that would already be better.

> I don't like the complexity of having functions whose security properties depend on a runtime argument.

Agreed. Do you think it's acceptable for `static` functions though or would you rather avoid it entirely?

> The only argument I can think of to merge the two is code size. Is the gain really worth it?

That, and also there can be a maintenance cost if we end up duplicating source code. I can give it a try to do some size measurements and check how easy or awkward it is to avoid duplication.

**Comment by gilles-peskine-arm** [comment]
> > I don't like the complexity of having functions whose security properties depend on a runtime argument.
> 
> Agreed. Do you think it's acceptable for static functions though or would you rather avoid it entirely?

I'd prefer to avoid it, but for smaller functions with a limited scope, it's not so bad.

**Comment by jforissier** [comment]
With this PR (and the necessary changes to make use of the `E_public` parameter), the OP-TEE test case runs faster although still much slower than with v3.5.2. This is because the test doesn't only run RSA signature verification and decryption, it also includes RSA signing and encryption. Assuming OP-TEE switches to the more secure algorithm for secret stuff, we may need to disable this test in the CI and run it only during the release tests.
Here are the numbers (running `time xtest 4011` on the arm32 QEMU target):

- v3.5.2 (optee_os master @ b339ffbd9): 14.5s
- v3.6.0: 8m 26.6s
- This PR (my branch: [test-mbedtls-expmod-regression-fix-9281](https://github.com/jforissier/optee_os/tree/test-mbedtls-expmod-regression-fix-9281) @ 9dca1658f): 5m 58s

**Comment by mpg** [comment]
Just checking: @gilles-peskine-arm @yanesca will you be volunteering to review this once I've updated it, or should I look for another reviewer? (I'd appreciate if at least one of you could give at least a design review.)

**Comment by gilles-peskine-arm** [comment]
I intend to review if I'm around (I'll take about a week off around 15 August).

**Comment by yanesca** [comment]
I am happy to review it as well, but I will be taking some days off too (this Friday and next Wednesday).

File: include/mbedtls/bignum.h [hunk 3]
```diff
@@ -44,6 +44,22 @@
...
+ *
+ * Implementation should always check using
+ *  if (X_public == MBEDTLS_MPI_IS_PUBLIC) {
+ *      // unsafe path
+ *  } else {
+ *      // safe path
+ *  }
+ * not the other way round, in order to prevent misuse. (This is, if a value
+ * other than the two below is passed, default to the safe path.) */
+#define MBEDTLS_MPI_IS_PUBLIC  0x2a2a
```
[the remark this answers is not in the document]
Comment (yanesca) [reply include/mbedtls/bignum.h:60]: 0x2a2a is a 16 bit value and can be loaded with a `movw`. That supposed to be a single cycle, how can we improve on that?

File: include/mbedtls/bignum.h [hunk 4]
```diff
@@ -880,7 +896,38 @@ int mbedtls_mpi_mod_int(mbedtls_mpi_uint *r, const mbedtls_mpi *A,
...
+ * \param prec_RR  A helper MPI depending solely on \p N which can be used to
+ *                 speed-up multiple modular exponentiations for the same value
+ *                 of \p N. This may be \c NULL. If it is not \c NULL, it must
+ *                 point to an initialized MPI. If it hasn't been used after
+ *                 the call to mbedtls_mpi_init(), this function will compute
+ *                 the helper value and store it in \p prec_RR for reuse on
+ *                 subsequent calls to this function. Otherwise, the function
+ *                 will assume that \p prec_RR holds the helper value set by a
+ *                 previous call to mbedtls_mpi_exp_mod(), and reuse it.
+ *
```
[the remark this answers is not in the document]
Comment (yanesca) [reply include/mbedtls/bignum.h:917]: This won't be needed if we change the API and make `_optionally_safe` functions local.

File: library/bignum_core.h (hunk 2 above)
Comment (yanesca) [reply library/bignum_core.h:633]: I am not happy about it either, but I think now that we are turning on USE_PSA_CRYPTO by default, we will be pretty desperate for code size savings for a while. I think the gain can worth it and we should try.

**Comment by yanesca** [comment]
There is still work needed, just pushing what I have so far to get an early CI overnight.

**Review by gilles-peskine-arm — APPROVED** [review]
As of a5fc8f342a980e2f75229fb42fb92a5d4b0b2c6a, I have one minor niggle, plus I still [don't like the name `optionally_safe`](https://github.com/Mbed-TLS/mbedtls/pull/9281#discussion_r1666674014), but no blocker.

I still [don't like the optionally-safe concept](https://github.com/Mbed-TLS/mbedtls/pull/9281#discussion_r1666676645), but I don't have a better idea to keep the code size down. Since it's not in the public API, we can look for a better way after 3.6.1.

Obviously this is incomplete, but I'm declaring a5fc8f342a980e2f75229fb42fb92a5d4b0b2c6a as approved for correctness, so another reviewer can take it from there if I'm not around.

**Comment by tom-cosgrove-arm** [comment]
> If we're going to have a single function for both cases, I would prefer a more specific naming convention than `optionally_safe`. I don't like the use of “safe”, which could refer to many different things. I'd prefer [leaky](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6.0/3rdparty/p256-m/p256-m/p256-m.c#L976) or “public”.

How about using `ct` instead of `safe`?

We could also put the emphasis in the other direction: `can_skip_ct`.

**Comment by mpg** [comment]
For the record, here's what I used for benchmarking:
```c
#include "mbedtls/bignum.h"
#include "bignum_core.h"
#include <stdio.h>
#include <time.h>

#define TIMEIT(TITLE, CODE)                                         \
do {                                                                \
    for (size_t i = 0; i < 1000; i++) {                             \
        CODE;                                                       \
    }                                                               \
    clock_t start = clock();                                        \
    for (size_t i = 0; i < 1000; i++) {                             \
        CODE;                                                       \
    }                                                               \
    clock_t end = clock();                                          \
    double duration = (double)(end - start) / CLOCKS_PER_SEC;       \
    printf("%s: %f ms\n", TITLE, duration);                         \
} while (0)


// hex(random.randrange(2 ** 1024))
const char *A = "49dd4a46f532d1e3c395875d0f43747367e1fe078ac571a541e17c1e1a505cbb9df94e8fbe4b6acee05134a3ccb8780cbf19abded6dee43af23c547046ab309090eccfd8d837ce33b7489421c9a93201b7598f32bf4d97de5302604d581e31e1d1f786f826d00678c62222d0ed97910a786a9ca2a24cd768ee4241e761d71494";
const char *D = "8e51ee5226332eea3e694e62919fe8a3e2c6be653cd63d5c87027848636293dfe42025ab64df0f75cacab381400e4b734b08b4cbb1c4a28f699ae81dab87838f501f090e72e5d546f8de82f273416c204fa66176c0b48aea5df5cb081b80b56e63e3bfa545157b259baeebcdbf50b7299953440a681f414ea4cfca9d8f2c0b91";
const char *E = "10001";
const char *N = "ff3f5df10b8db6aab53eb55c3c979ce9250287fb48ac031b650ecbe35a42b2f0d2edfdb2252023e0b5769574ba0d6e7a5dec6989b75c82bc0364a0f24c7e3acdd12720573b8bdbd879d65cf3d8fb7ae9324774bb910aac64dc9f233ff58472809ec260089ef66b304368e86b1d159ce330867c3c49758757305f3de52bf958a7";

int main(void) {
    mbedtls_mpi x, a, d, e, n, r;

    mbedtls_mpi_init(&x); mbedtls_mpi_init(&a); mbedtls_mpi_init(&e);
    mbedtls_mpi_init(&d); mbedtls_mpi_init(&n); mbedtls_mpi_init(&r);

    mbedtls_mpi_read_string(&a, 16, A);
    mbedtls_mpi_read_string(&d, 16, D);
    mbedtls_mpi_read_string(&e, 16, E);
    mbedtls_mpi_read_string(&n, 16, N);

    TIMEIT("1024/1024-bit exp_mod, cold r", mbedtls_mpi_free(&r); mbedtls_mpi_exp_mod(&x, &a, &d, &n, &r));
    TIMEIT("1024/1024-bit exp_mod,  hot r", mbedtls_mpi_exp_mod(&x, &a, &d, &n, &r));
    TIMEIT("  17/1024-bit exp_mod, cold r", mbedtls_mpi_free(&r); mbedtls_mpi_exp_mod_optionally_safe(&x, &a, &e, &n, &r, MBEDTLS_MPI_IS_PUBLIC));
    TIMEIT("  17/1024-bit exp_mod,  hot r", mbedtls_mpi_exp_mod_optionally_safe(&x, &a, &e, &n, &r, MBEDTLS_MPI_IS_PUBLIC));
}
```

**Comment by yanesca** [comment]
> How about using ct instead of safe?
>
> We could also put the emphasis in the other direction: can_skip_ct.

I chose the prefix following the existing `mbedtls_mpi_core_get_mont_r2_unsafe()` funtion. It didn't occur to me to tie it to the _ct prefix. Conceptually this seems neat and `leaky` is more precise, but if I think about it I probably like `_unsafe` better:
- In the context of `bignum_core` we don't always use `_ct` but even where we do will go away over time as being constant time will become default.
- I think it is more likely that people will consult the documentation and start to think if they read `optionally_unsafe` as opposed to `can_skip_ct` or `optionally_leaky`

What do you think?

**Comment by tom-cosgrove-arm** [comment]
> > How about using ct instead of safe?
> > We could also put the emphasis in the other direction: can_skip_ct.
> 
> I chose the prefix following the existing `mbedtls_mpi_core_get_mont_r2_unsafe()` funtion. It didn't occur to me to tie it to the _ct prefix. Conceptually this seems neat and `leaky` is more precise, but if I think about it I probably like `_unsafe` better:
> 
> * In the context of `bignum_core` we don't always use `_ct` but even where we do will go away over time as being constant time will become default.
> * I think it is more likely that people will consult the documentation and start to think if they read `optionally_unsafe` as opposed to `can_skip_ct` or `optionally_leaky`
> 
> What do you think?

Yes, generally I prefer `_unsafe`, since it screams "here be dragons! read the docs!" - and this is one place where I'd rather slow down someone's reading and comprehension for security. I gave the other suggestions to offer alternatives.

That said, I find the suffix `_optionally_unsafe` very weird. I wonder about something like `_may_be_unsafe` but that's up to you. I realise "optionally" more clearly captures that it's the caller who chooses, but again, maybe this is a place where we want to make people think twice when reading/using these functions.

**Comment by gilles-peskine-arm** [comment]
> I think it is more likely that people will consult the documentation and start to think if they read optionally_unsafe as opposed to can_skip_ct or optionally_leaky

I doubt that. In languages like Haskell and Rust, “unsafe” has an aura of “what you need to get work done” and I think people just use it without trying to understand what subtle rule they're violating. Like casts in C. At least “leaky” tells you what sort of rule you're violating. I can't parse “can skip ct” (well, I can because I know what it's supposed to mean, but my first impression is that it can skip something implicit, and also it is constant-time).

File: library/bignum_core.c [hunk 5]
```diff
@@ -746,7 +746,60 @@ static void exp_mod_precompute_window(const mbedtls_mpi_uint *A,
...
+ */
+static inline void exp_mod_calc_first_bit_optionally_safe(const mbedtls_mpi_uint *E,
+                                                          size_t E_limbs,
+                                                          int E_public,
+                                                          size_t *E_limb_index,
+                                                          size_t *E_bit_index)
+{
+    if (E_public == MBEDTLS_MPI_IS_PUBLIC) {
+        size_t E_bits = mbedtls_mpi_core_bitlen(E, E_limbs);
+        if (E_bits != 0) {
```
[the remark this answers is not in the document]
Comment (yanesca) [reply library/bignum_core.c:764]: Because if we do, we end up with `E_limb_index=0` and we get an underflow when we are doing `--E_limb_index` in the loop.

**Comment by yanesca** [comment]
I suggest we stick with the current naming for now. What Gilles said applies here as well:
> Since it's not in the public API, we can look for a better way after 3.6.1.

File: library/bignum_core.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (mpg) [reply library/bignum_core.c:764]: However if `E_bits == 0` it looks like this function isn't setting the output parameters at all (on the public path), but instead relies on them being already set to appropriate value by the caller - which is the case now, but still seems unclean.

File: library/bignum_core.c [hunk 6]
```diff
@@ -758,16 +829,25 @@ static void exp_mod_precompute_window(const mbedtls_mpi_uint *A,
...
+                                                     int E_public,
+                                                     const mbedtls_mpi_uint *RR,
+                                                     mbedtls_mpi_uint *T)
 {
-    const size_t wsize = exp_mod_get_window_size(E_limbs * biL);
+    /* We'll process the bits of E from most significant
+     * (limb_index=E_limbs-1, E_bit_index=biL-1) to least significant
+     * (limb_index=0, E_bit_index=0). */
+    size_t E_limb_index = E_limbs;
+    size_t E_bit_index = 0;
```
Comment (mpg) [inline library/bignum_core.c:846]: See my other comment: I think we should initialize these variables here, but really let the function call below do it (and the compiler give us a warning if it doesn't).

**Comment by mpg** [comment]
The CI doesn't look happy.

**Review by mpg — COMMENTED** [review]
Looks pretty good to me, except for:
- an issue with a static function.
- we don't seem to be doing the hooks-based testing on `mbedtls_mpi_exp_mod()` / `mbedtls_mpi_exp_mod_unsafe()` - is there a reason or was it an oversight?

Regarding testing with test hooks, I assume the reason is that we don't have valgrind/memsan testing of constant-time behaviour of `mbedtls_mpi_core_exp_mod()` in 3.6? I believe it landed in development in the meantime, so I assume the development version of this PR wouldn't have to do that and would just rely on valgrind/memsan testing for `mbedtls_mpi_core_exp_mod()`?

**Comment by mpg** [comment]
> The CI doesn't look happy.

There are (at least) two kind of issues:
1. In `component_test_mx32` at lot (326) of the generated test cases for `mbedtls_mpi_core_exp_mod()` are failing, all on the same assertion: `suites/test_suite_bignum_core.function:1277:0 == memcmp(X, A, N_limbs * sizeof(mbedtls_mpi_uint))` - so presumably no computed the correct result.
2. Several components are failing to build with `` multiple definition of `mbedtls_mpi_optionally_safe_codepath' ``. I guess we want to declare it `extern int` in the `.h` file and only define it once in the `.c` file.

**Comment by yanesca** [comment]
> The CI doesn't look happy.

Oh, sorry, I forgot to check back for the results.

**Review by mpg — COMMENTED** [review]
LGTM if the CI agrees, except for the additional testing we discussed (which could be left for a follow-up however).

**Comment by yanesca** [comment]
> which could be left for a follow-up however

You mean for after 3.6.1?

**Comment by tom-cosgrove-arm** [comment]
For code size, I took the difference between `mbedtls-3.6` @ 28cdd1190 and this PR rebased onto that commit (since that's what will happen when this is merged).

In the default config, building for AArch64, the code size increase is

| base:28cdd1190:mbedtls-3.6 | pr:9281:rebased:dd9609174 |      Delta | Filename |
|---------------:|-----------:|-----------:|:---------|
|   22858, 0 |   22982, 0 |     +124+0 | `bignum.o` |
|    9104, 0 |    9440, 0 |     +336+0 | `bignum_core.o` |
|            |            |     +460+0 | TOTAL |

(Full config gives the same change)

Building for TF-M gives no change, since that config uses `p256-m` and don't use `bignum*`.

Building for Thumb2 with minimum changes from default to get it to build (`+MBEDTLS_NO_PLATFORM_ENTROPY-MBEDTLS_FS_IO-MBEDTLS_HAVE_TIME-MBEDTLS_HAVE_TIME_DATE-MBEDTLS_NET_C-MBEDTLS_PSA_CRYPTO_STORAGE_C-MBEDTLS_PSA_ITS_FILE_C-MBEDTLS_TIMING_C`)

| base:28cdd1190:mbedtls-3.6 | pr:9281:rebased:dd9609174 |      Delta | Filename |
|---------------:|-----------:|-----------:|:---------|
|    8866, 0 |    8944, 0 |      +78+0 | `bignum.o` |
|    2578, 0 |    2730, 0 |     +152+0 | `bignum_core.o` |
|            |            |     +230+0 | TOTAL |

**Comment by mpg** [comment]
> You mean for after 3.6.1?

**Comment by mpg** [comment]
> You mean for after 3.6.1?

I mean if I have to choose between merging this PR without the extra tests or have it miss the code freeze deadline, I prefer to merge it without the extra tests. But if merging it with the extra tests is also on the table, that's of course my favourite option :)

**Comment by yanesca** [comment]
I raised a separate PR for the additional testing:
https://github.com/Mbed-TLS/mbedtls/pull/9493

File: library/bignum_core.c [hunk 7]
```diff
@@ -746,7 +746,93 @@ static void exp_mod_precompute_window(const mbedtls_mpi_uint *A,
     }
 }
 
+#if defined(MBEDTLS_TEST_HOOKS) && !defined(MBEDTLS_THREADING_C)
+// Set to a default that is neither MBEDTLS_MPI_IS_PUBLIC nor MBEDTLS_MPI_IS_SECRET
+int mbedtls_mpi_optionally_safe_codepath = MBEDTLS_MPI_IS_PUBLIC + MBEDTLS_MPI_IS_SECRET + 1;
```
Comment (tom-cosgrove-arm) [inline library/bignum_core.c:751]: I don't like this. A + B + 1 is not a good way to get a number that's neither A nor B - what if A = 0 and B = -1? I know that's not true here, but this expression has a dependency on the values of A and B (and we don't have a static assert that this value = neither of them).

How would you feel about a third value specified in the #defines, of something like MBEDTLS_IS_NETHER_FOR_TESTING (name is horrible, but you get the idea)?

File: include/mbedtls/bignum.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply include/mbedtls/bignum.h]: Just to confirm that for Thumb2 the comparisons are encoded as single instructions, e.g.

```
  16:   f1b1 3f2a       cmp.w   r1, #707406378  ; 0x2a2a2a2a
```

**Comment by tom-cosgrove-arm** [comment]
Performance measurements, in default config (desktop only, sorry)

aarch64:
|                          Test | base:mbedtls-3.6:28cdd1190 | pr:9281:rebased:dd9609174 | Relative |
|------------------------------:|---------------------------:|---------------------------:|---------:|
| 1024/1024-bit exp_mod, cold r |               0.449740 ms |               0.445420 ms |    1.01x |
| 1024/1024-bit exp_mod,  hot r |               0.444260 ms |               0.442480 ms |    1.00x |
|   17/1024-bit exp_mod, cold r |               0.044070 ms |               0.014440 ms |    3.05x |
|   17/1024-bit exp_mod,  hot r |               0.041390 ms |               0.011440 ms |    3.62x |

x86_64:
|                          Test | base:mbedtls-3.6:28cdd1190 | pr:9281:rebased:23675570a | Relative |
|------------------------------:|---------------------------:|---------------------------:|---------:|
| 1024/1024-bit exp_mod, cold r |               0.672410 ms |               0.653440 ms |    1.03x |
| 1024/1024-bit exp_mod,  hot r |               0.670990 ms |               0.649560 ms |    1.03x |
|   17/1024-bit exp_mod, cold r |               0.066270 ms |               0.020480 ms |    3.24x |
|   17/1024-bit exp_mod,  hot r |               0.062450 ms |               0.016760 ms |    3.73x |

**Comment by mpg** [comment]
> I raised a separate PR for the additional testing:
> #9493

It looks like you also pushed the additional tests here, which I guess wasn't intended since you created a separate PR for them, but is absolutely fine by me. Now that they're here, let's review them and hopefully get the whole thing merged - which as I was saying was my favourite outcome anyway :)

**Review by mpg — COMMENTED** [review]
LGTM - though I can't formally approve, having created the PR. @yanesca can you "review" and mark as approved for me so that it shows as 1 approval on github?

**Review by yanesca — APPROVED** [review]
I have reviewed @mpg's commits and he has reviewed mine, this approval is for our combined review.

File: library/bignum_core.h [hunk 8]
```diff
@@ -110,6 +110,10 @@
  * other than the two below is passed, default to the safe path.) */
 #define MBEDTLS_MPI_IS_PUBLIC  0x2a2a2a2a
 #define MBEDTLS_MPI_IS_SECRET  0
+#if defined(MBEDTLS_TEST_HOOKS) && !defined(MBEDTLS_THREADING_C)
+// Default value for testing that is neither MBEDTLS_MPI_IS_PUBLIC nor MBEDTLS_MPI_IS_SECRET
+#define MBEDTLS_MPI_IS_TEST  1
```
Comment (tom-cosgrove-arm) [inline library/bignum_core.h:115]: Thanks - this is better, having all the values specified in the same place

**Comment by tom-cosgrove-arm** [comment]
At least one of the test failures is relevant, e.g. tls-testing / all_u16-build_arm_linux_gnueabi_gcc_arm5vte

```
[2024-08-22T07:44:40.471Z]   CC    test_suite_rsa.c
[2024-08-22T07:44:40.729Z] suites/test_suite_rsa.function: In function 'test_mbedtls_rsa_public':
[2024-08-22T07:44:40.729Z] suites/test_suite_rsa.function:493:5: error: implicit declaration of function 'mbedtls_mpi_optionally_safe_codepath_reset' [-Werror=implicit-function-declaration]
[2024-08-22T07:44:40.729Z]      mbedtls_mpi_optionally_safe_codepath_reset();
[2024-08-22T07:44:40.729Z]      ^
[2024-08-22T07:44:40.729Z] In file included from suites/helpers.function:7:0:
[2024-08-22T07:44:40.729Z] suites/test_suite_rsa.function:497:16: error: 'mbedtls_mpi_optionally_safe_codepath' undeclared (first use in this function)
[2024-08-22T07:44:40.729Z]      TEST_EQUAL(mbedtls_mpi_optionally_safe_codepath, MBEDTLS_MPI_IS_PUBLIC);
[2024-08-22T07:44:40.729Z]                 ^
[2024-08-22T07:44:40.729Z] ./include/test/macros.h:74:56: note: in definition of macro 'TEST_EQUAL'
[2024-08-22T07:44:40.729Z]                                   (unsigned long long) (expr1), (unsigned long long) (expr2)))                      \
[2024-08-22T07:44:40.729Z]                                                         ^
[2024-08-22T07:44:40.729Z] suites/test_suite_rsa.function:497:16: note: each undeclared identifier is reported only once for each function it appears in
[2024-08-22T07:44:40.729Z]      TEST_EQUAL(mbedtls_mpi_optionally_safe_codepath, MBEDTLS_MPI_IS_PUBLIC);
[2024-08-22T07:44:40.729Z]                 ^
[2024-08-22T07:44:40.729Z] ./include/test/macros.h:74:56: note: in definition of macro 'TEST_EQUAL'
[2024-08-22T07:44:40.729Z]                                   (unsigned long long) (expr1), (unsigned long long) (expr2)))                      \
[2024-08-22T07:44:40.729Z]                                                         ^
[2024-08-22T07:44:40.729Z] suites/test_suite_rsa.function:497:54: error: 'MBEDTLS_MPI_IS_PUBLIC' undeclared (first use in this function)
[2024-08-22T07:44:40.729Z]      TEST_EQUAL(mbedtls_mpi_optionally_safe_codepath, MBEDTLS_MPI_IS_PUBLIC);
[2024-08-22T07:44:40.729Z]                                                       ^
[2024-08-22T07:44:40.729Z] ./include/test/macros.h:74:86: note: in definition of macro 'TEST_EQUAL'
[2024-08-22T07:44:40.729Z]                                   (unsigned long long) (expr1), (unsigned long long) (expr2)))                      \
[2024-08-22T07:44:40.729Z]                                                                                       ^
[2024-08-22T07:44:40.729Z] suites/test_suite_rsa.function: In function 'test_mbedtls_rsa_private':
[2024-08-22T07:44:40.729Z] suites/test_suite_rsa.function:570:20: error: 'mbedtls_mpi_optionally_safe_codepath' undeclared (first use in this function)
[2024-08-22T07:44:40.729Z]          TEST_EQUAL(mbedtls_mpi_optionally_safe_codepath, MBEDTLS_MPI_IS_SECRET);
[2024-08-22T07:44:40.729Z]                     ^
[2024-08-22T07:44:40.729Z] ./include/test/macros.h:74:56: note: in definition of macro 'TEST_EQUAL'
[2024-08-22T07:44:40.729Z]                                   (unsigned long long) (expr1), (unsigned long long) (expr2)))                      \
[2024-08-22T07:44:40.729Z]                                                         ^
[2024-08-22T07:44:40.729Z] suites/test_suite_rsa.function:570:58: error: 'MBEDTLS_MPI_IS_SECRET' undeclared (first use in this function)
[2024-08-22T07:44:40.729Z]          TEST_EQUAL(mbedtls_mpi_optionally_safe_codepath, MBEDTLS_MPI_IS_SECRET);
[2024-08-22T07:44:40.729Z]                                                           ^
[2024-08-22T07:44:40.729Z] ./include/test/macros.h:74:86: note: in definition of macro 'TEST_EQUAL'
[2024-08-22T07:44:40.729Z]                                   (unsigned long long) (expr1), (unsigned long long) (expr2)))                      \
[2024-08-22T07:44:40.729Z]                                                                                       ^
[2024-08-22T07:44:40.729Z] cc1: all warnings being treated as errors

```

**Comment by tom-cosgrove-arm** [comment]
Thanks - this is looking good to me, but I have two remaining comments:

1. I think we need a ChangeLog entry - this is very definitely user-visible, even if it's an NFR;

2. While there's already a big comment around the definition of `MBEDTLS_MPI_IS_PUBLIC`, I think we should say why we have such a "weird" value. I know that is documented above in this PR, but that is really something that should be in the code "Use a value that is unlikely to happen by accident, but which can be used as an immediate value in a Thumb2 comparison (for code size)"

File: include/mbedtls/bignum.h [hunk 9]
```diff
@@ -880,7 +880,40 @@ int mbedtls_mpi_mod_int(mbedtls_mpi_uint *r, const mbedtls_mpi *A,
...
+ * \return         \c 0 if successful.
+ * \return         #MBEDTLS_ERR_MPI_ALLOC_FAILED if a memory allocation failed.
+ * \return         #MBEDTLS_ERR_MPI_BAD_INPUT_DATA if \c N is negative or
+ *                 even, or if \c E is negative.
+ * \return         Another negative error code on different kinds of failures.
+ *
+ */
+int mbedtls_mpi_exp_mod_unsafe(mbedtls_mpi *X, const mbedtls_mpi *A,
```
Comment (gilles-peskine-arm) [inline include/mbedtls/bignum.h:911]: I'm sorry but I realized I made a mistake in a [previous approval](https://github.com/Mbed-TLS/mbedtls/pull/9281#pullrequestreview-2236094854):

> Since it's not in the public API, we can look for a better way after 3.6.1.

But as of 878af1280729c60c4fb965005fae929963b0c20d we _are_ adding `mbedtls_mpi_exp_mod_unsafe` to the public API of the 3.6 LTS branch. I'm [ok with the prototype](https://github.com/Mbed-TLS/mbedtls/pull/9281#discussion_r1666676645) but I [don't like the name](https://github.com/Mbed-TLS/mbedtls/pull/9281#issuecomment-2291335763). Also I don't like to rush when extending the API of an LTS branch.

Can we make this an internal function instead? It's only meant to be used in `rsa.c` after all.

File: library/bignum_core.h [hunk 10]
```diff
@@ -817,4 +821,16 @@ void mbedtls_mpi_core_from_mont_rep(mbedtls_mpi_uint *X,
                                     mbedtls_mpi_uint mm,
                                     mbedtls_mpi_uint *T);
 
+/*
+ * Can't define thread local variables with our abstraction layer: do nothing if threading is on.
+ */
+#if defined(MBEDTLS_TEST_HOOKS) && !defined(MBEDTLS_THREADING_C)
+extern int mbedtls_mpi_optionally_safe_codepath;
```
Comment (gilles-peskine-arm) [inline library/bignum_core.h:828]: `mbedtls_mpi_optionally_safe_codepath` gives me hives. It's not at all obvious that turning on `MBEDTLS_TEST_HOOKS` doesn't change the functional behavior of the code: I had to carefully check the places where `mbedtls_mpi_optionally_safe_codepath` is used and verify that when the library reads it, it only influences how the library might modify it and nothing else.

`mbedtls_mpi_optionally_safe_codepath` should be documented at the place where it's declared. But the documentation belongs in the test code... The solution to this conundrum is that the variable should be defined in test code. The library code should call a tracing function through a function pointer (doing nothing if the function pointer is null).

This would normally be a blocker. I'm prepared to waive it under time pressure for the 3.6.1 release if we schedule a high-priority follow-up with the assurance that it will not get forgotten on the big tech debt heap.

File: library/bignum_core.c [hunk 11]
```diff
@@ -824,8 +856,8 @@ static void mbedtls_mpi_core_exp_mod_optionally_safe(mbedtls_mpi_uint *X,
     /* We'll process the bits of E from most significant
      * (limb_index=E_limbs-1, E_bit_index=biL-1) to least significant
      * (limb_index=0, E_bit_index=0). */
-    size_t E_limb_index = E_limbs;
-    size_t E_bit_index = 0;
+    size_t E_limb_index;
+    size_t E_bit_index;
```
Comment (gilles-peskine-arm) [inline library/bignum_core.c:860]: Non-blocker: I don't like relying on auxiliary functions to initialize variables. Unfortunately compilers aren't good at analyzing whether variables are analyzed on all code paths, and we don't run Coverity assiduously enough to notice all problems. I would strongly prefer to initialize to the safe-path values here, and have `exp_mod_calc_first_bit_optionally_safe` modify the values on the unsafe path.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
I've reviewed the library changes, not the test changes. I have one blocker because it's a change in an LTS and one thing that would be a blocker if we weren't rushing for release. Plus I agree with Tom that this should have a changelog entry.

**Comment by tom-cosgrove-arm** [comment]
The Windows CI failures are test failures:

```
[2024-08-22T09:08:34.230Z]          Base test mbedtls_mpi_exp_mod #1 .................................. PASS
[2024-08-22T09:08:34.230Z]          Base test mbedtls_mpi_exp_mod #2 (Even N) ......................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Base test mbedtls_mpi_exp_mod #2 (N = 0 (null)) ................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Base test mbedtls_mpi_exp_mod #3 (Negative N) ..................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Base test mbedtls_mpi_exp_mod #4 (Negative base) .................. PASS
[2024-08-22T09:08:34.230Z]          Base test mbedtls_mpi_exp_mod #5 (Negative exponent) .............. FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Base test mbedtls_mpi_exp_mod #6 (Negative base + exponent) ....... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 0 (null) ^ 0 (null) mod 9 ............... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 0 (null) ^ 0 (1 limb) mod 9 ............. PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 0 (null) ^ 1 mod 9 ...................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 0 (null) ^ 2 mod 9 ...................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 0 (1 limb) ^ 0 (null) mod 9 ............. FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 0 (1 limb) ^ 0 (1 limb) mod 9 ........... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 0 (1 limb) ^ 1 mod 9 .................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 0 (1 limb) ^ 2 mod 9 .................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 1 ^ 0 (null) mod 9 ...................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 4 ^ 0 (null) mod 9 ...................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 10 ^ 0 (null) mod 9 ..................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1033, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 1 ^ 0 (1 limb) mod 9 .................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 4 ^ 0 (1 limb) mod 9 .................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: 10 ^ 0 (1 limb) mod 9 ................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: -3 ^ 3 mod 27 ........................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: MAX_SIZE exponent ....................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1128, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x000000002a2a2a2a = 707406378
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: MAX_SIZE + 1 exponent ................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1120, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: MAX_SIZE modulus ........................ FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1128, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x000000002a2a2a2a = 707406378
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: MAX_SIZE + 1 modulus .................... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1120, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: MAX_SIZE exponent and modulus ........... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1128, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x000000002a2a2a2a = 707406378
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod: MAX_SIZE + 1 exponent and modulus ....... FAILED
[2024-08-22T09:08:34.230Z]            mbedtls_mpi_optionally_safe_codepath == MBEDTLS_MPI_IS_SECRET
[2024-08-22T09:08:34.230Z]            at line 1120, C:/Windows/workspace/mbed-tls-pr-head_PR-9281-head/worktrees/tmpiq_0xjib/tests/suites/test_suite_bignum.function
[2024-08-22T09:08:34.230Z]            lhs = 0x0000000000000001 = 1
[2024-08-22T09:08:34.230Z]            rhs = 0x0000000000000000 = 0
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod #1 ....................................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod (Negative base) [#1] ..................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod (Negative base) [#2] ..................... PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod (N.n=3, RR.n=1 on 32 bit) ................ PASS
[2024-08-22T09:08:34.230Z]          Test mbedtls_mpi_exp_mod (N.n=3, RR.n=1 on 64 bit) ................ ----
[2024-08-22T09:08:34.230Z]             Unmet dependencies: 0 
```

File: include/mbedtls/bignum.h (hunk 9 above)
Comment (mpg) [reply include/mbedtls/bignum.h:911]: If you don't like the name we need to have a larger discussion because we already have a few functions called `_unsafe` (as Janos pointed out already), so if we make a change it should apply to all functions.

But I fully agree about making the new function internal, especially considering it's an LTS and we don't have time to have the naming discussion.

File: library/bignum_core.h (hunk 10 above)
Comment (mpg) [reply library/bignum_core.h:828]: We could declare that the 3.6.1 EPIC can't be closed until that follow-up is done, so that we have to do the follow-up before the end of the quarter.

File: include/mbedtls/bignum.h (hunk 9 above)
Comment (gilles-peskine-arm) [reply include/mbedtls/bignum.h:911]: > we already have a few functions called _unsafe

Not in the public API. I don't care nearly as much about internal functions.

```
$ git show -s --oneline
28cdd11908 (HEAD, upstream-restricted/test-mbedtls-3.6.1rc, upstream-public/mbedtls-3.6) Merge pull request #9479 from gilles-peskine-arm/psa-keystore-static-release-update-3.6
$ git grep _unsafe include
```

We do have one internal function called `xxx_unsafe` (`mbedtls_mpi_core_get_mont_r2_unsafe`) and while I'm ok (but not enthusiastic) about the name, I'm bothered that its documentation doesn't explain in what way it's unsafe.

Comment (mpg) [reply include/mbedtls/bignum.h:911]: Indeed, the other function is not public, so that's an additional reason to keep the new one private.

(I also agree that naming is less important for internal functions, but we can still have a discussion about it some time. I can see arguments for calling them `_leaky` rather than `_unsafe` as it's more informative. Also, for the small `static` functions that are currently called `optionally_safe`, I think `slow_or_leaky` would make anyone think before using them. But let's have this discussion another time.)

**Comment by mpg** [comment]
Here are measurements I did on 32-bit Arm (Cortex-A7, Pi 2):

|                               | 3.5.1    | 3.6.0    |         | 9281     |        |
| ----------------------------- | -------- | -------- | ------- | -------- | ------ |
| 1024/1024-bit exp_mod, cold r | 26.73 ms | 25.84 ms | x  0.96 | 25.47 ms | x 0.95 |
| 1024/1024-bit exp_mod,  hot r | 26.52 ms | 25.40 ms | x  0.96 | 25.25 ms | x 0.95 |
|   17/1024-bit exp_mod, cold r |  0.62 ms |  1.43 ms | x  2.31 |  0.87 ms | x 1.56 |
|   17/1024-bit exp_mod,  hot r |  0.42 ms |  1.22 ms | x  2.90 |  0.66 ms | x 1.57 |
| '17'/1024-bit exp_mod, cold r |  0.64 ms | 25.61 ms | x 40    |  0.87 ms | x 1.56 |
| '17'/1024-bit exp_mod,  hot r |  0.43 ms | 25.40 ms | x 60    |  0.66 ms | x 1.57 |

Using a slightly modified version of [the program above](https://github.com/Mbed-TLS/mbedtls/pull/9281#issuecomment-2288316341) where the `'17'/1024` lines are the same as the above except with `mbedtls_mpi_grow(&e, d.private_n)` inserted in-between.

All ratios in the above table are with 3.5.1 as the reference value. So, basically public operations after this PR would be about 50-60% slower than they were in 3.5.1, which I think is quite acceptable - in any case a vast improvement over the situation in 3.6.0.

**Comment by yanesca** [comment]
Reverting to 878af12807 as discussed offline.

File: ChangeLog.d/fix-rsa-performance-regression.txt [hunk 12]
```diff
@@ -0,0 +1,2 @@
+Bugfix
+   * Fix performance regression when using short RSA public keys.
```
Comment (tom-cosgrove-arm) [inline ChangeLog.d/fix-rsa-performance-regression.txt:2]: Minor nits: (1) we don't totally fix the performance regression, but we reduce the impact on public-key operations of the constant-time changes in 3.6; (2) I'm pretty sure there was an issue raised for this, so should we mention the issue number?

Comment (yanesca) [reply ChangeLog.d/fix-rsa-performance-regression.txt]: (1) The rest of the performance regression is the price of better security. The phrasing you suggest would imply that we treat that as a regression and it will be fixed, which is not the case.
(2) I was thinking about it, but I didn't add as I didn't want to auto-close the issue. But I guess we can always reopen it.

**Comment by yanesca** [comment]
Reverted to https://github.com/Mbed-TLS/mbedtls/commit/878af1280729c60c4fb965005fae929963b0c20d.

File: library/bignum_core.h (hunk 10 above)
Comment (yanesca) [reply library/bignum_core.h:824]: Reopened the followup to address this: https://github.com/Mbed-TLS/mbedtls/pull/9493

File: library/rsa.c [hunk 13]
```diff
@@ -1228,6 +1228,16 @@ int mbedtls_rsa_check_pub_priv(const mbedtls_rsa_context *pub,
     return 0;
 }
 
+/*
+ * This function is identical to mbedtls_mpi_exp_mod() the only difference is that this function is
+ * not constant time.
+ *
+ * WARNING! This function is not constant time.
+ */
+int mbedtls_mpi_exp_mod_unsafe(mbedtls_mpi *X, const mbedtls_mpi *A,
```
Comment (tom-cosgrove-arm) [inline library/rsa.c:1237]: Shouldn't this have `extern` on it?

Comment (yanesca) [reply library/rsa.c:1237]: I thought that all function declarations are implicitly `extern`

Comment (tom-cosgrove-arm) [reply library/rsa.c:1237]: Hmm, yes, and we seem to use that in Mbed TLS, so I'll withdraw this comment (although it looks strange to me without `extern` since we're in a `.c` file)

File: library/bignum.c [hunk 14]
```diff
@@ -1720,6 +1728,20 @@ int mbedtls_mpi_exp_mod(mbedtls_mpi *X, const mbedtls_mpi *A,
...
 }
 
+int mbedtls_mpi_exp_mod(mbedtls_mpi *X, const mbedtls_mpi *A,
+                        const mbedtls_mpi *E, const mbedtls_mpi *N,
+                        mbedtls_mpi *prec_RR)
+{
+    return mbedtls_mpi_exp_mod_optionally_safe(X, A, E, MBEDTLS_MPI_IS_SECRET, N, prec_RR);
+}
+
+int mbedtls_mpi_exp_mod_unsafe(mbedtls_mpi *X, const mbedtls_mpi *A,
```
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply library/bignum.c:1738]: ... and this is causing FreeBSD CI builds to fail

```
[2024-08-22T12:59:17.807Z] /usr/home/ec2-user/workspace/mbed-tls-pr-head_PR-9281-head/src/library/bignum.c:1738:5: error: no previous prototype for function 'mbedtls_mpi_exp_mod_unsafe' [-Werror,-Wmissing-prototypes]
[2024-08-22T12:59:17.807Z] int mbedtls_mpi_exp_mod_unsafe(mbedtls_mpi *X, const mbedtls_mpi *A,
[2024-08-22T12:59:17.807Z]     ^
[2024-08-22T12:59:17.807Z] /usr/home/ec2-user/workspace/mbed-tls-pr-head_PR-9281-head/src/library/bignum.c:1738:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
[2024-08-22T12:59:17.807Z] int mbedtls_mpi_exp_mod_unsafe(mbedtls_mpi *X, const mbedtls_mpi *A,
[2024-08-22T12:59:17.807Z] ^
[2024-08-22T12:59:17.807Z] static 
[2024-08-22T12:59:17.807Z] [  8%] Building C object library/CMakeFiles/mbedcrypto.dir/bignum_core.c.o
[2024-08-22T12:59:17.807Z] 1 error generated.
[2024-08-22T12:59:17.807Z] make[2]: *** [library/CMakeFiles/mbedcrypto.dir/build.make:268: library/CMakeFiles/mbedcrypto.dir/bignum.c.o] Error 1
[2024-08-22T12:59:17.807Z] make[2]: *** Waiting for unfinished jobs....
[2024-08-22T12:59:18.064Z] make[1]: *** [CMakeFiles/Makefile2:1053: library/CMakeFiles/mbedcrypto.dir/all] Error 2
[2024-08-22T12:59:18.064Z] make: *** [Makefile:146: all] Error 2
[2024-08-22T12:59:18.064Z] ^^^^test_cmake_out_of_source: build: cmake 'out-of-source' build: make -> 2^^^^
```

File: ChangeLog.d/fix-rsa-performance-regression.txt [hunk 15]
```diff
@@ -0,0 +1,2 @@
+Bugfix
+   * Fix unintended performance regression when using short RSA public keys. See #9232.
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/fix-rsa-performance-regression.txt:2]:
```suggestion
   * Fix unintended performance regression when using short RSA public keys. Fixes #9232.
```

A follow-up that improves testing is not relevant for users. The text in the changelog entry won't auto-close the issue, that only happens from the pull request description and commit comments.

File: library/bignum.c (hunk 14 above)
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply library/bignum.c:1738]: Yes, we have `-Wmissing-prototypes` in some builds since very recently.

We have a precedent of creating a header in `library` in an LTS branch: `bignum_internal` was added 2.28.7. So please (re)create `library/bignum_internal.h` for `mbedtls_mpi_exp_mod_unsafe()`.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
I approve the library changes for the release freeze today, after fixing the CI (plus the changelog entry while you're at it). I haven't reviewed the tests, but I'm satisfied that they're non-harmful.

This is conditional on doing the following as soon as possible, in any case before the end of the quarter:

* Have the tests reviewed and approved (by me or someone else).
* [Improving the test hooks](https://github.com/Mbed-TLS/mbedtls/pull/9281#discussion_r1726676094)
* [Make initialization robust](https://github.com/Mbed-TLS/mbedtls/pull/9281#discussion_r1726686537)

**Review by gilles-peskine-arm — DISMISSED** [review]
I approve the library changes at 5f316972b2d0ee6ede71102a666df55b5f46e1e8 for the release freeze today. I haven't reviewed the tests, but I'm satisfied that they're non-harmful.

This is conditional on doing the following as soon as possible, in any case before the end of the quarter:

* Have the tests reviewed and approved (by me or someone else).
* [Improving the test hooks](https://github.com/Mbed-TLS/mbedtls/pull/9281#discussion_r1726676094)
* [Make initialization robust](https://github.com/Mbed-TLS/mbedtls/pull/9281#discussion_r1726686537)

File: ChangeLog.d/fix-rsa-performance-regression.txt [hunk 16]
```diff
@@ -0,0 +1,2 @@
+Bugfix
+   * Fix unintended performance regression when using short RSA public keys. Fixes #9232.
```
Comment (tom-cosgrove-arm) [inline ChangeLog.d/fix-rsa-performance-regression.txt:2]: Is this line going to be too long?

File: library/bignum_internal.h [hunk 17]
```diff
@@ -0,0 +1,50 @@
...
+ * \return         #MBEDTLS_ERR_MPI_BAD_INPUT_DATA if \c N is negative or
+ *                 even, or if \c E is negative.
+ * \return         Another negative error code on different kinds of failures.
+ *
+ */
+int mbedtls_mpi_exp_mod_unsafe(mbedtls_mpi *X, const mbedtls_mpi *A,
+                               const mbedtls_mpi *E, const mbedtls_mpi *N,
+                               mbedtls_mpi *prec_RR);
+
+#endif /* bignum_internal.h */
```
Comment (tom-cosgrove-arm) [inline library/bignum_internal.h:50]: (non-blocker) the comment normally includes the pre-processor macro name, not the file name

File: ChangeLog.d/fix-rsa-performance-regression.txt (hunk 16 above)
Comment (yanesca) [reply ChangeLog.d/fix-rsa-performance-regression.txt:2]: It is within the 100 column limit. Do we have a stricter limitation on Changelog entries?

File: library/bignum_internal.h (hunk 17 above)
Comment (yanesca) [reply library/bignum_internal.h:50]: It was copied from `rsa_internal.h`.

File: ChangeLog.d/fix-rsa-performance-regression.txt (hunk 16 above)
Comment (tom-cosgrove-arm) [reply ChangeLog.d/fix-rsa-performance-regression.txt:2]:
```
$ scripts/assemble_changelog.py
Traceback (most recent call last):
  File "/media/psf/Home/home/tom/projects/mbedtls/quick/scripts/assemble_changelog.py", line 534, in <module>
    main()
  File "/media/psf/Home/home/tom/projects/mbedtls/quick/scripts/assemble_changelog.py", line 531, in main
    merge_entries(options)
  File "/media/psf/Home/home/tom/projects/mbedtls/quick/scripts/assemble_changelog.py", line 477, in merge_entries
    changelog.add_file(input_file)
  File "/media/psf/Home/home/tom/projects/mbedtls/quick/scripts/assemble_changelog.py", line 257, in add_file
    self.add_categories_from_text(input_stream.name, 1,
  File "/media/psf/Home/home/tom/projects/mbedtls/quick/scripts/assemble_changelog.py", line 225, in add_categories_from_text
    raise InputFormatError(filename,
__main__.InputFormatError: ChangeLog.d/fix-rsa-performance-regression.txt:2: Line is longer than allowed: Length 89 (Max 80)
```

File: library/bignum_internal.h (hunk 17 above)
Comment (tom-cosgrove-arm) [reply library/bignum_internal.h:50]: "normally" and "non-blocker", but

```
$ for f in library/*.h ; do ; tail -1 $f ; done | fgrep .h | wc -l  
8
$ for f in library/*.h ; do ; tail -1 $f ; done | fgrep _H | wc -l
49
```

File: library/bignum_core.c (hunk 7 above)
Comment (tom-cosgrove-arm) [reply library/bignum_core.c:751]: I'm unresolving this as we've reverted past the commit that addressed this

Comment (yanesca) [reply library/bignum_core.c:751]: I've already added this commit to the [followup PR](https://github.com/Mbed-TLS/mbedtls/pull/9493)

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM with the reservations in https://github.com/Mbed-TLS/mbedtls/pull/9281#pullrequestreview-2254649856

**Comment by gilles-peskine-arm** [comment]
I've pressed the merge button so that we can get on with the release. We need a forward-port to `development`, but that doesn't go through the release process so it can wait a few days.
