### PR TITLE
driver-only ECDH: enable ECDH-based TLS 1.2 key exchanges -- part 1

### LINKED ISSUE #7253: driver-only ECDH: enable ECDH-based TLS 1.2 key exchanges
Following the activity on accelerated ECDH started from #7142 and #7148, enable ECDH based key exchanges and:

- pass all tests in reference and accelerated scenarios
- verify test parity using `analyze_outcome.py`
- verify potential regressions using `outcome-analysis.sh`

This issues mimic #6862 but for ECDH instead of ECDSA

## Note
For an easier review activity it is strongly suggested to progress in this order:
- enable ECDH first #7296 
- then move to ECDHE #7297

### PR DESCRIPTION
**Pull request by valeriosetti**
This PR addresses the first part of #7253 by re-enabling only ECDH key exchanges and granting test parity.

Resolves #7253 (only in part).

## Gatekeeper checklist

- [x] **changelog** not required - will be added at the end of the series
- [x] **backport** not required - new feature
- [x] **tests** provided

### CODE REVIEW

**Comment by valeriosetti** [comment]
Here is the result of `outcome-analysis.sh`
[outcome-analysis.txt](https://github.com/Mbed-TLS/mbedtls/files/10981935/outcome-analysis.txt)

File: tests/ssl-opt.sh [hunk 1]
```diff
@@ -9447,7 +9497,7 @@ run_test    "DTLS reassembly: no fragmentation (openssl server)" \
 
 requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
 run_test    "DTLS reassembly: some fragmentation (openssl server)" \
-            "$O_SRV -dtls -mtu 768" \
+            "$O_SRV -dtls -mtu 256" \
```
Comment (mpg) [inline tests/ssl-opt.sh:9500]: Seems unrelated. Is it an accident or am I missing something?

File: tests/ssl-opt.sh [hunk 2]
```diff
@@ -11362,8 +11412,8 @@ not_with_valgrind # risk of non-mbedtls peer timing out
 requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
 run_test    "DTLS proxy: 3d, openssl server" \
             -p "$P_PXY drop=5 delay=5 duplicate=5 protect_hvr=1" \
-            "$O_NEXT_SRV -dtls1_2 -mtu 2048" \
-            "$P_CLI dgram_packing=0 dtls=1 hs_timeout=500-60000 tickets=0" \
+            "$O_NEXT_SRV -dtls1_2 -mtu 2048 -debug -msg -state" \
+            "$P_CLI dgram_packing=0 dtls=1 hs_timeout=500-60000 tickets=0 debug_level=4" \
```
Comment (mpg) [inline tests/ssl-opt.sh:11416]: Looks like leftovers from debugging.

File: tests/ssl-opt.sh [hunk 3]
```diff
@@ -1102,6 +1126,28 @@ is_gnutls() {
     esac
 }
 
+# Some external tools (gnutls or openssl) might not have support for ECDH and
```
Comment (mpg) [inline tests/ssl-opt.sh:1129]: Minor: just to be sure it's clear that we're talking about ECDH as opposed to ECDHE, we should call it "static ECDH" to avoid the ambiguity.

**Review by mpg — CHANGES_REQUESTED** [review]
Looks good to me except what looks like two accidents, and a request for improving the wording of one comment.

File: tests/ssl-opt.sh (hunk 1 above)
Comment (valeriosetti) [reply tests/ssl-opt.sh:9500]: Nope, this is intentional. The test expects `"found fragmented DTLS handshake message"` on the client's output, but with 768 this does not happen. Checking at the proxy log output and also at test `"DTLS reassembly: fragmentation, nbio, renego (gnutls server)"` I thought about reducing that MTU size and that did the trick.

My suspect is that disabling ECDHE and having only ECDH cause the test to be executed (and that is fine, of course), but exchanged messages are somehow smaller in size so that they do not get split into smaller chunks. Howerver this is just my hypothesis, so if I'm doing something really wrong here I will revert that ;)

File: tests/ssl-opt.sh (hunk 2 above)
Comment (valeriosetti) [reply tests/ssl-opt.sh:11416]: Ops, yes, sorry for that :/

File: tests/ssl-opt.sh (hunk 1 above)
Comment (mpg) [reply tests/ssl-opt.sh:9500]: Ah, right, your hypothesis makes sense to me!

**Review by mpg — APPROVED** [review]
LGTM

**Comment by mprse** [comment]
This one needs to be rebased.

**Comment by valeriosetti** [comment]
> This one needs to be rebased.

Ops, I added a comment on this [here](https://github.com/Mbed-TLS/mbedtls/pull/7312#issuecomment-1475879376), but obviously this affects also preceding PRs

**Review by mprse — APPROVED** [review]
LGTM

**Review by mpg — APPROVED** [review]
