### PR TITLE
Run ssl-opt.sh in more reduced configurations

### LINKED ISSUE #5731: lsof on FreeBSD might emit warnings and fail component_test_cmake_out_of_source
In Mbed TLS 2.x, `component_test_cmake_out_of_source` in `tests/scripts/all.sh` runs a test case from `tests/ssl-opt.sh` and checks that there are no error messages. This has been broken for a while due to an incorrect dependency in `ssl-opt.sh`: the test case only runs if `requires_openssl_with_fallback_scsv`, which depends on the version of `openssl`. We never noticed until now, but the test case is skipped on our FreeBSD CI because its `openssl` is too recent — it's still running as expected on Linux because we run it with an older `openssl`.

https://github.com/Mbed-TLS/mbedtls/pull/5730 fixes the dependency of the test case, and so it now runs on FreeBSD as expected. But `all.sh test_cmake_out_of_source` then fails on Arm FreeBSD instances due to a warning message from `lsof`. Seen in https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-merge/detail/PR-5730-merge/3/pipeline/420:

```
Fallback SCSV: beginning of list ....................................... PASS
------------------------------------------------------------------------
PASSED (1 / 1 tests (0 skipped))
lsof: WARNING: compiled for FreeBSD release 12.2-RELEASE-p10; this is 12.2-RELEASE-p7.
lsof: WARNING: access /home/ec2-user/.lsof_freebsd: No such file or directory
lsof: WARNING: created device cache file: /home/ec2-user/.lsof_freebsd
^^^^test_cmake_out_of_source: test: cmake 'out-of-source' build: [ ! -s ssl-opt.err ] -> 1^^^^
```

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
This is an incremental improvement to the ability to run `tests/ssl-opt.sh` in reduced configurations. The main completeness goals is for it to pass on `config/config-ccm-psk-dtls1_2.h` and `config-suite-b.h`, and to be roughly aligned with the 2.28 backport. Beyond that, there are a few miscellaneous improvements in automatic requirement detection.

* Add some missing `requires_xxx` statements.
* Deduce a few more requirements automatically from the parameters passed to the client and the server.
* In PSK-only builds, run some tests. (I don't seek to improve builds with PSK + asymmetric key exchange, but I don't think I'm making anything worse.)
* New configuration `config-ccm-psk-dtls1_2.h`, based on `config-ccm-psk-dtls1_2.h` but with a few more DTLS options and a smaller SSL buffer, so more representative of IoT devices that don't do asymmetric crypto.
* Minor improvements and fixes to `test-ref-configs.pl`.
* Resolve #5731 (workaround for a problem with the test infrastructure).

Note on "Automatically detect protocol version requirement from force_version": I left a spurious `requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_3` on "TLS 1.3: CertificateRequest check - openssl" to avoid a merge conflict.

Backport: https://github.com/Mbed-TLS/mbedtls/pull/5730

### CODE REVIEW

File: tests/scripts/test-ref-configs.pl [hunk 1]
```diff
@@ -32,11 +32,19 @@
         'compat' => '-m tls12 -f \'^TLS-PSK-WITH-AES-...-CCM-8\'',
         'test_again_with_use_psa' => 1
     },
+    'config-ccm-psk-dtls1_2.h' => {
+        'compat' => '-m dtls12 -f \'^TLS-PSK-WITH-AES-...-CCM-8\'',
```
Comment (gilles-peskine-arm) [inline tests/scripts/test-ref-configs.pl:36]: This actually runs no `compat.sh` test cases. This is a preexisting bug (https://github.com/ARMmbed/mbedtls/issues/5629) and out of scope here.

**Comment by gilles-peskine-arm** [comment]
CI passed originally, but pr-merge is now failing in `test-ref-configs.pl`, specifically in `ssl-opt.sh: config-ccm-psk-dtls1_2.h+PSA+DEBUG`:
```
DTLS proxy: multiple records in same datagram .......................... RETRY(client-timeout) FAIL
  ! server or client failed to reach handshake stage
  ! outputs saved to o-XXX-581.log
DTLS proxy: multiple records in same datagram, duplicate every packet .. RETRY(client-timeout) FAIL
  ! server or client failed to reach handshake stage
  ! outputs saved to o-XXX-582.log
```
I'll investigate.

**Review by paul-elliott-arm — COMMENTED** [review]
First pass of review whilst you are investigating failures.

File: tests/ssl-opt.sh [hunk 2]
```diff
@@ -1150,6 +1146,12 @@ run_test() {
             requires_config_enabled MBEDTLS_FS_IO;;
     esac
 
+    # Check if the test uses DTLS.
+    detect_dtls "$SRV_CMD"
```
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply tests/ssl-opt.sh:1251]: I don't understand what your concern is. If we're looking at the same revision, line 845 is
```
    if [ -z "$PXY_CMD" ] && [ "$DTLS" -eq 1 ]; then
```
in the function `analyze_test_commands`. My patch moves the call to `detect_dtls` from the top of `analyze_test_commands` to this place in `run_test`. This is before `run_test` calls `analyze_test_commands`. So everything that used to run with `DTLS` already set still runs with `DTLS` already set, and in addition now `DTLS` is set for what `run_test` does between the call to `detect_dtls` here and the call to `analyze_test_commands` below.

File: tests/scripts/test-ref-configs.pl (hunk 1 above)
Comment (gilles-peskine-arm) [reply tests/scripts/test-ref-configs.pl:36]: https://jenkins-mbedtls.oss.arm.com/blue/rest/organizations/jenkins/pipelines/mbed-tls-pr-merge/branches/PR-5582-merge/runs/22/nodes/282/steps/1009/log/?start=0 (CI run with #5630 merged) shows that `compat.sh` runs some tests here:
```
m->G dtls12,no TLS-PSK-WITH-AES-128-CCM-8 .............................. PASS
m->G dtls12,no TLS-PSK-WITH-AES-256-CCM-8 .............................. PASS
m->m dtls12,no TLS-PSK-WITH-AES-128-CCM-8 .............................. PASS
m->m dtls12,no TLS-PSK-WITH-AES-256-CCM-8 .............................. PASS
m->G dtls12,yes TLS-PSK-WITH-AES-128-CCM-8 ............................. PASS
m->G dtls12,yes TLS-PSK-WITH-AES-256-CCM-8 ............................. PASS
m->m dtls12,yes TLS-PSK-WITH-AES-128-CCM-8 ............................. PASS
m->m dtls12,yes TLS-PSK-WITH-AES-256-CCM-8 ............................. PASS
```
This looks as expected (we're testing against OpenSSL 1.0.2g and it doesn't support CCM cipher suites, hence no testing against OpenSSL).

File: tests/ssl-opt.sh [hunk 3]
```diff
@@ -1152,6 +1152,16 @@ run_test() {
         requires_config_enabled MBEDTLS_SSL_PROTO_DTLS
     fi
 
+    # Check more TLS protocol features.
+    case "$SRV_CMD $CLI_CMD" in
+        *[-_\ =]tickets=[^0]*)
```
Comment (mpg) [inline tests/ssl-opt.sh:1258]: This is probably correct, but out of curiosity: why allow `=`? Perhaps a comment with examples of things we're meaning to match would help. (I'm not even sure why we allow `-`: is it for the sake of OpenSSL/GnuTLS? But then they don't mandate the `=` sign between the option name and its value, do they?)

File: tests/ssl-opt.sh [hunk 4]
```diff
@@ -1460,6 +1460,7 @@ trap cleanup INT TERM HUP
 # - the expected parameters are selected
 #   ("signature_algorithm ext: 6" means SHA-512 (highest common hash))
 requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
+requires_ciphersuite_enabled TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256
```
Comment (mpg) [inline tests/ssl-opt.sh:1567]: Optional: I know this PR isn't supposed to do everything, but if I may suggest a low-hanging fruit: these tests also only make sense if SHA-512 and Curve25519 are enabled.

File: tests/ssl-opt.sh [hunk 5]
```diff
@@ -293,6 +293,69 @@ maybe_requires_ciphersuite_enabled() {
...
+# maybe_adapt_for_psk [RUN_TEST_OPTION...]
+# If running in a PSK-only build, maybe adapt the test to use a pre-shared key.
+#
+# If not running in a PSK-only build, do nothing.
+# If the test looks like it doesn't use a pre-shared key but can run with a
+# pre-shared key, pass a pre-shared key. If the test looks like it can't run
+# with a pre-shared key, skip it. If the test looks like it's already using
+# a pre-shared key, do nothing.
+#
+# This code does not consider builds with ECDH-PSK or RSA-PSK.
```
Comment (mpg) [inline tests/ssl-opt.sh:321]: Typo: ECDHE-PSK

**Review by mpg — COMMENTED** [review]
Releasing comments from a partial review before I leave for the day. Tomorrow I'll start again with 6e86e54abbea94b048905219da333e9124fe5bb9

File: tests/ssl-opt.sh (hunk 3 above)
Comment (gilles-peskine-arm) [reply tests/ssl-opt.sh:1258]: I used the same punctuation before the word in several places, including `PSK` which could come at the beginning of a cipher suite. It happens that `tickets` is only relevant for mbedtls: openssl and gnutls only have `-no_ticket` and `--noticket` respectively. So I could change this one to require a space before. I'm not sure whether to go for uniformity or to get each case exactly right on its own. Getting each case exactly right isn't necessarily a good thing anyway since it's fragile, and being too picky could lead to tests not being executed when they're supported, which is bad.

**Comment by gilles-peskine-arm** [comment]
I've updated to address Manuel's comments. I still haven't addressed the CI failure, which is due to attempting to use `udp_proxy pack=…` in a configuration without `MBEDTLS_HAVE_TIME`. [I'm still unsure what to do about this](https://github.com/Mbed-TLS/mbedtls/pull/3624/files#r842125289).

File: tests/ssl-opt.sh [hunk 6]
```diff
@@ -6616,11 +6616,12 @@ run_test    "mbedtls_ssl_get_bytes_avail: no extra data" \
             -s "Read from client: 100 bytes read$"
 
 requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
+requires_max_content_len 474
```
Comment (mpg) [inline tests/ssl-opt.sh:6666]: Sorry if I'm missing something obvious, but why is this request size +24?

File: tests/ssl-opt.sh [hunk 7]
```diff
@@ -876,6 +876,38 @@ is_gnutls() {
...
+#
+# calc_verify is only called for two things: to calculate the
+# extended master secret, and to process client authentication.
+#
+# Warning: the current implementation assumes that extended_ms is not
+#          disabled on the client or on the server.
+#
+# Inputs:
+# * $1: 'required' or 1 if client authentication is expected,
+#       'none' or 0 or absent if not.
```
Comment (mpg) [inline tests/ssl-opt.sh:895]: I find 'none' a bit unintuitive, in that it will still end up setting the variable to something non-empty it if EMS is enabled. I'm not sure I have a better name to suggest, though. Perhaps 'auto'?

**Review by mpg — COMMENTED** [review]
Looks pretty good to me, just two minor points.

File: tests/ssl-opt.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (paul-elliott-arm) [reply tests/ssl-opt.sh:1259]: Oh, sorry, completely misread the github diff here.

File: tests/ssl-opt.sh (hunk 6 above)
Comment (gilles-peskine-arm) [reply tests/ssl-opt.sh]: Good question. I don't remember. I suspect I arrived at those two numbers independently and I forgot to reconcile them. I've changed those tests to be more precise and not rely on magic numbers defined elsewhere anymore.

File: tests/ssl-opt.sh (hunk 7 above)
Comment (gilles-peskine-arm) [reply tests/ssl-opt.sh]: Originally this was the `auth_mode` parameter. I ended up never calling this function with a parsed `auth_mode` (and in fact only ever calling it with `none`), but that could happen so I've kept the code but documented it.

**Review by mpg — COMMENTED** [review]
Looks good to me, but there's one test failing.

**Comment by gilles-peskine-arm** [comment]
With https://github.com/Mbed-TLS/mbedtls/pull/5708 as of e756f642cdf09ece1160d1c25edaea0f0be86b32, the failing test from `test-ref-configs.pl` now passes, so I don't intend to make further changes to this pull request.

**Review by mpg — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
Backport: https://github.com/Mbed-TLS/mbedtls/pull/5730 (might still need a few tweaks, I'm waiting for CI results). I'll forward-port a couple of commits that improve automatic requirement detection, which were not necessary in 3.1 (but are useful nonetheless) but were the shortest route to making 2.28 work.

**Comment by gilles-peskine-arm** [comment]
I've pushed what I wanted to push. Please wait for the CI to pass on both PR before reviewing, because I might rewrite history if the CI points out some minor mistakes.

File: ChangeLog.d/dtls-cid-null.txt [hunk 8]
```diff
@@ -0,0 +1,5 @@
+Bugfix
+   * In configurations with MBEDTLS_SSL_DTLS_CONNECTION_ID enabled but not
+     MBEDTLS_DEBUG_C, DTLS handshakes using CID would crash due to a null
+     pointer dereference. Fix this. Fixes #3998.
+     The fix was released, but not announced, in Mbed TLS 3.1.0.
```
[the remark this answers is not in the document]
Comment (AndrzejKurek) [reply ChangeLog.d/dtls-cid-null.txt:5]: I would say that it can be removed. A regression test for it will already exist, removing one whole build will save some time.

**Comment by gilles-peskine-arm** [comment]
This PR and its [backport](https://github.com/Mbed-TLS/mbedtls/pull/5730) are ready to review.

File: tests/ssl-opt.sh (hunk 3 above)
Comment (mpg) [reply tests/ssl-opt.sh]: Ok, let's go for uniformity then, especially now that all these tests are grouped in the same function.

**Review by mpg — DISMISSED** [review]
LGTM. Thanks!

**Comment by mpg** [comment]
Did we check that this PR doesn't result in more tests being skipped (incorrectly, then) in the default config / full config?

**Comment by gilles-peskine-arm** [comment]
@mpg Good point, I did partial incremental checks but not a final comprehensive check. I'll go and dig CI logs.

**Comment by mpg** [comment]
Well, I've been doing local runs. The last one's almost finished, I'll post the results in a moment.

**Comment by mpg** [comment]
Full config:

- before: `PASSED (842 / 842 tests (31 skipped))`
- after: `PASSED (844 / 844 tests (31 skipped))`

Default config:

- before: `PASSED (842 / 842 tests (421 skipped))`
- after: `PASSED (844 / 844 tests (421 skipped))`

For "before" I used the merge-base which is 9a34b60a9941b4cb5e41214991b8df558fe228db

The number skipped are identical but the total number of tests reported is 2 more after this PR.

**Comment by gilles-peskine-arm** [comment]
On both this PR and the 2.28 backport, I went and compared logs from the latest pr-merge and the nearest nightly:
* https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-merge/job/PR-5582-merge/37/ and https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/2542/
* https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-merge/job/PR-5730-merge/4/ and https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/2543/

I extracted `ssl-opt.sh` PASS lines from the full logs, but unfortunately they're hard to use because the lines from parallel jobs are mixed together. The nightly runs ssl-opt for coverage, so additional lines from that are expected. So I sorted the log lines and checked for lines that have more than one more occurrence in the nightly log compared to the PR log. This is what I found:
```
~/tmp/5582 % cat Makefile 
all: dev-nightly.pass dev-pr.pass lts-nightly.pass lts-pr.pass
all: dev-nightly-full.pass dev-pr-full.pass lts-nightly-full.pass lts-pr-full.pass

%.txt: %.html
        sed -n 's/^.*<\/style>//p' <$< >$@

%.pass: %.txt
        grep 'PASS$$' $< | grep -v '^test_suite_' | grep -v '^[mGO]->[mGO] ' |sort >$@
~/tmp/5582 % comm -23 dev-nightly.pass dev-pr.pass |uniq -d
PASS
Session resume using tickets, DTLS: openssl server ..................... PASS
mbedtls_ssl_get_bytes_avail: extra data ................................ PASS
~/tmp/5582 % comm -23 lts-nightly.pass lts-pr.pass |uniq -d
Fallback SCSV: disabled, openssl client ................................ PASS
Fallback SCSV: enabled, openssl client ................................. PASS
RC4: server enabled, client disabled ................................... PASS
mbedtls_ssl_get_bytes_avail: extra data ................................ PASS
```

So in the PR for `development`, there's the renamed test case (expected) and one flaky test which had a newline-RETRY-pass in the nightly, and all is good. In the 2.28 PR, there's the renamed test case (expected) and three test cases that are unexpected.
* `RC4: server enabled, client disabled` is still running in `full`, but there's one configuration where it's no longer running.
* `Fallback SCSV: disabled, openssl client` and `Fallback SCSV: enabled, openssl client` are no longer running in `full`.

Note that this analysis is imprecise: if a test case is now running in a config A but wasn't before, and was running in config B but isn't anymore, the two compensate.

I also checked the `full` configuration specifically (from the logs of `test_full_cmake_gcc_asan`), and the only difference is the two SCSV test cases in 2.28.

**Comment by gilles-peskine-arm** [comment]
Wouldn't it be nice if instead of digging through logs, there was a report from the CI containing a list of executed test cases with their _outcome_? :facepalm: 

As before, comparing last night's pr-merge with last night's nightly:

* https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-merge/job/PR-5582-merge/37/ and https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/2542/
* https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-merge/job/PR-5730-merge/4/ and https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/2543/

```
$ cat Makefile
all: dev-nightly-ssl.csv dev-pr-ssl.csv lts-nightly-ssl.csv lts-pr-ssl.csv
%-ssl.csv: %-outcomes.csv.xz
        xzcat $< | grep ';ssl-opt;' | sort >$@
$ comm -23 dev-nightly-ssl.csv dev-pr-ssl.csv |grep -v ';mbedtls_ssl_get_bytes_avail: extra data;'
Linux-x86_64;config-thread.h;ssl-opt;ECJPAKE: working, DTLS, nolog;PASS;
$ comm -23 lts-nightly-ssl.csv lts-pr-ssl.csv |grep -v ';mbedtls_ssl_get_bytes_avail: extra data;'
FreeBSD-amd64;component_test_cmake_out_of_source;ssl-opt;Fallback SCSV: beginning of list;SKIP;
Linux-x86_64;component_test_asan_remove_peer_certificate;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_asan_remove_peer_certificate;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_asan_remove_peer_certificate;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_default_cmake_gcc_asan;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_default_cmake_gcc_asan;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_default_cmake_gcc_asan;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_full_cmake_gcc_asan;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_full_cmake_gcc_asan;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_m32_o2;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_m32_o2;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_malloc_0_null;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_malloc_0_null;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_memory_buffer_allocator;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_memory_buffer_allocator;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_memory_buffer_allocator;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_memsan;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_memsan;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_memsan;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_no_pem_no_fs;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_no_pem_no_fs;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_no_pem_no_fs;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_no_renegotiation;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_no_renegotiation;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_no_renegotiation;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_no_use_psa_crypto_full_cmake_asan;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_no_use_psa_crypto_full_cmake_asan;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_sslv3;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_sslv3;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_sslv3;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len_CID;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len_CID;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len_CID;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len_record_splitting;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len_record_splitting;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_variable_ssl_in_out_buffer_len_record_splitting;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_zlib_cmake;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_zlib_cmake;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_zlib_cmake;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;component_test_zlib_make;ssl-opt;Fallback SCSV: disabled, openssl client;PASS;
Linux-x86_64;component_test_zlib_make;ssl-opt;Fallback SCSV: enabled, openssl client;PASS;
Linux-x86_64;component_test_zlib_make;ssl-opt;RC4: server enabled, client disabled;PASS;
Linux-x86_64;config-thread.h;ssl-opt;ECJPAKE: working, DTLS, nolog;PASS;
```

So in addition to the previously analyzed SCSV and RC4 test cases, there's one more difference:
```
Linux-x86_64;config-thread.h;ssl-opt;ECJPAKE: working, DTLS, nolog;PASS;
```
This difference comes from "test-ref-configs: clarify configuration-related traces", which fixed the bug in `test-ref-configs.pl` whereby it made indistinguishable reports from running tests in a certain configuration and running in that configuration plus PSA. So now, instead of seeing the line above twice, we have that line once and
```
Linux-x86_64;config-thread.h+PSA;ssl-opt;ECJPAKE: working, DTLS, nolog;PASS;
```
once. So all is good.

**Review by mpg — APPROVED** [review]
LGTM. Does this (and its backport) close #5731 then?

**Comment by gilles-peskine-arm** [comment]
@mpg Indeed it does. I've added the magic syntax to this PR's description.
