### PR TITLE
Fix undefined behavior in ssl_read if buf parameter is NULL

### LINKED ISSUE #3076: Undefined behavior in mbedtls_ssl_read
### Description
- Type: Bug 
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.21.0
OS version: Ubuntu 1
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  
GCC 9

**Expected behavior**   

Calling mbedtls_ssl_read(socketInfo->SSLContext, NULL, 0); should decrypt and readable socket data to its internal buffer without actually reading anything to user buffer.  This is useful in order to do before a call to mbedtls_ssl_get_bytes_avail to make sure it is accurate.

**Actual behavior**  

in mbedtls_ssl_read( mbedtls_ssl_context *ssl, unsigned char *buf, size_t len ), buf is unchecked and eventually passed to memcpy at line 5378.  Passing a NULL pointer to memcpy is undefiened behavior (AFAIK, refer [HERE](https://stackoverflow.com/questions/5243012/is-it-guaranteed-to-be-safe-to-perform-memcpy0-0-0)), even if the size parameter is 0.  In practice, this is not likely to cause an issue as most memcpy implementations will probably not read from src if size is 0, but GCC 9 debug build caused an abort if memcpy is called with buf == NULL.

Suggested fix:

Surround these lines with an if that tests buf for NULL

Line 5378:    memcpy( buf, ssl->in_offt, n );
Line 5379:    ssl->in_msglen -= n;

if (buf)
{
     memcpy( buf, ssl->in_offt, n );
     ssl->in_msglen -= n;
}

Also it may help to add an assertion at the start of the function to check that if buf is NULL, len must also be NULL, but I dont know if this adds any real value.

**Steps to reproduce**  
Can be seen just by looking at the code

### PR DESCRIPTION
**Pull request by daverodgman**
## Description

Updated version of #5527 

- Adds a corresponding fix to `mbedtls_ssl_write`
- Adds tests
- Adds a sign-off to cover @gilles-peskine-arm 's suggestion
- Updated Changelog

Fixes #3076

## Gatekeeper checklist

- [x] **changelog** provided
- [x] **backport** #7172 
- [x] **tests** provided

Note - I've disabled the test for DTLS as it's not a no-op here. Presumably this is expected behaviour - please can a reviewer who understands DTLS better should check this.

### CODE REVIEW

File: library/ssl_msg.c [hunk 1]
```diff
@@ -5593,8 +5593,10 @@ int mbedtls_ssl_read(mbedtls_ssl_context *ssl, unsigned char *buf, size_t len)
     n = (len < ssl->in_msglen)
         ? len : ssl->in_msglen;
 
-    memcpy(buf, ssl->in_offt, n);
-    ssl->in_msglen -= n;
+    if (len != 0) {
+        memcpy(buf, ssl->in_offt, n);
+        ssl->in_msglen -= n;
+    }
```
Comment (minosgalanakis) [inline library/ssl_msg.c:5599]: Not a blocker. 

What is the defined behaviour for `mbedtls_platform_zeroize(void *buf, 0 )` ? If that is not guaranteed to be a no-op for zero len, it may be better to handdle it in the if, else block

~~~~~
    if (len != 0) {
        memcpy(buf, ssl->in_offt, n);
        ssl->in_msglen -= n;
       mbedtls_platform_zeroize(ssl->in_offt, n);
    }
~~~~~~

File: library/ssl_msg.c [hunk 2]
```diff
@@ -5670,7 +5672,9 @@ static int ssl_write_real(mbedtls_ssl_context *ssl,
          */
         ssl->out_msglen  = len;
         ssl->out_msgtype = MBEDTLS_SSL_MSG_APPLICATION_DATA;
-        memcpy(ssl->out_msg, buf, len);
+        if (len > 0) {
+            memcpy(ssl->out_msg, buf, len);
+        }
 
         if ((ret = mbedtls_ssl_write_record(ssl, SSL_FORCE_FLUSH)) != 0) {
```
Comment (minosgalanakis) [inline library/ssl_msg.c:5679]: As above, is it possible to have `ssl->out_msglen == 0` and `ret = mbedtls_ssl_write_record(ssl, SSL_FORCE_FLUSH)) != 0` ?

**Review by minosgalanakis — COMMENTED** [review]
Looks good overall, however I am not certain if we should be calling it a no-op though. Effectively it should not perform the read/write operation when calling it with zero length, but there are operations performed.

File: library/ssl_msg.c (hunk 2 above)
Comment (daverodgman) [reply library/ssl_msg.c:5679]: I'm not able to trigger that case, so maybe not? But I don't think the behaviour of `mbedtls_ssl_write_record` should be affected by this change.

**Comment by daverodgman** [comment]
Actually you are right about it not being a no-op. If I put this code into the test case:

```
    if (ssl->conf->transport != MBEDTLS_SSL_TRANSPORT_DATAGRAM) {
        TEST_ASSERT(mbedtls_ssl_write(ssl, NULL, 0) == 0);
        TEST_ASSERT(mbedtls_ssl_write(ssl, NULL, 0) == 0);
        TEST_ASSERT(mbedtls_ssl_write(ssl, NULL, 0) == 0);
        TEST_ASSERT(mbedtls_ssl_write(ssl, NULL, 0) == 0);
    }
```

I start seeing some new failures, specifically `MBEDTLS_ERR_SSL_INVALID_MAC` returned where the tests expect `MBEDTLS_ERR_SSL_WANT_READ`, `MBEDTLS_ERR_SSL_WANT_WRITE`, or success. (It requires at least four repetitions for this to happen). @ronald-cron-arm this smells like a bug to me, WDYT?

**Comment by daverodgman** [comment]
> Actually you are right about it not being a no-op. If I put this code into the test case:
> 
> ```
>     if (ssl->conf->transport != MBEDTLS_SSL_TRANSPORT_DATAGRAM) {
>         TEST_ASSERT(mbedtls_ssl_write(ssl, NULL, 0) == 0);
>         TEST_ASSERT(mbedtls_ssl_write(ssl, NULL, 0) == 0);
>         TEST_ASSERT(mbedtls_ssl_write(ssl, NULL, 0) == 0);
>         TEST_ASSERT(mbedtls_ssl_write(ssl, NULL, 0) == 0);
>     }
> ```
> 
> I start seeing some new failures, specifically `MBEDTLS_ERR_SSL_INVALID_MAC` returned where the tests expect `MBEDTLS_ERR_SSL_WANT_READ`, `MBEDTLS_ERR_SSL_WANT_WRITE`, or success. (It requires at least four repetitions for this to happen). @ronald-cron-arm this smells like a bug to me, WDYT?

Discussed with Ronald - agreed that we should try to merge this fix, and separately raise an issue to cover this as it does look like a bug.

**Comment by daverodgman** [comment]
Captured the above not-a-no-op issue in #7233 as I think this is a separate issue - please ignore for the purposes of reviewing this fix.

**Review by AndrzejKurek — APPROVED** [review]
