### PR TITLE
Bignum: Implement fixed width raw modular multiplication

### LINKED ISSUE #6022: Bignum: Implement fixed width modular multiplication
**Prerequisites:** #6017 

Implement fixed width modular multiplication. The `_mod_raw` version should take a caller-managed buffer for the temporary buffer. The `_mod` version should allocate, pass and then free the temporary buffer.

Both functions should only handle the case when the modulus advertises Montgomery representation. (The fast reduction case will be added in #6025).

### PR DESCRIPTION
**Pull request by gabor-mezei-arm**
## Description

Implement fixed width modular multiplication. The `_mod_raw` version should take a caller-managed buffer for the temporary buffer. 

Resolve #6022 

## Gatekeeper checklist

- [x] **tests** provided, or not required

### CODE REVIEW

File: library/bignum_mod_raw.h [hunk 1]
```diff
@@ -170,6 +170,31 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
                               const mbedtls_mpi_uint *B,
                               const mbedtls_mpi_mod_modulus *N );
 
+/** \brief  Multiply two MPIs, returning the residue modulo the specified
+ *          modulus.
+ *
```
Comment (wernerlewis) [inline library/bignum_mod_raw.h:175]: Could clarify that this should only handle the case where the modulus `int_rep` is Montgomery.

File: library/bignum_mod_raw.h [hunk 2]
```diff
@@ -170,6 +170,31 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
...
+ * \param[out] X        The address of the result MPI.
+ *                      This must be initialized. Must have enough limbs to
+ *                      store the full value of the result.
+ * \param[in]  A        The address of the first MPI. This must be initialized.
+ * \param[in]  B        The address of the second MPI. This must be initialized.
+ * \param[in]  N        The address of the modulus. Used to perform a modulo
+ *                      operation on the result of the subtraction.
+ * \param[in]  T        The address of an MPI used by the multiplication
+ *                      as a temp variable.
```
Comment (wernerlewis) [inline library/bignum_mod_raw.h:190]: It isn't clear here how large the temporary storage needs to be. Details could be added, similar to those given for `mbedtls_mpi_core_montmul`.

Comment (minosgalanakis) [reply library/bignum_mod_raw.h:190]: > It isn't clear here how large the temporary storage needs to be. Details could be added, similar to those given for `mbedtls_mpi_core_montmul`.

I believe the equation used in `mbedtls_mpi_core_montmul` is pretty much applicable in more than one cases, including this one. Not directly related to the pr but could we consider it for #6684 ?

File: library/bignum_mod_raw.h [hunk 3]
```diff
@@ -170,6 +170,31 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
...
 
+/** \brief  Multiply two MPIs, returning the residue modulo the specified
+ *          modulus.
+ *
+ * The size of the operation is determined by \p N. \p A and \p B must have
+ * the same number of limbs as \p N.
+ *
+ * \p X may be aliased to \p A or \p B, or even both, but may not overlap
+ * either otherwise.
+ *
```
Comment (minosgalanakis) [inline library/bignum_mod_raw.h:181]: We may need to retain that information

~~~~~~~ 
* \p A and \p B may alias each other, if \p AN_limbs == \p B_limbs. They may
 * not alias \p N (since they must be in canonical form, they cannot == \p N).
~~~~~~~

File: library/bignum_mod_raw.h [hunk 4]
```diff
@@ -170,6 +170,31 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
...
+ * \param[out] X        The address of the result MPI.
```
Comment (minosgalanakis) [inline library/bignum_mod_raw.h:182]:
~~~~~~
 * \param[out]    X         The destination MPI, as a little-endian array of
 *                          length \p AN_limbs.
 *                          On successful completion, X contains the result of
 *                          the multiplication `A * B * R^-1` mod N where
 *                          `R = 2^(biL*AN_limbs)`.
~~~~~~~

File: library/bignum_mod_raw.h (hunk 2 above)
Comment (minosgalanakis) [reply library/bignum_mod_raw.h:190]: I am attaching the wording for T:

~~~~~~
 * \param[in,out] T         Temporary storage of size at least 2*AN_limbs+1 limbs.
 *                          Its initial content is unused and
 *                          its final content is indeterminate.
 *                          It must not alias or otherwise overlap any of the
 *                          other parameters.
 ~~~~~~

File: tests/suites/test_suite_bignum_mod_raw.function [hunk 5]
```diff
@@ -345,6 +345,113 @@ exit:
...
+    size_t limbs_N;
+    size_t limbs_R;
+
+    mbedtls_mpi_mod_modulus m;
+    mbedtls_mpi_mod_modulus_init( &m );
+
+    TEST_EQUAL( mbedtls_test_read_mpi_core( &A, &limbs_A, input_A ), 0 );
+    TEST_EQUAL( mbedtls_test_read_mpi_core( &B, &limbs_B, input_B ), 0 );
+    TEST_EQUAL( mbedtls_test_read_mpi_core( &N, &limbs_N, input_N ), 0 );
+    TEST_EQUAL( mbedtls_test_read_mpi_core( &R, &limbs_R, result  ), 0 );
```
Comment (minosgalanakis) [inline tests/suites/test_suite_bignum_mod_raw.function:371]:
```suggestion
    TEST_EQUAL( mbedtls_test_read_mpi_core( &R, &limbs_R, result ), 0 );
```

**Review by minosgalanakis — COMMENTED** [review]
Looks in good shape, minor documentation issues.

File: library/bignum_mod_raw.h (hunk 2 above)
Comment (tom-cosgrove-arm) [reply library/bignum_mod_raw.h:190]: Replying to myself: yes, I could do with this, so doing it in my current PR

File: library/bignum_mod_raw.h [hunk 6]
```diff
@@ -170,6 +170,31 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
                               const mbedtls_mpi_uint *B,
                               const mbedtls_mpi_mod_modulus *N );
 
+/** \brief  Multiply two MPIs, returning the residue modulo the specified
+ *          modulus.
+ *
+ * The size of the operation is determined by \p N. \p A and \p B must have
+ * the same number of limbs as \p N.
```
Comment (tom-cosgrove-arm) [inline library/bignum_mod_raw.h:177]: We're using wording like this now.
```suggestion
 * The size of the operation is determined by \p N. \p A, \p B and \p X must
 * all be associated with the modulus \p N and must all have the same number
 * of limbs as \p N.
```

File: library/bignum_mod_raw.h [hunk 7]
```diff
@@ -170,6 +170,31 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
...
+ *
+ * \p X may be aliased to \p A or \p B, or even both, but may not overlap
+ * either otherwise.
+ *
+ * \param[out] X        The address of the result MPI.
+ *                      This must be initialized. Must have enough limbs to
+ *                      store the full value of the result.
```
Comment (tom-cosgrove-arm) [inline library/bignum_mod_raw.h:184]: I'd remove `Must have enough limbs to store the full value of the result.` since it's covered by more restrictive text higher up (i.e. X must be associated with N => it will be the same size as N (but we state this anyway) => it will have enough limbs to store the result (so no need to say this last bit)

File: library/bignum_mod_raw.h [hunk 8]
```diff
@@ -170,6 +170,31 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
...
+ * \param[in]  A        The address of the first MPI. This must be initialized.
+ * \param[in]  B        The address of the second MPI. This must be initialized.
```
Comment (tom-cosgrove-arm) [inline library/bignum_mod_raw.h:186]: We don't need `This must be initialized` on `[in]` parameters - it's needed for `[out]` parameters where we use the constant-time functions that read the current value.

File: scripts/mbedtls_dev/bignum_mod_raw.py [hunk 9]
```diff
@@ -49,6 +49,25 @@ def result(self) -> List[str]:
...
+
+    def arguments(self) -> List[str]:
+        return [bignum_common.quote_str(n) for n in [self.arg_a,
+                                                     self.arg_b,
+                                                     self.arg_n]
+               ] + self.result()
+
+    def result(self) -> List[str]:
+        result = (self.int_a * self.int_b) % self.int_n
+        return [self.format_result(result)]
```
Comment (tom-cosgrove-arm) [inline scripts/mbedtls_dev/bignum_mod_raw.py:69]: Since `mbedtls_mpi_mod_raw_mul()` only takes input in Montgomery form, would it be simpler to have the Python calculate that and not do it in the `.function`?

File: tests/suites/test_suite_bignum_mod_raw.function (hunk 5 above)
Comment (tom-cosgrove-arm) [reply tests/suites/test_suite_bignum_mod_raw.function:371]: Honestly, I wouldn't bother with minor horizontal whitespace issues like this. I might still want `char*` fixed to `char *` (if there were issues like that) but most of this will be rewritten soon

File: tests/suites/test_suite_bignum_mod_raw.function [hunk 10]
```diff
@@ -345,6 +345,113 @@ exit:
 }
 /* END_CASE */
 
+/* BEGIN_CASE */
+void mpi_mod_raw_mul( char * input_A,
+                      char * input_B,
+                      char * input_N,
+                      char * result )
+{
```
[the remark this answers is not in the document]
Comment (gabor-mezei-arm) [reply tests/suites/test_suite_bignum_mod_raw.function:353]: I do not see any logic in putting the `N` to the first place in the parameter list. `A` `B` `N` is more logical, following the sequence of the operation and following the sequence of the tested function.

File: tests/suites/test_suite_bignum_mod_raw.function (hunk 5 above)
Comment (gabor-mezei-arm) [reply tests/suites/test_suite_bignum_mod_raw.function:371]: Extra space is added to be align with the above lines.

File: scripts/mbedtls_dev/bignum_mod_raw.py (hunk 9 above)
Comment (minosgalanakis) [reply scripts/mbedtls_dev/bignum_mod_raw.py:69]: That's a good catch. The test script's conversion functions have been merged. You can use [self.to_montgomery()](https://github.com/Mbed-TLS/mbedtls/blob/development/scripts/mbedtls_dev/bignum_common.py#L256-L257) to convert the data and the expected return greatly simplifying the .function

File: library/bignum_mod_raw.h [hunk 11]
```diff
@@ -170,6 +170,41 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
                               const mbedtls_mpi_uint *B,
                               const mbedtls_mpi_mod_modulus *N );
 
+/** \brief  Multiply two MPIs, returning the residue modulo the specified
+ *          modulus.
+ *
+ * \note Currently handles the case when `m->int_rep` is
```
Comment (wernerlewis) [inline library/bignum_mod_raw.h:176]:
```suggestion
 * \note Currently handles the case when `N->int_rep` is
```

File: library/bignum_mod_raw.h [hunk 12]
```diff
@@ -170,6 +170,41 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
...
+ * \param[out] X        The address of the result MPI. Must have the same
+ *                      number of limbs as \p N.
+ *                      On successful completion, \p X contains the result of
+ *                      the multiplication `A * B * R^-1` mod N where
+ *                      `R = 2^(biL * N->limbs)`.
+ * \param[in]  A        The address of the first MPI.
+ * \param[in]  B        The address of the second MPI.
+ * \param[in]  N        The address of the modulus. Used to perform a modulo
+ *                      operation on the result of the multiplication.
+ * \param[in,out] T     Temporary storage of size at least 2 * AN_limbs + 1
```
Comment (wernerlewis) [inline library/bignum_mod_raw.h:196]:
```suggestion
 * \param[in,out] T     Temporary storage of size at least 2 * N->limbs + 1
```

File: library/bignum_mod_raw.h [hunk 13]
```diff
@@ -170,6 +170,31 @@ void mbedtls_mpi_mod_raw_sub( mbedtls_mpi_uint *X,
...
+ * \p X may be aliased to \p A or \p B, or even both, but may not overlap
+ * either otherwise.
+ *
+ * \param[out] X        The address of the result MPI.
+ *                      This must be initialized. Must have enough limbs to
+ *                      store the full value of the result.
+ * \param[in]  A        The address of the first MPI. This must be initialized.
+ * \param[in]  B        The address of the second MPI. This must be initialized.
+ * \param[in]  N        The address of the modulus. Used to perform a modulo
+ *                      operation on the result of the subtraction.
```
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply library/bignum_mod_raw.h]: This has been done, so marking resolved

File: library/bignum_mod_raw.h (hunk 1 above)
Comment (tom-cosgrove-arm) [reply library/bignum_mod_raw.h:175]: This has been done, so marking resolved

File: library/bignum_mod_raw.h (hunk 2 above)
Comment (tom-cosgrove-arm) [reply library/bignum_mod_raw.h]: The information has been added, so resolving this conversation

File: library/bignum_mod_raw.h (hunk 4 above)
Comment (tom-cosgrove-arm) [reply library/bignum_mod_raw.h]: Pretty much done, so marking resolved

File: library/bignum_mod_raw.h (hunk 3 above)
Comment (tom-cosgrove-arm) [reply library/bignum_mod_raw.h:182]: This has been done, so marking resolved

File: tests/suites/test_suite_bignum_mod_raw.function (hunk 5 above)
Comment (tom-cosgrove-arm) [reply tests/suites/test_suite_bignum_mod_raw.function:371]: whitespace, so marking as resolved

**Review by wernerlewis — COMMENTED** [review]
Couple of minor documentation errors, otherwise LGTM.

File: library/bignum_mod_raw.h (hunk 11 above)
Comment (tom-cosgrove-arm) [reply library/bignum_mod_raw.h:176]: Should it be "only handles the case..."?

**Review by minosgalanakis — APPROVED** [review]
LGTM

The documentation chages proposed by @wernerlewis would be good to have.

**Review by wernerlewis — APPROVED** [review]
LGTM

**Review by minosgalanakis — APPROVED** [review]
