### PR TITLE
	Bignum: Implement high level fixed width modular inversion

### LINKED ISSUE #6292: Bignum: Implement high level fixed width modular inversion
**Prerequisites:** #6023

Implement `mbedtls_mpi_mod_inv`. The task is constrained to prime moduli for now, and this should be documented.

This functions should allocate the needed temporary storage and perform necessary pre and post processing depending on the representation used by the modulus. (If it isn't in Montgomery form, it needs to be converted before `mbedtls_mpi_mod_raw_inv_prime` is called and needs to be converted back after.)

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
Resolves #6292

## Gatekeeper checklist

- [x] **changelog** not required - an over-arching bignum ChangeLog will be created at some point
- [x] **backport** not required - this is `development` only
- [x] **tests** provided

### CODE REVIEW

**Comment by tom-cosgrove-arm** [comment]
The "use separate functions for mont/non-mont" form looks like this. It would be possible to remove `mbedtls_mpi_mod_inv_mont()` and have a call to `mbedtls_mpi_mod_raw_inv_prime()` direct in `mbedtls_mpi_mod_inv()`, but if we're going for readability this symmetric version is better.

```
static int mbedtls_mpi_mod_inv_mont( mbedtls_mpi_mod_residue *X,
                                     const mbedtls_mpi_mod_residue *A,
                                     const mbedtls_mpi_mod_modulus *N,
                                     mbedtls_mpi_uint *working_memory )
{
    /* Input already in Montgomery form, so there's little to do */
    mbedtls_mpi_mod_raw_inv_prime( X->p, A->p,
                                   N->p, N->limbs,
                                   N->rep.mont.rr,
                                   working_memory );
    return( 0 );
}

static int mbedtls_mpi_mod_inv_non_mont( mbedtls_mpi_mod_residue *X,
                                         const mbedtls_mpi_mod_residue *A,
                                         const mbedtls_mpi_mod_modulus *N,
                                         mbedtls_mpi_uint *working_memory )
{
    /* Need to convert input into Montgomery form */

    int ret = MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED;

    mbedtls_mpi_mod_modulus Nmont;
    mbedtls_mpi_mod_modulus_init( &Nmont );

    MBEDTLS_MPI_CHK( mbedtls_mpi_mod_modulus_setup( &Nmont, N->p, N->limbs,
                                         MBEDTLS_MPI_MOD_REP_MONTGOMERY ) );

    /* We'll use X-> to hold the Montgomery form of the input A->p */
    mbedtls_mpi_core_to_mont_rep( X->p, A->p, Nmont.p, Nmont.limbs,
                                  Nmont.rep.mont.mm, Nmont.rep.mont.rr,
                                  working_memory );

    mbedtls_mpi_mod_raw_inv_prime( X->p, X->p,
                                   Nmont.p, Nmont.limbs,
                                   Nmont.rep.mont.rr,
                                   working_memory );

    mbedtls_mpi_core_from_mont_rep( X->p, X->p, Nmont.p, Nmont.limbs,
                                    Nmont.rep.mont.mm, working_memory );

cleanup:
    mbedtls_mpi_mod_modulus_free( &Nmont );
    return( ret );
}

int mbedtls_mpi_mod_inv( mbedtls_mpi_mod_residue *X,
                         const mbedtls_mpi_mod_residue *A,
                         const mbedtls_mpi_mod_modulus *N )
{
    if( X->limbs != N->limbs || A->limbs != N->limbs )
        return( MBEDTLS_ERR_MPI_BAD_INPUT_DATA );

    /* Zero has the same value regardless of Montgomery form or not */
    if( mbedtls_mpi_core_check_zero_ct( A->p, A->limbs ) == 0 )
        return( MBEDTLS_ERR_MPI_BAD_INPUT_DATA );

    size_t working_limbs =
                    mbedtls_mpi_mod_raw_inv_prime_working_limbs( N->limbs );

    mbedtls_mpi_uint *working_memory = mbedtls_calloc( working_limbs,
                                                     sizeof(mbedtls_mpi_uint) );
    if( working_memory == NULL )
        return( MBEDTLS_ERR_MPI_ALLOC_FAILED );

    int ret = MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED;

    switch( N->int_rep )
    {
        case MBEDTLS_MPI_MOD_REP_MONTGOMERY:
            ret = mbedtls_mpi_mod_inv_mont( X, A, N, working_memory );
            break;
        case MBEDTLS_MPI_MOD_REP_OPT_RED:
            ret = mbedtls_mpi_mod_inv_non_mont( X, A, N, working_memory );
            break;
        default:
            ret = MBEDTLS_ERR_MPI_BAD_INPUT_DATA;
            break;
    }

    mbedtls_platform_zeroize( working_memory,
                              working_limbs * sizeof(mbedtls_mpi_uint) );
    free( working_memory );

    return ret;
}
```

File: library/bignum_mod.c [hunk 1]
```diff
@@ -191,6 +191,95 @@ int mbedtls_mpi_mod_sub( mbedtls_mpi_mod_residue *X,
...
+    int ret = MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED;
+
+    mbedtls_mpi_mod_modulus Nmont;
+    mbedtls_mpi_mod_modulus_init( &Nmont );
+
+    MBEDTLS_MPI_CHK( mbedtls_mpi_mod_modulus_setup( &Nmont, N->p, N->limbs,
+                                         MBEDTLS_MPI_MOD_REP_MONTGOMERY ) );
+
+    /* We'll use X->p to hold the Montgomery form of the input A->p */
+    mbedtls_mpi_core_to_mont_rep( X->p, A->p, Nmont.p, Nmont.limbs,
```
Comment (minosgalanakis) [inline library/bignum_mod.c:224]: Any reason we are not invoking the `mbedtls_mpi_core_to_mont_rep()`? I assume that the main reason behind that design is memory ownership, and in particular who owns the memory pointed by `*working_memory`

Given this use case I would rather we modify `mbedtls_mpi_mod_raw_to_mont_rep` to now allocate memory and have a high level mod_owned version to do so.

### High level mod_to_mont_rep (owning the memory pointed by `*T` )
~~~~~
int mbedtls_mpi_mod_to_mont_rep( mbedtls_mpi_uint *X,
                                     const mbedtls_mpi_mod_modulus *m)
{
    mbedtls_mpi_uint *T;
    const size_t t_limbs = m->limbs * 2 + 1;

    if( ( T = (mbedtls_mpi_uint *) mbedtls_calloc( t_limbs, ciL ) ) == NULL )
        return( MBEDTLS_ERR_MPI_ALLOC_FAILED );
    
    mbedtls_mpi_mod_raw_to_mont_rep(X, m, T)
    mbedtls_mpi_core_montmul( X, X, m->rep.mont.rr, m->limbs, m->p, m->limbs,
                              m->rep.mont.mm, T );

    mbedtls_platform_zeroize( T, t_limbs * ciL );
    mbedtls_free( T );
    return( 0 );
}
~~~~~~


### Mid Level mod_to_mont_rep (Abstracting the core to  montumul)
~~~~~~
int mbedtls_mpi_mod_raw_to_mont_rep( mbedtls_mpi_uint *X,
                                     const mbedtls_mpi_mod_modulus *m,
                                     mbedtls_mpi_uint *T)
{
    const size_t t_limbs = m->limbs * 2 + 1;

    mbedtls_mpi_core_montmul( X, X, m->rep.mont.rr, m->limbs, m->p, m->limbs,
                              m->rep.mont.mm, T );

    return( 0 );
}
~~~~~

**Review by minosgalanakis — COMMENTED** [review]
Looking at it on a design level, this PR seem to doing three things:

* Adjusting how the conversion to and from montgomery form is handled
* Introducing some usefull helper methods and minor bug fixes.
* Addomg the requested by the specifications functionality for modular inversion.

My only concern design wise is the reason we need to introduce a core level conversion method, rather than a high level one, and adjusting the mod_raw level to not allocate any memory.

Are we expecting many functions in core to need the conversion? And since it is all but an invocation of montmul, I can see no reason other than readability that it should warrant a core version.

File: library/bignum_core.h [hunk 2]
```diff
@@ -572,6 +576,111 @@ mbedtls_mpi_uint mbedtls_mpi_core_sub_int( mbedtls_mpi_uint *X,
...
+ *
+ * \param[out]    X         The result of the conversion.
+ *                          Must have the same number of limbs as \p A.
+ * \param[in]     A         The MPI to convert from Montgomery form.
+ *                          Must have the same number of limbs as the modulus.
+ * \param[in]     N         The address of the modulus, which gives the size of
+ *                          the base `R` = 2^(biL*m->limbs).
+ * \param[in]     AN_limbs  The number of limbs in \p X, \p A and \p N.
+ * \param         mm        The Montgomery constant for \p N: -N^-1 mod 2^biL.
+ *                          This can be determined  by calling
```
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply library/bignum_core.h]: nice catch - I'm annoyed I missed this!

File: library/bignum_core.h [hunk 3]
```diff
@@ -572,6 +576,111 @@ mbedtls_mpi_uint mbedtls_mpi_core_sub_int( mbedtls_mpi_uint *X,
...
+ *
+ * \param AN_limbs The number of limbs in the input `A` and the modulus `N`
+ *                 (they must be the same size) that will be given to
+ *                 `mbedtls_mpi_core_montmul()` or one of the other functions
+ *                 that specifies this as the amount of working memory needed.
+ *
+ * \return         The number of limbs of working memory required by
+ *                 `mbedtls_mpi_core_montmul()` (or other similar function).
+ */
+static inline size_t mbedtls_mpi_core_montmul_working_limbs( size_t AN_limbs )
```
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply library/bignum_core.h:604]: Yes, we are expecting the compiler to optimise this function out. This is idiomatic in C (using `static inline` is pretty much the only version of inlining that has been the same since before C99 inline, back to the GBU89 extensions).

> Wouldn't using static in a header create discrete units of that method in all files that include it

That will only happen (in practice) if each of those files tries to take the address of this function (for example, to assign it to a function pointer).

File: library/bignum_mod.c (hunk 1 above)
Comment (tom-cosgrove-arm) [reply library/bignum_mod.c:224]: The main difference is that I wanted a version of Montgomery conversion that wasn't in-place.

Since the conversions we currently have are in mod_raw, it made sense to put the new ones in core - I assume that the design and location of the current ones is as per spec, so I'm not going to move them around - certainly not in this PR.

Since core already understands stuff that is in Montgomery form only, it doesn't seem to me to be a problem to have a thin pair of conversion functions there.

If we want to rewrite the montgomery conversion in mod_raw to not allocate, we can, but that won't help me especially here - I'd still have the in-place issue. And I presume having the mod_raw version allocate was part of its origin design.

**Comment by tom-cosgrove-arm** [comment]
Rebased on top of latest `development` due to conflicts

**Comment by tom-cosgrove-arm** [comment]
Grr, the Montgomery-form test cases are too similar to the test cases for `mbedtls_mpi_mod_raw_inv_prime()` :(

**Review by minosgalanakis — CHANGES_REQUESTED** [review]
Looks good overall, requires minor modification to the test generation suites, and a TD item to be raised about the design requirements of the multi level conversion functions.

File: scripts/mbedtls_dev/bignum_common.py [hunk 4]
```diff
@@ -287,6 +302,8 @@ def r2(self) -> int: # pylint: disable=invalid-name
     def is_valid(self) -> bool:
         if self.int_a >= self.int_n:
             return False
+        if self.disallow_zero_a and self.int_a == 0:
```
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply scripts/mbedtls_dev/bignum_common.py:305]: When I did this, I got errors from pylint about too much duplicated code.

This is an ongoing problem, and I think we're a bit close to deadline to change what we're doing now, which is: to avoid duplication, if code needs to be repeated enough for pylint to complain, it needs to be an option in the base class.

I don't like this, but I don't like Python either :) and nor do I like that our code-checking tools are preventing us writing the code we would like to write. This is the tail wagging the dog! but it's the route we've chosen to go down.

File: scripts/mbedtls_dev/bignum_common.py [hunk 5]
```diff
@@ -244,6 +249,8 @@ class ModOperationCommon(OperationCommon):
     #pylint: disable=abstract-method
     """Target for bignum mod_raw test case generation."""
     moduli = MODULI_DEFAULT # type: List[str]
+    mongtomgery_form_a = False
```
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply scripts/mbedtls_dev/bignum_common.py:252]: We either do this or we stop using pylint.

File: library/bignum_mod.c [hunk 6]
```diff
@@ -191,6 +191,95 @@ int mbedtls_mpi_mod_sub( mbedtls_mpi_mod_residue *X,
...
+
+    /* Zero has the same value regardless of Montgomery form or not */
+    if( mbedtls_mpi_core_check_zero_ct( A->p, A->limbs ) == 0 )
+        return( MBEDTLS_ERR_MPI_BAD_INPUT_DATA );
+
+    size_t working_limbs =
+                    mbedtls_mpi_mod_raw_inv_prime_working_limbs( N->limbs );
+
+    mbedtls_mpi_uint *working_memory = mbedtls_calloc( working_limbs,
+                                                     sizeof(mbedtls_mpi_uint) );
```
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply library/bignum_mod.c:258]: If I move it far enough to the right to line up it goes over the 80-character boundary. This is a compromise to make it easy to read (eyes don't have to dart too much further to the left on the second line).

And whitespace is going to be re-written anyway soon

File: scripts/mbedtls_dev/bignum_core.py [hunk 7]
```diff
@@ -757,15 +757,7 @@ class BignumCoreExpMod(BignumCoreTarget, bignum_common.ModOperationCommon):
...
-
-    def arguments(self) -> List[str]:
-        # Input 'a' has to be given in Montgomery form
-        mont_a = self.to_montgomery(self.int_a)
-        arg_mont_a = self.format_arg('{:x}'.format(mont_a))
-        return [bignum_common.quote_str(n) for n in [self.arg_n,
-                                                     arg_mont_a,
-                                                     self.arg_b]
-               ] + self.result()
+    mongtomgery_form_a = True
```
[the remark this answers is not in the document]
Comment (tom-cosgrove-arm) [reply scripts/mbedtls_dev/bignum_core.py:760]: The benefit of merge slots is that most of the work is done in them. It doesn't have to be exclusively in the merge slot, and because most is there small changes elsewhere are possible without conflicts.

**Review by minosgalanakis — APPROVED** [review]
Upon discussing it, the python test modifciation will work for now. So the proposed changes are now "good to have" but not "must have".

If refactoring is required by the second review, please consider them.

File: library/bignum_core.h [hunk 8]
```diff
@@ -572,6 +576,111 @@ mbedtls_mpi_uint mbedtls_mpi_core_sub_int( mbedtls_mpi_uint *X,
...
+ * This function is a thin wrapper around `mbedtls_mpi_core_montmul()` that is
+ * an alternative to calling `mbedtls_mpi_mod_raw_to_mont_rep()` when we
+ * don't want to allocate memory.
+ *
+ * \param[out]    X         The result of the conversion.
+ *                          Must have the same number of limbs as \p A.
+ * \param[in]     A         The MPI to convert into Montgomery form.
+ *                          Must have the same number of limbs as the modulus.
+ * \param[in]     N         The address of the modulus, which gives the size of
+ *                          the base `R` = 2^(biL*m->limbs).
```
Comment (wernerlewis) [inline library/bignum_core.h:626]:
```suggestion
 *                          the base `R` = 2^(biL*N->limbs).
```

File: library/bignum_core.h [hunk 9]
```diff
@@ -572,6 +576,111 @@ mbedtls_mpi_uint mbedtls_mpi_core_sub_int( mbedtls_mpi_uint *X,
...
+ * This function is a thin wrapper around `mbedtls_mpi_core_montmul()` that is
+ * an alternative to calling `mbedtls_mpi_mod_raw_from_mont_rep()` when we
+ * don't want to allocate memory.
+ *
+ * \param[out]    X         The result of the conversion.
+ *                          Must have the same number of limbs as \p A.
+ * \param[in]     A         The MPI to convert from Montgomery form.
+ *                          Must have the same number of limbs as the modulus.
+ * \param[in]     N         The address of the modulus, which gives the size of
+ *                          the base `R` = 2^(biL*m->limbs).
```
Comment (wernerlewis) [inline library/bignum_core.h:664]:
```suggestion
 *                          the base `R` = 2^(biL*N->limbs).
```

File: scripts/mbedtls_dev/bignum_common.py [hunk 10]
```diff
@@ -263,6 +270,14 @@ def from_montgomery(self, val: int) -> int:
     def boundary(self) -> int:
         return self.int_n
 
+    @property
+    def arg_a(self) -> str:
+        if self.mongtomgery_form_a:
```
Comment (wernerlewis) [inline scripts/mbedtls_dev/bignum_common.py:275]: Here and elsewhere, spelling:
```suggestion
        if self.montgomery_form_a:
```

**Review by wernerlewis — DISMISSED** [review]
A couple of minor documentation and typo fixes that would be good to have. Otherwise, LGTM.

File: library/bignum_mod.c (hunk 1 above)
Comment (minosgalanakis) [reply library/bignum_mod.c:224]: I have created a TD item to track this , and allow the team discuss on the design #6815. I will resolve this since it is now out of scope.

File: scripts/mbedtls_dev/bignum_common.py (hunk 10 above)
Comment (tom-cosgrove-arm) [reply scripts/mbedtls_dev/bignum_common.py:275]: bah - nice spot!

**Comment by tom-cosgrove-arm** [comment]
I've fixed the typos @wernerlewis found, so can you please re-review?

**Review by wernerlewis — APPROVED** [review]
LGTM

**Review by minosgalanakis — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
CI is fully green ; removing `needs-ci`
