### PR TITLE
psa_cipher_decrypt CCM*: fix rejection of messages shorter than 3 bytes

### LINKED ISSUE #9314: psa_cipher_decrypt with CCM* rejects very short messages
`psa_cipher_decrypt` takes an input which is the IV concatenated with the ciphertext proper. It validates that the input is at least as large as the IV. This validation is wrong for `PSA_ALG_CCM_STAR_NO_TAG`: the length enforcement is for 16 bytes but the IV length is actually 13. As a consequence, `psa_cipher_decrypt` incorrectly returns `PSA_ERROR_INVALID_ARGUMENT` when the message is 3 bytes or less.

Workaround: the multipart interface works fine.

[Found by Cryptofuzz](https://github.com/guidovranken/cryptofuzz/pull/77#issuecomment-2189533504).

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
[Found by Cryptofuzz](https://github.com/guidovranken/cryptofuzz/pull/77#issuecomment-2189533504). Fixes #9314.

Specification links:

* [`PSA_ALG_CCM_STAR_NO_TAG`](https://arm-software.github.io/psa-api/crypto/1.2/api/ops/ciphers.html#c.PSA_ALG_CCM_STAR_NO_TAG) — note in particular “default IV length of 13”.
* [`psa_cipher_decrypt`](https://arm-software.github.io/psa-api/crypto/1.2/api/ops/ciphers.html#c.psa_cipher_decrypt)

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** provided
- [x] **3.6 backport** https://github.com/Mbed-TLS/mbedtls/pull/9341
- [x] **2.28 backport** no (no CCM\* in 2.28)
- [x] **tests** provided

### CODE REVIEW

File: library/psa_crypto.c [hunk 1]
```diff
@@ -4631,11 +4631,7 @@ psa_status_t psa_cipher_decrypt(mbedtls_svc_key_id_t key,
         goto exit;
     }
 
-    if (alg == PSA_ALG_CCM_STAR_NO_TAG &&
-        input_length < PSA_BLOCK_CIPHER_BLOCK_LENGTH(slot->attr.type)) {
```
Comment (sezrab) [inline library/psa_crypto.c:4635]: If the issue is with the fact that the input_length (lengths of IV (default 13) + message?) is less than the block length (which is 16) IF the message is < 3 bytes, I don't understand why the fix doesn't lie within `PSA_BLOCK_CIPHER_BLOCK_LENGTH`

If it is okay to remove `...input_length < PSA_BLOCK_CIPHER_BLOCK_LENGTH(slot->attr.type)) {`, why was it there in the first place?

**Review by sezrab — APPROVED** [review]
LGTM!

**Review by sezrab — APPROVED** [review]
