### PR TITLE
Make generate_errors.pl handle directory names containing spaces when opening files

### LINKED ISSUE #6879: Error: 'MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE' undeclared, while building with cmake.
### Summary
After cloning the project , when I try to build it using cmake  It throws an error. 

`error.c:108:25: error: ‘MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE’ undeclared`

### System information

> Mbed TLS version (number or commit id): 
- Version : Mbed TLS 3.3.0
- Last commit ```8c89224991adff88d53cd380f42a2baa36f91454```

> Operating system and version: 
- Operating System : Linux Mint 21 Cinnamon
- Cinnamon version : 5.4.12
- Kernel : 5.15.0-56-generic
- Configuration (if not default, please attach `mbedtls_config.h`):  Configuration is [default](https://github.com/Mihir-Raj-Singh/mbedtls/blob/262851df1cc4f090b3e2920cd647d5e22c9bb2f1/include/mbedtls/mbedtls_config.h).

> Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
- None

> Additional environment information: 
- None

### Expected behavior

- Build process must run successfully and produced the desired files.

### Actual behavior

- Throws an error :

```/home/scorpion/Desktop/Untitled Folder/build/library/error.c: In function ‘mbedtls_strerror’:
/home/scorpion/Desktop/Untitled Folder/build/library/error.c:108:25: error: ‘MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE’ undeclared (first use in this function); did you mean ‘MBEDTLS_SSL_ALL_ALERT_MESSAGES’?
  108 |         if(use_ret == -(MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE))
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         MBEDTLS_SSL_ALL_ALERT_MESSAGES
/home/scorpion/Desktop/Untitled Folder/build/library/error.c:108:25: note: each undeclared identifier is reported only once for each function it appears in
gmake[2]: *** [library/CMakeFiles/mbedcrypto.dir/build.make:551: library/CMakeFiles/mbedcrypto.dir/error.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:813: library/CMakeFiles/mbedcrypto.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
![cmake](https://user-images.githubusercontent.com/92584041/210714678-45127b40-67d6-449a-9886-f5a7d75404fd.png)

```
### Steps to reproduce

- clone the repo on your local system
- `mkdir build`
- `cd build`
- `cmake /path/to/mbedtls/folder/`
- `cmake --build .`

### Additional information

> `cmake /path/to/mbedtls/folder/` output :

Image 1

>  `cmake --build .` output :

Image 2

### PR DESCRIPTION
**Pull request by tom-daubney-arm**
Fixes #6879 

## Description

Modify generate_errors.pl such that it can now handle opening files where the file path includes a directory name containing spaces.

Fix provided by
@tom-cosgrove-arm in aforementioned issue.

2.28 backport: #6894 

## Gatekeeper checklist

- [ ] **changelog** provided
- [ ] **backport** done PR #6894
- [ ] **tests** not required - this is a robustness improvement to parts of the build system

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

### CODE REVIEW

File: ChangeLog.d/fix_build_for_directory_names_containing_spaces.txt [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Bugfix
+   * Fix a bug in the build where directory names containing spaces were
+     causing generate_errors.pl to error out resulting in a build failure.
+     Raised in issue #6879.
```
Comment (tom-cosgrove-arm) [inline ChangeLog.d/fix_build_for_directory_names_containing_spaces.txt:4]: This should probably say "Fixes #6879." and should definitely end with a newline.

**Review by tom-cosgrove-arm — CHANGES_REQUESTED** [review]

File: ChangeLog.d/fix_build_for_directory_names_containing_spaces.txt (hunk 1 above)
Comment (tom-daubney-arm) [reply ChangeLog.d/fix_build_for_directory_names_containing_spaces.txt:4]: But it doesn't fully fix #6879 though does it? In @gilles-peskine-arm's [comment](https://github.com/Mbed-TLS/mbedtls/issues/6879#issuecomment-1373712786) he mentioned two bugs. The first being the issue with the script, that this PR addresses and the other being the fact that the Perl script erroring out didn't halt the build.

Should I use this PR to close issue #6879 and then file a separate issue for the fact that errors in generate_errors.pl does not halt the build process?

Comment (tom-cosgrove-arm) [reply ChangeLog.d/fix_build_for_directory_names_containing_spaces.txt]: It does fix both issues. The `glob` change makes it work with spaces in the path, and the `or die` change will make it out.

What we saw in the build was a warning on the `<FILE>` input because the `open` didn't work; the `die` means that an error is reported instead, which does halt the build.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM
