### PR TITLE
Have compat.sh and ssl-opt.sh not return success for > 255 errors

### LINKED ISSUE #2068: ssl-opt.sh and compat.sh return 0 if there are 256 errors
Both `ssl-opt.sh` and `compat.sh` attempt to use the number of failures as their return status. But the return status of a shell script is taken modulo 256. If the number of failures is a nonzero multiple of 256, the scripts do print “FAIL” but they return a success status. This could cause CI failures to occasionally go undetected.

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
Fixes #2068

## Gatekeeper checklist

- [x] **changelog** not required - this isn't a user-facing change
- [x] **backport** done (#6928)
- [x] **tests** not required - these are minor fixes to test scripts

### CODE REVIEW

File: tests/compat.sh [hunk 1]
```diff
@@ -1123,4 +1122,7 @@ PASSED=$(( $TESTS - $FAILED ))
 echo " ($PASSED / $TESTS tests ($SKIPPED skipped$MEMREPORT))"
 
 FAILED=$(( $FAILED + $SRVMEM ))
+if [ $FAILED -gt 255 ]; then
+    FAILED=255
```
Comment (daverodgman) [inline tests/compat.sh:1126]: I'd put a comment to explain here

File: tests/ssl-opt.sh [hunk 2]
```diff
@@ -13312,4 +13312,7 @@ fi
 PASSES=$(( $TESTS - $FAILS ))
 echo " ($PASSES / $TESTS tests ($SKIPS skipped))"
 
+if [ $FAILS -gt 255 ]; then
+    FAILS=255
```
Comment (daverodgman) [inline tests/ssl-opt.sh:13316]: Again, comment would be good

**Review by daverodgman — CHANGES_REQUESTED** [review]
Ideally would be good to have comments IMO

**Review by daverodgman — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
CI is green - ready to merge
