### PR TITLE
Fix build of v3.6 (issues #9186 and #9188)

### LINKED ISSUE #9186: Build library failed for server mode only: missing-prototypes for mbedtls_ssl_conf_has_static_psk
### Summary

I stumbled on this bug using mbedtls with the ESP-IDF Framework. But I was unsure if this is a general bug of mbedtls, so I cloned the original code and could reproduce the build fail with the most recent v3.6.0 and develop

### System information

Mbed TLS version (number or commit id): v3.6.0 and develop
Operating system and version: Manjaro 24.0
Configuration (if not default, please attach `mbedtls_config.h`): Undefine `MBEDTLS_SSL_CLI_C`
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): GCC 13
Additional environment information: -

### Expected behavior

I should be able to build the mbedtls library without client mode. After all it looks like `MBEDTLS_SSL_CLI_C` is a selectable option in mbedtls_config.h. More technical insight in "Additional information".

### Actual behavior

Build fails with:

```
Software/mbedtls/library/ssl_tls.c:2120:5: error: no previous prototype for ‘mbedtls_ssl_conf_has_static_psk’ [-Werror=missing-prototypes]
 2120 | int mbedtls_ssl_conf_has_static_psk(mbedtls_ssl_config const *conf)
```

More technical insight in "Additional information".

### Steps to reproduce

From an unmodified clone: Undefine `MBEDTLS_SSL_CLI_C` (e.g. comment it out) and try to build the library using CMake.

### Additional information

I think I figured the problem out already:

1. If we are in the `MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED` situation ssl_tls.c [defines](https://github.com/Mbed-TLS/mbedtls/blob/c7569a8c4bc7525a4d4d435eb3cd04031d7f64bc/library/ssl_tls.c#L2120) and [uses](https://github.com/Mbed-TLS/mbedtls/blob/c7569a8c4bc7525a4d4d435eb3cd04031d7f64bc/library/ssl_tls.c#L9542) the function `mbedtls_ssl_conf_has_static_psk`.
2. But for the prototype declaration of the external function the define above is not enough: It also needs [MBEDTLS_SSL_CLI_C](https://github.com/Mbed-TLS/mbedtls/blob/c7569a8c4bc7525a4d4d435eb3cd04031d7f64bc/library/ssl_misc.h#L1512)
3. This leads to the situation of a used function without prototype and mbedtls takes this pretty seriously. At least it looks like the Werror=missing-prototypes setting is very intentional in the [CMake configuration file](https://github.com/Mbed-TLS/mbedtls/blob/c7569a8c4bc7525a4d4d435eb3cd04031d7f64bc/library/CMakeLists.txt#L200).
4. Solution: Definitely declaration, definition and usage of the functions should all be aligned under the same define-requirements. Most likely either the `MBEDTLS_SSL_CLI_C` needs to be removed from the header or added in the source. But I am not enough of an mbedtls expert to create a PR right away.

### LINKED ISSUE #9188: Build fails with unset MBEDTLS_DHM_C but MBEDTLS_USE_PSA_CRYPTO set
### Summary

Build fails with the following custom configuration:
- set: `MBEDTLS_USE_PSA_CRYPTO`
- unset: `MBEDTLS_DHM_C`
- unset: `MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED`
- unset: `MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED`

### System information

Mbed TLS version: v3.6.0 and development branch
Operating system and version: macOS 12.6
Configuration: please see "Steps to reproduce" section below
Compiler and options: Apple clang version 14.0.0 (clang-1400.0.29.202), Xcode 14.2 (14C18), SDK: `MacOSX13.1.sdk`

### Expected behavior

Compilation should work with `MBEDTLS_USE_PSA_CRYPTO` set, regardless of `MBEDTLS_DHM_C` being set or unset.

### Actual behavior

Build fails with following output:
```
[105/118] Building C object library/CMakeFiles/mbedtls.dir/ssl_tls12_server.c.o
FAILED: library/CMakeFiles/mbedtls.dir/ssl_tls12_server.c.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I../include -I../library -Ilibrary -I../3rdparty/everest/include -I../3rdparty/p256-m -I../3rdparty/p256-m/p256-m -arch x86_64 -mmacosx-version-min=10.11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Ofast -fPIC -fvisibility=hidden -ffunction-sections -fdata-sections -Wall -Wextra -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wvla -Wformat=2 -Wno-format-nonliteral -Werror -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.11 -std=c99 -MD -MT library/CMakeFiles/mbedtls.dir/ssl_tls12_server.c.o -MF library/CMakeFiles/mbedtls.dir/ssl_tls12_server.c.o.d -o library/CMakeFiles/mbedtls.dir/ssl_tls12_server.c.o -c ../library/ssl_tls12_server.c
../library/ssl_tls12_server.c:3949:25: error: result of comparison of constant 528 with expression of type 'uint8_t' (aka 'unsigned char') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
        if (ecpoint_len > sizeof(handshake->xxdh_psa_peerkey)) {
            ~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Steps to reproduce

1. Clone repo and checkout `development` or `mbedtls-3.6` branch
2. Set custom config:
  ```
  # Run in Terminal inside the repo folder:
  scripts/config.pl unset MBEDTLS_DHM_C && \
  scripts/config.pl unset MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED && \
  scripts/config.pl unset MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED && \
  scripts/config.pl set MBEDTLS_USE_PSA_CRYPTO
  ```
3. Build `release` using CMake

### Additional information

I've already created a working local patch and the PR will follow soon.

### PR DESCRIPTION
**Pull request by misch7**
## Description

Fix two build issues related to custom configs:
- Fix #9186
- Fix #9188

Also fix additional build issues with sample programs and test suites caused by introducing `-Wmissing-prototypes`

See also https://github.com/Mbed-TLS/mbedtls-framework/pull/23

## PR checklist

- [x] **changelog** provided
- [x] **development PR** provided
- [x] **framework PR** provided https://github.com/Mbed-TLS/mbedtls-framework/pull/23
- [x] **3.6 PR** provided #9451
- [x] **2.28 PR**  not required because: neither issue is present in 2.28 (#9186: no build failure in the given configuration and compilers; #9188: moot since PSA did not support DHM yet)
- **tests**  provided. Some more CI coverage required, added `-Wmissing-prototypes` to `all.sh`

### CODE REVIEW

File: library/ssl_tls12_server.c [hunk 1]
```diff
@@ -3946,7 +3946,7 @@ static int ssl_parse_client_key_exchange(mbedtls_ssl_context *ssl)
            The size of the array is thus greater than 256 bytes which is greater than any
            possible value of ecpoint_len (type uint8_t) and the check below can be skipped.*/
```
Comment (gilles-peskine-arm) [inline library/ssl_tls12_server.c:3947]: When FFDH is disabled but RSA is enabled, `sizeof(handshake->xxdh_psa_peerkey)` is also greater than 256 bytes (assuming a sensible maximum RSA key size — if I got the math right, setting `PSA_VENDOR_RSA_MAX_KEY_BITS` to 1912 or less would result in ≤255 bytes for `sizeof(handshake->xxdh_psa_peerkey)` which is `PSA_EXPORT_PUBLIC_KEY_MAX_SIZE`).

This doesn't need to be the case, since RSA is irrelevant to what's stored in `xxdh_psa_peerkey`, but the size of the array is declared as `PSA_EXPORT_PUBLIC_KEY_MAX_SIZE` and not as max(max FFDH public key size, max ECC public key size).

Skipping this check when FFDH is disabled was done in 24e50d3dbdd1893364c241c179dbf182f2bf9413 to silence this compiler warning. We could broaden the skip to whenever the buffer is larger than `UINT8_MAX`. But I don't like the way this is done: I'd prefer to let compilers figure out if the comparison is always true and optimize the branch out. Evidently Clang, at least, figures it out.

I'd like a second opinion from another Mbed TLS maintainer on the preferred fix here.

File: library/ssl_tls12_server.c [hunk 2]
```diff
@@ -3946,7 +3946,7 @@ static int ssl_parse_client_key_exchange(mbedtls_ssl_context *ssl)
...
 #if !defined(PSA_WANT_ALG_FFDH)
-        if (ecpoint_len > sizeof(handshake->xxdh_psa_peerkey)) {
+        if ((size_t) ecpoint_len > sizeof(handshake->xxdh_psa_peerkey)) {
```
Comment (gilles-peskine-arm) [inline library/ssl_tls12_server.c:3949]: There is a similar piece of code in `ssl_parse_server_ecdh_params` in `ssl_tls12_client.c` which had the same problem. We fixed it in 7910cdd47fab98e29af6a1c6c7a4730f4ece8a58 by making `ecpoint_len` have the type `size_t`. This was needed for GCC, where casting `ecpoint_len` in the comparison expression isn't enough to disable the warning. So I think we should do the same here.

File: library/ssl_misc.h [hunk 3]
```diff
@@ -1507,7 +1507,7 @@ int mbedtls_ssl_psk_derive_premaster(mbedtls_ssl_context *ssl,
 #endif /* MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED */
```
Comment (gilles-peskine-arm) [inline library/ssl_misc.h:1508]: Please add [changelog entries](https://github.com/Mbed-TLS/mbedtls/blob/development/ChangeLog.d/00README.md) for the bug fixes.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Thanks for raising and fixing these issues!

For bug fixes, we want to have a changelog entry and, when feasible, a non-regression test. Here the non-regression test is to up the warning level in a CI build, and add a configuration but [I'm not sure what configuration yet](https://github.com/Mbed-TLS/mbedtls/issues/9188#issuecomment-2134029177), I'll think about it.

File: library/ssl_misc.h [hunk 4]
```diff
@@ -1507,7 +1507,7 @@ int mbedtls_ssl_psk_derive_premaster(mbedtls_ssl_context *ssl,
...
 
 #if defined(MBEDTLS_SSL_HANDSHAKE_WITH_PSK_ENABLED)
-#if defined(MBEDTLS_SSL_CLI_C)
+#if defined(MBEDTLS_SSL_CLI_C) || defined(MBEDTLS_SSL_SRV_C)
```
[the remark this answers is not in the document]
Comment (misch7) [reply library/ssl_misc.h:1510]: Done in 5a13c71

File: library/ssl_misc.h (hunk 3 above)
Comment (misch7) [reply library/ssl_misc.h:1508]: Done in 4d0b847. Please let me know in case you'd like some changes there.

File: library/ssl_tls12_server.c (hunk 2 above)
Comment (misch7) [reply library/ssl_tls12_server.c]: Good point, I should have done some digging there. It would have been too easy ^^ Done in 586dcd9

File: library/ssl_tls12_server.c (hunk 1 above)
Comment (misch7) [reply library/ssl_tls12_server.c]: Thanks for the explanation. It's interesting to learn a bit about the internals of the library. Without knowing all the implications, I'd in general prefer as well to let compilers figure out the comparison. This already came in handy here with Clang forcing me to look at potential mistakes without letting them slip through.

**Comment by misch7** [comment]
> Thanks for raising and fixing these issues!
> 
> For bug fixes, we want to have a changelog entry and, when feasible, a non-regression test. Here the non-regression test is to up the warning level in a CI build, and add a configuration but [I'm not sure what configuration yet](https://github.com/Mbed-TLS/mbedtls/issues/9188#issuecomment-2134029177), I'll think about it.

Thanks for the fast review and detailed explanation!

I'd also advocate for adding a configuration even if it's notably hard to cover all scenarios.

File: tests/scripts/all.sh [hunk 5]
```diff
@@ -4385,14 +4385,14 @@ component_build_no_ssl_srv () {
...
-    make CC=gcc CFLAGS='-Werror -Wall -Wextra -O1'
+    make CC=gcc CFLAGS='-Werror -Wall -Wextra -O1 -Wmissing-prototypes'
 }
 
 component_build_no_ssl_cli () {
     msg "build: full config except SSL client, make, gcc" # ~ 30s
     scripts/config.py full
     scripts/config.py unset MBEDTLS_SSL_CLI_C
-    make CC=gcc CFLAGS='-Werror -Wall -Wextra -O1'
+    make CC=gcc CFLAGS='-Werror -Wall -Wextra -O1 -Wmissing-prototypes'
```
Comment (gilles-peskine-arm) [inline tests/scripts/all.sh:4395]: This [reveals another missing-prototype error](https://mbedtls.trustedfirmware.org/job/mbed-tls-pr-head/job/PR-9189-head/4/execution/node/2335/log/):
```
  CC    src/asn1_helpers.c
src/asn1_helpers.c:18:5: error: no previous prototype for 'mbedtls_test_asn1_skip_integer' [-Werror=missing-prototypes]
 int mbedtls_test_asn1_skip_integer(unsigned char **p, const unsigned char *end,
```

Please add the missing `#include`.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Thanks for the update! Looks good to me, except that adding `-Wmissing-prototypes` causes another warning, looking like a missing `#include`. Please fix that one as well since the CI is now failing.

We're still missing a non-regression test for the no-DHM configuration, but that's a [more general issue in our testing](https://github.com/Mbed-TLS/mbedtls/issues/9197) for which we need to do a bit of design, so please don't bother with that one, we're going to discuss and resolve it internally.

File: tests/scripts/all.sh (hunk 5 above)
Comment (gilles-peskine-arm) [reply tests/scripts/all.sh:4395]: Sorry, building that file allows the build to progress to another file with errors:

```
src/test_helpers/ssl_helpers.c:950:5: error: no previous prototype for ‘mbedtls_ssl_write_fragment’ [-Werror=missing-prototypes]
  950 | int mbedtls_ssl_write_fragment(mbedtls_ssl_context *ssl,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/test_helpers/ssl_helpers.c:997:5: error: no previous prototype for ‘mbedtls_ssl_read_fragment’ [-Werror=missing-prototypes]
  997 | int mbedtls_ssl_read_fragment(mbedtls_ssl_context *ssl,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
```

You can test locally by running
```
tests/scripts/all.sh -k build_no_ssl_srv build_no_ssl_cli
```

Comment (misch7) [reply tests/scripts/all.sh:4395]: > Sorry, building that file allows the build to progress to another file with errors:
> 

Well, at least that's worth it 😂

> 
> You can test locally by running
> 
> ```
> tests/scripts/all.sh -k build_no_ssl_srv build_no_ssl_cli
> ```

Ah thanks! I was just asking that myself right away, so I could avoid flooding the CI :-)

Comment (misch7) [reply tests/scripts/all.sh:4395]: Okay, after installing a few missing Python plugins the scripts were working and this time the whole two prototypes were completely missing; At least a little variety twist ^^

But as a reward I received a few dozen more prototype errors:
```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

I'll look at them later so don't hold your breath for now ;-)

Comment (misch7) [reply tests/scripts/all.sh:4395]: Turns out we unleashed prototype-hell ^^

Tuning `-ferror-limit=0` revealed 46+ prototype errors and consequently fixing them (and their follow-ups) just slightly inflated this PR.
Most of them were in `tests/suites` and I first considered implementing automatic `static`-prefix generation in `generate_test_code.py`. While browsing the `function` files  I noticed that there already was a mixture of static and non-static functions with different return types. So I went for the explicit way and changed all functions there. I think this is also the better approach for keeping the code clear (instead of having to guess what the generator script does).
However I also had to modify the script to generate static wrapper functions and identify existing static functions. Also refactored some stuff to satisfy the compiler (and the reader alike) in the sample programs where it felt appropriate.

Finally the only remaining error was triggered by the unused function `ecjpake_operation_setup` in `test_suite_psa_crypto.function` for which I took the liberty of commenting it out, since it is not referenced anywhere in the whole codebase.

If you agree with the recent modifications, do we need an additional changelog entry? And would you like me to add  `-ferror-limit=0` to `component_build_no_ssl_srv` and `component_build_no_ssl_cli` in `all.sh`?

File: tests/suites/test_suite_psa_crypto.function [hunk 6]
```diff
@@ -40,11 +40,14 @@
 #define ASSERT_OPERATION_IS_INACTIVE(operation) TEST_ASSERT(operation.id == 0)
 
 #if defined(PSA_WANT_ALG_JPAKE)
-int ecjpake_operation_setup(psa_pake_operation_t *operation,
-                            psa_pake_cipher_suite_t *cipher_suite,
-                            psa_pake_role_t role,
-                            mbedtls_svc_key_id_t key,
-                            size_t key_available)
+/**
+ * TODO: This function is currently unused. What shall we do with it?
```
Comment (gilles-peskine-arm) [inline tests/suites/test_suite_psa_crypto.function:44]: Please remove it. We have git for the history.

File: tests/scripts/all.sh [hunk 7]
```diff
@@ -4385,14 +4385,14 @@ component_build_no_ssl_srv () {
     msg "build: full config except SSL server, make, gcc" # ~ 30s
     scripts/config.py full
     scripts/config.py unset MBEDTLS_SSL_SRV_C
-    make CC=gcc CFLAGS='-Werror -Wall -Wextra -O1'
+    make CC=gcc CFLAGS='-Werror -Wall -Wextra -O1 -Wmissing-prototypes'
 }
```
Comment (gilles-peskine-arm) [inline tests/scripts/all.sh:4389]: We're currently passing `-Wmissing-prototypes` when building with CMake, but only inside `library`. Please move the corresponding clauses from `library/CMakeLists.txt` to the toplevel cmakelists.

File: tests/scripts/all.sh (hunk 5 above)
Comment (gilles-peskine-arm) [reply tests/scripts/all.sh:4395]: No, please don't add `-ferror-limit=0`. That's rarely useful: typically, when there are so many errors, it means the compiler is completely out of synch from what the programmer thought. We wouldn't want to generate GB worth of CI logs.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Wow, I didn't expect this many changes! But thanks for following through. Note, if it wasn't for #9218, I'd say it isn't worth it to fiddle with `tests/*`. But if there's a concrete problem with building the unit tests on NuttX, then it's worth making it possible.

I'm afraid I'm going to request that you please force-push a new history that does not add `static` to test case functions, i.e. the lines after `BEGIN_CASE` in `*.function`. Requiring `static` there is just noise. Also, please avoid rewrapping lines in the same commit: that makes the commits hard to review. For reviewing, I'd like the additions of `static` to disappear in

```
git log -p -w dev..HEAD | perl -0777 -pe 's/-(.*\n)\+static \1//gm; s/^@.*\n(?: .*\n)*(?=@|diff|\Z)//gm; s/^diff.*\nindex.*\n--- .*\n\+\+\+ .*\n(?=\Z|diff |commit )//gm' | colordiff | less -R
```

so that we can focus on what else is happening.

File: tests/src/asn1_helpers.c [hunk 8]
```diff
@@ -15,6 +15,8 @@
 
 #include <mbedtls/asn1.h>
 
+#include <test/asn1_helpers.h>
```
Comment (gilles-peskine-arm) [inline tests/src/asn1_helpers.c:18]: Also, for a change of this magnitude, I think we need a 2.28 backport as well, just for the parts that backport cleanly. I don't particularly care to pass `-Wmissing-prototypes` in 2.28, but I want backporting changes to tests to remain easy when it's currently a simple cherry-pick. For parts that are already different, it doesn't matter.

File: tests/suites/test_suite_psa_crypto.function (hunk 6 above)
Comment (misch7) [reply tests/suites/test_suite_psa_crypto.function]: Done in a9d40d7

File: tests/scripts/generate_test_code.py [hunk 9]
```diff
@@ -200,7 +200,7 @@
 CONDITION_REGEX = r'({})(?:\s*({})\s*({}))?$'.format(C_IDENTIFIER_REGEX,
                                                      CONDITION_OPERATOR_REGEX,
                                                      CONDITION_VALUE_REGEX)
-TEST_FUNCTION_VALIDATION_REGEX = r'\s*void\s+(?P<func_name>\w+)\s*\('
+TEST_FUNCTION_VALIDATION_REGEX = r'\s*static\s*void\s+(?P<func_name>\w+)\s*\('
```
[the remark this answers is not in the document]
Comment (misch7) [reply tests/scripts/generate_test_code.py]: Done in 9871937

File: tests/src/asn1_helpers.c (hunk 8 above)
Comment (misch7) [reply tests/src/asn1_helpers.c:18]: Who shall do the backporting?

File: tests/scripts/all.sh (hunk 7 above)
Comment (misch7) [reply tests/scripts/all.sh:4389]: Just to be sure, do you only refer to the `-Wmissing-prototypes` clauses within these lines:

- From GCC:
  https://github.com/Mbed-TLS/mbedtls/blob/98ffc8e7c30a8a3aa6d688e416d299567b4deb9c/library/CMakeLists.txt#L200
- From Clang:
  https://github.com/Mbed-TLS/mbedtls/blob/98ffc8e7c30a8a3aa6d688e416d299567b4deb9c/library/CMakeLists.txt#L204

...to be moved to these lines:

- To GCC:
  https://github.com/Mbed-TLS/mbedtls/blob/98ffc8e7c30a8a3aa6d688e416d299567b4deb9c/CMakeLists.txt#L199
- To Clang:
  https://github.com/Mbed-TLS/mbedtls/blob/98ffc8e7c30a8a3aa6d688e416d299567b4deb9c/CMakeLists.txt#L233

...or all / other specific clauses from the original lines?

And are the target lines correct?

File: tests/src/asn1_helpers.c (hunk 8 above)
Comment (gilles-peskine-arm) [reply tests/src/asn1_helpers.c:18]: Ideally you, after the main pull request is approved. But if we've exhausted your bandwidth someone else will deal with it, it just might take more time.

File: tests/scripts/all.sh (hunk 7 above)
Comment (gilles-peskine-arm) [reply tests/scripts/all.sh:4389]: Just moving `-Wmissing-prototypes`, not the other `-W`. I think the target lines are correct, or maybe the GCC line needs to be in a version-based conditional, I don't know when `-Wmissing-prototypes` was introduces.

Comment (misch7) [reply tests/scripts/all.sh:4389]: Ok, thanks.

Meanwhile I've dug a bit and the oldest reference I could find in GCC's repo is from 1999:
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=fe50c0eb3bcd01019e3b8e610b3906510a5d4b8e

That's from version `2.96 19991014`:
https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/version.c;h=2c4f8fbc6ca55f810c8c8e306cee5895e9ae3eae;hb=fe50c0eb3bcd01019e3b8e610b3906510a5d4b8e

So I guess given the age and that it worked in `library` all the time, we can safely assume that it will work.

File: tests/src/asn1_helpers.c (hunk 8 above)
Comment (misch7) [reply tests/src/asn1_helpers.c:18]: Ok, I'm happy to do it.

File: tests/scripts/all.sh (hunk 7 above)
Comment (misch7) [reply tests/scripts/all.sh:4389]: Done in d74b452

I've just seen that the previous CI job failed with:
```
tests/suites/test_suite_ctr_drbg.function:99:14: error: unused function 'thread_random_function' [-Werror,-Wunused-function]
```

Guess I have to figure out a way to build exactly the same locally.

Comment (misch7) [reply tests/scripts/all.sh:4389]: So I've managed to reproduce the CI failure by calling what I scrapped from the logs:

`tests/scripts/all.sh --seed 4 --keep-going test_cmake_out_of_source`

Before I ran into the same issue as the CI did, a few more errors were raised on each run:

```
tests/src/drivers/platform_builtin_keys.c:59:14: error: no previous prototype for function 'mbedtls_psa_platform_get_builtin_key'
```

And after making the former function `static`, two `unused` errors occurred:
```
tests/src/drivers/platform_builtin_keys.c:59:21: error: unused function 'mbedtls_psa_platform_get_builtin_key'
tests/src/drivers/platform_builtin_keys.c:26:52: error: unused variable 'builtin_keys'
```

When temporarily commenting those out, I finally ran into the same error as the CI did:

```
tests/suites/test_suite_ctr_drbg.function:99:14: error: unused function 'thread_random_function'
```

Which is actually not true, because `grep` revealed that `thread_random_function` is used within the same file at line 402. It's apparently hard to figure it out for the compiler because it is being used in the `TEST_EQUAL` macro:

https://github.com/Mbed-TLS/mbedtls/blob/7777cb7efc29535e84bf54fae32fe4fb8f74ba23/tests/suites/test_suite_ctr_drbg.function#L399-L404

My suggestion would be to make `thread_random_function` a regular function again and add its prototype directly in the line 99 above the definition:

https://github.com/Mbed-TLS/mbedtls/blob/7777cb7efc29535e84bf54fae32fe4fb8f74ba23/tests/suites/test_suite_ctr_drbg.function#L99

The build and all tests successfully passed, once I did this locally and deleted the unused file `tests/src/drivers/platform_builtin_keys.c` as well :)

Shall I proceed as proposed?

I'm not quite sure because of possible implications of `mbedtls_psa_platform_get_builtin_key` being referenced here when `MBEDTLS_PSA_CRYPTO_BUILTIN_KEYS ` is enabled (which is disabled by default):

https://github.com/Mbed-TLS/mbedtls/blob/7777cb7efc29535e84bf54fae32fe4fb8f74ba23/tests/src/psa_test_wrappers.c#L29-L39

https://github.com/Mbed-TLS/mbedtls/blob/7777cb7efc29535e84bf54fae32fe4fb8f74ba23/include/mbedtls/mbedtls_config.h#L1325-L1341

Comment (gilles-peskine-arm) [reply tests/scripts/all.sh:4389]: `thread_random_function` is defined unconditionally but only used under certain conditions: `TEST_CASE depends_on:MBEDTLS_THREADING_PTHREAD:!MBEDTLS_CTR_DRBG_USE_128_BIT_KEY:!MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH` means
```
#if defined(MBEDTLS_THREADING_PTHREAD) && !defined(MBEDTLS_CTR_DRBG_USE_128_BIT_KEY) && !defined(MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH)
```

(I'm not sure why it's 128-bit-AES only.) Either the function needs to remain non-static and to have a prototype, or its definition needs to have a matching guard.

As for `mbedtls_psa_platform_get_builtin_key`, it's used when building tests in configurations with `MBEDTLS_PSA_CRYPTO_BUILTIN_KEYS` enabled, such as the configuration obtained with `scripts/config.py full`.

Comment (misch7) [reply tests/scripts/all.sh:4389]: Thanks for the clarification, done in 815f555

Now the build should pass and we are ready for review.

**Comment by gilles-peskine-arm** [comment]
I'm afraid there's a merge conflict now, so I must ask you to please rebase again.

**Comment by misch7** [comment]
> I'm afraid there's a merge conflict now, so I must ask you to please rebase again.

Done, that should do it in conjunction with https://github.com/Mbed-TLS/mbedtls-framework/pull/23

I assume we have to merge the `framework` PR first, so I can add the corresponding submodule commit here?

**Comment by gilles-peskine-arm** [comment]
Please update the submodule to the head of the PR in the framework repository, so that we can run the CI with the updated submodule.

When we merge the framework PR, we'll need a final update to this PR to update the submodule to the result of the merge.

**Comment by misch7** [comment]
> Update the submodule to the head of PR in the framework repository (f…

Ok, done.

**Comment by misch7** [comment]
The recent commits address the errors of the [failed CI jobs](https://mbedtls.trustedfirmware.org/job/mbed-tls-pr-head/job/PR-9189-head/16/display/redirect) of commit a680204.

I've spun up a local Docker CI container and successfully tested these previously failed `test` jobs of `all.sh`:

```
build_arm_linux_gnueabi_gcc_arm5vte
build_crypto_default
build_crypto_full
build_no_pk_rsa_alt_support
check_test_helpers
full_no_pkparse_pkwrite
test_crypto_for_psa_service
test_crypto_full_md_light_only
test_ctr_drbg_aes_128_sha_256
test_ctr_drbg_aes_128_sha_512
test_ctr_drbg_aes_256_sha_256
test_depends_py_cipher_id
test_depends_py_cipher_id_psa
test_depends_py_hashes

test_have_int32_cmake_new_bignum

test_ref_configs

check_code_style
```

Since the remaining jobs have just recurring errors, we should see more green lights with the next run.

I also had to add https://github.com/Mbed-TLS/mbedtls-framework/pull/23/commits/31b66dc7d8297d2ba287aa9b53e57ea6bd06bf26 to satisfy the unit tests for `generate_test_code.py`.

**Comment by misch7** [comment]
00e2ad4 should fix the remaining errors of the last 3 failed CI jobs.

c5f3b61 fixes an additional error that occurred when I ran `test_no_platform` on macOS:

```
test/metatest.c:131:34: error: format specifies type 'void *' but the argument has type 'volatile char *' [-Werror,-Wformat-pedantic]
    mbedtls_printf("%p -> %u\n", p, (unsigned) *p);
                    ~~           ^
                    %s
```

**Comment by misch7** [comment]
Finally the CI gives green light :-)

I'm curious, what do the internal CI jobs do?

**Comment by davidhorstmann-arm** [comment]
> I'm curious, what do the internal CI jobs do?

Currently the CI is replicated - the Internal and TF OpenCI jobs are duplicates of each other.

**Comment by misch7** [comment]
Thanks @davidhorstmann-arm and @gilles-peskine-arm for the info :-)

Shall I rebase this PR once the other PR in `framework` is merged? Ideally I'd like to do this anyway, so I could squash some commits.
Or would you prefer another quick rebase now for the CI jobs?

**Comment by gilles-peskine-arm** [comment]
The fix has already been merged (it's #9200, right @davidhorstmann-arm ?). I haven't started a proper review yet, so please rebase now, and feel free to reorganize commits.

**Comment by misch7** [comment]
> > I haven't started a proper review yet, so please rebase now, and feel free to reorganize commits.
> 
> Ok, thanks @gilles-peskine-arm. I get back to you when it's done.

Done and ready for CI & review @gilles-peskine-arm :-)

**Comment by davidhorstmann-arm** [comment]
@misch7 I've pushed a copy of Mbed-TLS/mbedtls-framework#23 to the main framework repository. This is required because at present our CI can't check out the framework commit from your fork.

Hopefully this will be fixed in future but for this PR just manually pushing a copy has worked around it.

**Comment by misch7** [comment]
> @misch7 I've pushed a copy of [Mbed-TLS/mbedtls-framework#23](https://github.com/Mbed-TLS/mbedtls-framework/pull/23) to the main framework repository. This is required because at present our CI can't check out the framework commit from your fork.
> 
> Hopefully this will be fixed in future but for this PR just manually pushing a copy has worked around it.

@davidhorstmann-arm Thanks for letting me know. Where do I find it? Can't see anything yet in the history or PR's yet.

I assume your push will allow the previously failed internal CI builds to succeed (with the original commit hash)?
Or do I need to update the submodule commit hash in this PR here as well?

**Comment by misch7** [comment]
> 
> I've just pushed it to a branch [here](https://github.com/Mbed-TLS/mbedtls-framework/tree/dev/external-contrib-copy/mbedtls-pr-9189), which is enough for CI to pick it up.
> 

> 
> I've restarted the CI jobs that are affected, and yes they should just succeed now (all being well!), no other input needed

Ok, cool. Thanks! @davidhorstmann-arm  :)

**Review by minosgalanakis — COMMENTED** [review]
Looks good overall. There is a minor conflict which is caused by the renaming of `MBEDTLS_PSA_CRYPTO_C` to `MBEDTLS_PSA_CRYPTO_CLIENT` in [test_suite_pk.function](https://github.com/Mbed-TLS/mbedtls/blob/10462d918420aba5d73ed3953f289e72d34044b5/tests/suites/test_suite_pk.function#L222)

Could you please rebase it and resolve it so it looks like that?

~~~~~
#if defined(MBEDTLS_PSA_CRYPTO_CLIENT)
static psa_status_t pk_psa_import_key(const unsigned char *key_data, size_t key_len,
                               psa_key_type_t type, psa_key_usage_t usage,
                               psa_algorithm_t alg, mbedtls_svc_key_id_t *key)
~~~~~~

No other conflicts other than updating the framework PR pointer, which you will have to do to address my comments there. I have verified that pr locally.

Happy to approve once conflict has been resolved.

**Comment by misch7** [comment]
@minosgalanakis Thanks for looking into this. I've resolved the conflicts as requested and also left a comment in the `framework` repo after running some tests with the suggested changes.

File: tests/suites/test_suite_x509write.function [hunk 10]
```diff
@@ -10,27 +10,31 @@
...
 #include "mbedtls/psa_util.h"
 
-#if defined(MBEDTLS_RSA_C)
-int mbedtls_rsa_decrypt_func(void *ctx, size_t *olen,
-                             const unsigned char *input, unsigned char *output,
-                             size_t output_max_len)
+#if defined(MBEDTLS_PEM_WRITE_C) && \
+    defined(MBEDTLS_X509_CRT_WRITE_C) && \
+    defined(MBEDTLS_X509_CRT_PARSE_C) && \
+    defined(MBEDTLS_MD_CAN_SHA1) && \
```
Comment (gilles-peskine-arm) [inline tests/suites/test_suite_x509write.function:16]: Note: we have ongoing work to change certain dependency symbols inclduing `MBEDTLS_MD_CAN_SHA1` on the `development` branch, and this will cause a conflict. However the work for this particular symbol hasn't been scheduled yet AFAICT so hopefully this pull request will be merged before then.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Thank you very much for this massive code cleanup!

There's just one problem with the sample programs, other than that looks good to me.

File: programs/cipher/cipher_aead_demo.c [hunk 11]
```diff
@@ -198,7 +190,7 @@ static int aead_encrypt(mbedtls_cipher_context_t *ctx, size_t tag_len,
     p += tag_len;
 
     olen = p - out;
-    print_buf("out", out, olen);
+    mbedtls_test_print_buf("out", out, olen);
```
[the remark this answers is not in the document]
Comment (misch7) [reply programs/cipher/cipher_aead_demo.c]: > Thank you very much for this massive code cleanup!
> 

Glad I could help the project :-)

> So please keep the duplication of this function.

Done in 70e9b4b (and by 24a0908).

File: tests/suites/test_suite_x509write.function (hunk 10 above)
Comment (misch7) [reply tests/suites/test_suite_x509write.function:16]: Fingers crossed 😁

Regarding sample programs: I also noticed that some dependencies went of out sync with the messages provided by some programs, e.g.:

`MBEDTLS_CIPHER_C ` vs. `MBEDTLS_MD_C`:

https://github.com/Mbed-TLS/mbedtls/blob/24a0908eca5255059ba97e78f6f68cd391424e36/programs/cipher/cipher_aead_demo.c#L43-L50

`MBEDTLS_FS_IO` hint missing in `mbedtls_printf`:

https://github.com/Mbed-TLS/mbedtls/blob/24a0908eca5255059ba97e78f6f68cd391424e36/programs/ssl/ssl_server.c#L12-L23

There might be more, those are the ones I remember.

Quick idea coming to mind would be to test for each one alone and have dedicated `printf`'s for each one missing. This would of course add more lines per sample.

**Review by gilles-peskine-arm — APPROVED** [review]
Thanks for the update! Looks good to me.

File: tests/suites/test_suite_x509write.function (hunk 10 above)
Comment (gilles-peskine-arm) [reply tests/suites/test_suite_x509write.function:16]: > I also noticed that some dependencies went of out sync with the messages provided by some programs

Yes, that definitely could use improvement..

> test for each one alone and have dedicated printf's for each one missing

Yes, that would be better.

Both are low-priority concerns though, so I can't guarantee that we would do or review such a change promptly.

**Review by minosgalanakis — APPROVED** [review]
LGTM

**Comment by gilles-peskine-arm** [comment]
Would you mind backporting the changes to the `mbedtls-3.6` and `mbedtls-2.28` branches?

The changes don't necessarily need to be complete. In particular, for 2.28, which will be retired at the end of 2024, I think we shouldn't change build scripts. Primarily, the goal of the backport would be that if the code in development is already identical with the older branch, we want it to remain identical, so that when we do bug fixes later, we don't run into conflicts due to `static` being missing.

File: tests/suites/test_suite_x509write.function (hunk 10 above)
Comment (misch7) [reply tests/suites/test_suite_x509write.function:16]: Ok, good to know you agree, so effort spent wisely :-)

No problem, I will have to look into that when I find the time as well.

**Comment by misch7** [comment]
> Would you mind backporting the changes to the `mbedtls-3.6` and `mbedtls-2.28` branches?
> 

Thank you both for the review. I'll happily do the backporting then.

And thanks for the details provided, this will be helpful.

**Comment by minosgalanakis** [comment]
@misch7 I believe the conflict is caused by #9394 moving the test files you are modifying.

`tests/suites/test_suite_XXX.function → ...tests/suites/test_suite_XXX.function`

**Comment by misch7** [comment]
> @misch7 I believe the conflict is caused by #9394 moving the test files you are modifying.
> 
> `tests/suites/test_suite_XXX.function → ...tests/suites/test_suite_XXX.function`

@minosgalanakis Yes seems like, since I didn't have to resolve any code during the rebase :-)

The new `framework` PR pointer has been updated as well.

**Comment by misch7** [comment]
Damn the build fails now, e.g. when I run:

`tests/scripts/all.sh -k build_no_ssl_srv build_no_ssl_cli`

...it fails with:

```
make[1]: *** No rule to make target `test_suite_bignum.generated.c', needed by `test_suite_bignum.generated'.  Stop.
make: *** [tests] Error 2
```

I've tested and verified that this is also the case for the current `development` HEAD f938f4ff on which I just rebased.

Any quick guess while I'm trying to resolve the issue? ^^

**Comment by misch7** [comment]
> `tests/scripts/all.sh -k build_no_ssl_srv build_no_ssl_cli`
> 

Update: Tested e7fdfdb9 builds just fine (last commit prior #9394).

I suspected that the failing build might be caused by older files in these `suites` folders:
```
tests/suites/
tf-psa-crypto/tests/suites/
```

So after deleting these folders and checking them out again, the build now fails with the following output:

```
  Gen   ../tf-psa-crypto/tests/test_suite_config.crypto_combinations.c
  Gen   ../tf-psa-crypto/tests/test_suite_config.psa_combinations.c
  Gen   ../tf-psa-crypto/tests/test_suite_constant_time.c
  Gen   ../tf-psa-crypto/tests/test_suite_constant_time_hmac.c
  Gen   ../tf-psa-crypto/tests/test_suite_ctr_drbg.c
Traceback (most recent call last):
  File "mbedtls/tests/../framework/scripts/generate_test_code.py", line 1277, in <module>
    main()
  File "mbedtls/tests/../framework/scripts/generate_test_code.py", line 1268, in main
    generate_code(funcs_file=args.funcs_file, data_file=args.data_file,
  File "mbedtls/tests/../framework/scripts/generate_test_code.py", line 1190, in generate_code
    raise IOError("ERROR: %s [%s] not found!" % (name, path))
OSError: ERROR: Functions file [suites//tf-psa-crypto/tests/test_suite_config.function] not found!
make[1]: *** [../tf-psa-crypto/tests/test_suite_config.crypto_combinations.c] Error 1
make[1]: *** Waiting for unfinished jobs....
  Gen   ../tf-psa-crypto/tests/test_suite_des.c
Traceback (most recent call last):
  File "mbedtls/tests/../framework/scripts/generate_test_code.py", line 1277, in <module>
    main()
  File "mbedtls/tests/../framework/scripts/generate_test_code.py", line 1268, in main
    generate_code(funcs_file=args.funcs_file, data_file=args.data_file,
  File "mbedtls/tests/../framework/scripts/generate_test_code.py", line 1190, in generate_code
    raise IOError("ERROR: %s [%s] not found!" % (name, path))
OSError: ERROR: Functions file [suites//tf-psa-crypto/tests/test_suite_config.function] not found!
make[1]: *** [../tf-psa-crypto/tests/test_suite_config.psa_combinations.c] Error 1
make: *** [tests] Error 2
```

Without knowing much about Python, I assume the double-slash in `suites//tf-psa-crypto` to be the likely cause?

Perhaps running the CI and replicating build errors will shed some light.

**Comment by gilles-peskine-arm** [comment]
The error about `test_suite_bignum.generated.c` is probably because that file has moved, and you still have a build product in the old place which gets picked up by a wildcard in the makefile. Solution: a fresh checkout, or remove files listed by `git ls-files -o`.

I don't know about the error about `test_suite_config.psa_combinations.c`, but that's another file that moved. I can't reproduce it on my machine.

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM after rebase

**Comment by misch7** [comment]
> The error about `test_suite_bignum.generated.c` is probably because that file has moved, and you still have a build product in the old place which gets picked up by a wildcard in the makefile. Solution: a fresh checkout, or remove files listed by `git ls-files -o`.

Yeah thanks, that was what I suspected too and this error went away after checking out both fresh `suites` folders.

> I don't know about the error about `test_suite_config.psa_combinations.c`, but that's another file that moved. I can't reproduce it on my machine.

Weird because I just cloned the whole main repo again and started a fresh build of `tests/scripts/all.sh -k build_no_ssl_srv` with the current HEAD's of main and framework, resulting in the same recent Python failure.
The only thing I could think of - after starting over completely fresh - is some issue with `Python 3.12.3` running in `venv` on my `macOS` machine.

**Review by minosgalanakis — DISMISSED** [review]
LGTM

@misch7 For the 3.6 backport, you could potentially use the pre-rebase version of this branch, since the restructuring that hit us here, [is not backported](https://github.com/Mbed-TLS/mbedtls/pull/9419). 

@gilles-peskine-arm Do you think we could merge this and the framework PR before the backports are ready? They are less of a moving target?

**Comment by misch7** [comment]
@minosgalanakis Ok, thanks. Good that the CI passed.

**Comment by mpg** [comment]
Took the liberty of editing the description to use [github keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) linking to the issues this is fixing.

**Comment by minosgalanakis** [comment]
Hi @misch7 we have recently merged #8226 which was splitting all.sh to different components. 

Could you rebase your PR on top of latest development and you will have to modify/ammend the commit updating the `component_build_no_ssl_srv`, and `component_build_no_ssl_cli ` since they now reside in [components-configuration-tls.sh](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/components-configuration-tls.sh) ([component_build_no_ssl_srv](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/components-configuration-tls.sh#L243-L248),  [component_build_no_ssl_cli ](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/components-configuration-tls.sh#L250-L255))

I will be helping you with the backport since the same split is happening in 3.6 LTS branch #9444

**Comment by gilles-peskine-arm** [comment]
A merge might be easier to both prepare and review than a rebase. We're ok with merge commits in a pull request if they aren't too frequent. A conflict after approval is a typical condition where a merge tends to be easier on everyone.

**Comment by gilles-peskine-arm** [comment]
> A merge might be easier to both prepare and review than a rebase. We're ok with merge commits in a pull request if they aren't too frequent. A conflict after approval is a typical condition where a merge tends to be easier on everyone.

On second thoughts, after having rebasing my own PR with all.sh conflicts… No, a rebase is easier here. Applying the changes to a different file is the same amount of work either way, unless there are many commits changing the same lines in `all.sh`, which is not the case here. Reviewing a rebase is easy with `git range-diff`.

**Comment by minosgalanakis** [comment]
@misch7 Since I already did the conflict resolution for the rebase, I cherry picked the commit https://github.com/Mbed-TLS/mbedtls/pull/9189/commits/a368c8a9af782c78f66ab86c8ed08100254e225b on this branch and rebased. 

I hope that is ok. If CI is clear, I will be reviewing it at high priority.

**Review by eleuzi01 — APPROVED** [review]
LGTM, thanks!

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
The rebase 58e2ebc086436da9ddc1c9e9ceafb87d1d8f6934 → 9e52d157e83fc25a54b4e391dec941dca5bef098 looks good except that it's missing a commit to update the framework submodule.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by eleuzi01 — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
The CI is very unhappy. I don't know what's going on. A mismatch between the framework version and the main repo version? So maybe https://github.com/Mbed-TLS/mbedtls-framework/pull/23 needs to be rebased on top of the latest `main`?

**Comment by minosgalanakis** [comment]
> The CI is very unhappy. I don't know what's going on. A mismatch between the framework version and the main repo version? So maybe [Mbed-TLS/mbedtls-framework#23](https://github.com/Mbed-TLS/mbedtls-framework/pull/23) needs to be rebased on top of the latest `main`?

This is bizzare indeed. In the 3.6 which is pointing at the same framework branch it passes, so if I rebase I will have to re-kick that CI job too.

**Comment by misch7** [comment]
> @misch7 Since I already did the conflict resolution for the rebase, I cherry picked the commit [a368c8a](https://github.com/Mbed-TLS/mbedtls/commit/a368c8a9af782c78f66ab86c8ed08100254e225b) on this branch and rebased.
> 
> I hope that is ok. If CI is clear, I will be reviewing it at high priority.

@minosgalanakis Ok, thanks!

**Comment by misch7** [comment]
While testing the recent rebase locally, I apparently ran into the same issue as the CI did:

```
$ make clean
Traceback (most recent call last):
  File "mbedtls/tests/../framework/scripts/generate_config_tests.py", line 179, in <module>
    test_data_generation.main(sys.argv[1:], __doc__, ConfigTestGenerator)
  File "mbedtls/framework/scripts/mbedtls_framework/test_data_generation.py", line 204, in main
    generator = generator_class(options)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "mbedtls/tests/../framework/scripts/generate_config_tests.py", line 162, in __init__
    self.mbedtls_config = config.ConfigFile()
                          ^^^^^^^^^^^^^^^^^^^
TypeError: ConfigFile.__init__() missing 2 required positional arguments: 'default_path' and 'name'
```
The problem went away when built with the rebased `framework` commit: https://github.com/Mbed-TLS/mbedtls-framework/commit/6a1dc7daa9e861fb873dd4b9f13ebfbd6f82f6dc

Hence I pushed b77c419 - fingers crossed for the CI.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM after submodule update

**Review by eleuzi01 — APPROVED** [review]
LGTM, thanks!
