### PR TITLE
Fix error handling for secure element keys in `psa_start_key_creation`

### LINKED ISSUE #8537: Fix error handling for secure element keys in `psa_start_key_creation`
### Summary
Currently, when creating a key in a secure element the return value of `psa_copy_key_material_into_slot` is ignored. A consequence is that keys in a dynamic secure element may be reported as successfully created even if an out-of-memory failure occurs.

This can be fixed by handling the return value of this call.

### PR DESCRIPTION
**Pull request by Ryan-Everett-arm**
## Description
Add some error handling for the call to `psa_copy_key_material_into_slot` in `psa_start_key_creation`. Fixes #8537
## PR checklist
- [x] **changelog** provided
- [x] **3.6 backport** #9074
- [x] **backport** #8544
- [x] **tests** not required, we cannot test out of memory issues

### CODE REVIEW

File: ChangeLog.d/fix-secure-element-key-creation.txt [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Bugfix
+   * Fix the error handling in psa_start_key_creation so that
+     out of memory issues are properly handled. Fixes #8537.
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/fix-secure-element-key-creation.txt:3]: * The changelog entry should mention the fact that this is only a problem when a non-default option is enabled. 
* `psa_start_key_creation` is an internal function, so it is not meaningful in a changelog entry. Changelog entries are meant for library users.

Suggested wording:

> Fix error handling when creating a key in a dynamic secure element (feature enabled by MBEDTLS_PSA_CRYPTO_SE_C). In a low memory condition, the creation could return PSA_SUCCESS but using or destroying the key would not work. Fixes #8537.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
LGTM for the fix but not for the changelog entry.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by tom-daubney-arm — APPROVED** [review]
LGTM - thanks
