### PR TITLE
Fixed a bug that the little-endian Microblaze does not work when MBEDTLS_HAVE_ASM is defined

### LINKED ISSUE #2020: MicroBlaze does not return from mbedtls_pk_parse_key with MBEDTLS_HAVE_ASM defined
### Description
- Type: Bug 
- Priority:  Major 

---------------------------------------------------------------
## Bug

**OS**  
FreeRTOS

**mbed TLS build:**  
Version: 2.12.0
OS version: 10.0  
Configuration: 
[mbedtls_freertos.txt](https://github.com/ARMmbed/mbedtls/files/2391700/mbedtls_freertos.txt)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  GCC 7.2.0 from Xilinx SDK 2018.1. Compiled with: `-O2 -mcpu=v10.0 -mxl-multiply-high -mno-xl-soft-div -mno-xl-soft-mul -mxl-barrel-shift -mxl-pattern-compare`
Additional environment information:  we are also using Mongoose web server. The MicroBlaze has been built with multiplier and divider hardware, branch prediction, and data and instruction caches. 

**Expected behavior**   
When parsing a buffer with `mbedtls_pk_parse_key`, the function should return.

**Actual behavior**  
The `mbedtls_pk_parse_key` never returns, and is stuck performing the multiplication in bignum.c.

The function executes and returns correctly when compiling without MBEDTLS_HAVE_ASM defined. 

**Steps to reproduce**  
Attempt to parse a key with `mbedtls_pk_parse_key` on a MicroBlaze with MBEDTLS_HAVE_ASM defined.

### PR DESCRIPTION
**Pull request by Kazuyuki-Kimura**
Fixed a bug that the little-endian Microblaze does not work when MBEDTLS_HAVE_ASM is defined.

I accidentally closed #4586.... sorry.

Signed-off-by: Kazuyuki Kimura <kim@wing.ocn.ne.jp>

Fixes #2020

### CODE REVIEW

**Review by gilles-peskine-arm — COMMENTED** [review]
Makes sense to me. I haven't reviewed the code for any other similar issues. I have not run any tests (as you're undoubtedly aware of, we do not have any testing on Microblaze).

Since this is a bug fix, it needs a changelog entry. Can you please create a file `ChangeLog.d/bignum-little-endian-microblaze.txt` containing something like
```
Bugfix
   * Fix bignum multiplication (and therefore asymmetric cryptography) on
     little-endian Microblaze when MBEDTLS_HAVE_ASM is enabled. Fixes #2020.
```

**Review by daverodgman — CHANGES_REQUESTED** [review]
Please add a Changelog

**Comment by daverodgman** [comment]
This addresses the same issue as #5580 - although I think (but am not sure) that 5580 doesn't properly fix for both endiannesses, whereas this clearly has a code path for both big and little endian. So superficially it looks like this might be the preferred fix.

**Comment by daverodgman** [comment]
Rebased and Changelog added. @Kazuyuki-Kimura or @Eurecam-Benjamin please could you test and confirm that addresses the issue? Ideally we also need a 2.28 backport. Thanks.

**Comment by daverodgman** [comment]
Discussed in historical review; we agreed this is OK to merge without being able to properly test.

File: library/bn_mul.h [hunk 1]
```diff
@@ -566,10 +566,20 @@
...
+        "lhui  r8,   r3,   0    \n\t"
+#else
+#define MULADDC_LHUI                    \
         "lhui  r8,   r3,   0    \n\t"   \
         "addi  r3,   r3,   2    \n\t"   \
-        "lhui  r9,   r3,   0    \n\t"   \
+        "lhui  r9,   r3,   0    \n\t"
+#endif
+
+#define MULADDC_X1_CORE                    \
```
Comment (tom-cosgrove-arm) [inline library/bn_mul.h:581]: annoying that the trailing `\` doesn't line up, but ah well

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM
