### PR TITLE
Don't use lstrlenW() on Windows

### LINKED ISSUE #2994: UWP has no lstrlenW function
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Unable to compile means Blocker I guess, but the way to fix in a fork is pretty easy so maybe minor?

---------------------------------------------------------------
## Bug

**OS**  
Windows (Compiling for Windows Store)

**mbed TLS build:**  
Version: 2.19.1 (But same thing is still present in master)
OS version: 10.0.18362
Configuration: https://gist.github.com/borrrden/e9e01b5703c450e789c8b2566709c2af
Compiler and options:  MSVC 19.16.27034.0
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  ???

**Expected behavior**   

Compiles correctly

**Actual behavior**

Doesn't compile, no function definition for `lstrlenW`  (x509_crt.c)

**Steps to reproduce**  

Make a CMake build as in the following:

`cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION="10.0.16299.0"`

### PR DESCRIPTION
**Pull request by tom-cosgrove-arm**
The lstrlenW() function isn't available to UWP apps, and isn't necessary, since when given -1, `WideCharToMultiByte()` will process the terminating null character itself (and the length returned by the function includes this character).

Resolves #2994

## Gatekeeper checklist

- [x] **changelog** not required - there will be a final one to cover this PR (addresses #2994) and the next (to fully address the rest of #1227)
- [x] **backport** to follow
- [x] **tests** not required

### CODE REVIEW

File: library/x509_crt.c [hunk 1]
```diff
@@ -1449,8 +1449,8 @@ int mbedtls_x509_crt_parse_path(mbedtls_x509_crt *chain, const char *path)
         }
 
         w_ret = WideCharToMultiByte(CP_ACP, 0, file_data.cFileName,
-                                    lstrlenW(file_data.cFileName),
-                                    p, (int) len - 1,
```
Comment (tom-cosgrove-arm) [inline library/x509_crt.c:1453]: Previously, we passed in the number of characters excluding the terminating null character, and had filled the buffer with `0` bytes to ensure the output is null-terminated.

File: library/x509_crt.c [hunk 2]
```diff
@@ -1449,8 +1449,8 @@ int mbedtls_x509_crt_parse_path(mbedtls_x509_crt *chain, const char *path)
...
+                                    -1,
+                                    p, (int) len,
```
Comment (tom-cosgrove-arm) [inline library/x509_crt.c:1453]: With this change, `WideCharToMultiByte()` finds and processes the terminating null itself, and outputs it, so we can give it the full buffer (i.e. `len` rather than `len - 1`)

See https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte

**Review by daverodgman — APPROVED** [review]

**Comment by tom-cosgrove-arm** [comment]
This line was hit by code coverage; obviously that's not a through test though, but should be sufficient together with the documentation of the function's semantics

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM based on documentation
