### PR TITLE
Backport 3.6: test sample programs in ssl-opt.sh

### LINKED ISSUE #9072: ssl_client1 fails on TLS 1.3
### Summary
If I attempt to make a request to `https://api.sunrisesunset.io/json?lat=47.333&lng=13.333` using Postman, or a browser, it works perfectly.

However, when making an HTTP request using the mbedTLS sample client [ssl_client1.c](https://github.com/Mbed-TLS/mbedtls/blob/development/programs/ssl/ssl_client1.c) with these parameters:

```
#define SERVER_PORT "443"
#define SERVER_NAME "api.sunrisesunset.io"
#define GET_REQUEST "GET /json?lat=47.333&lng=13.333 HTTP/1.1\r\nHost: api.sunrisesunset.io\r\n\r\n"
```

I got the following error:

```
ssl_client.c:0042: client hello, adding server name extension: api.sunrisesunset.io
ssl_tls13_client.c:0057: client hello, adding supported versions extension
ssl_tls13_client.c:0080: supported version: [3:4]
ssl_tls13_client.c:0086: supported version: [3:3]
ssl_tls13_client.c:0572: no cookie to send; skip extension
ssl_tls13_client.c:0285: client hello: adding key share extension
ssl_tls13_generic.c:1651: Perform PSA-based ECDH/FFDH computation.
ssl_tls13_generic.c:1689: psa_generate_key() returned -27648 (-0x6c00)
ssl_client.c:1012: <= write client hello
ssl_tls.c:4617: <= handshake
 failed
  ! mbedtls_ssl_handshake returned -0x6c00

Last error was: -27648 - SSL - Internal error (eg, unexpected failure in lower-level module)
```

What is interesting is that when I force the mbedTLS to use TLS 1.2, instead TLS 1.3 by adding the following:

`mbedtls_ssl_conf_max_version(&conf, MBEDTLS_SSL_MAJOR_VERSION_3, MBEDTLS_SSL_MINOR_VERSION_3);  // Force TLS 1.2`

The request works perfectly! So, it indicates to me that there might be a problem with the TLS 1.3, somehow the server is not properly working with mbedTLS TLS 1.3.

### System information

Mbed TLS version (number or commit id): `2ca6c285a0dd3f33982dd57299012dacab1ff206`
Operating system and version: `macOS 13.2.1 (22D68)`
Configuration (if not default, please attach `mbedtls_config.h`): `default` 

### Expected behavior
The request should return a successful result.

### Actual behavior
The request is failing during the handshake as previously mentioned:
```
ssl_tls.c:4617: <= handshake
 failed
  ! mbedtls_ssl_handshake returned -0x6c00

Last error was: -27648 - SSL - Internal error (eg, unexpected failure in lower-level module)
```

### Steps to reproduce
Just change these configs on [ssl_client1.c](https://github.com/Mbed-TLS/mbedtls/blob/development/programs/ssl/ssl_client1.c) sample:

```
#define SERVER_PORT "443"
#define SERVER_NAME "api.sunrisesunset.io"
#define GET_REQUEST "GET /json?lat=47.333&lng=13.333 HTTP/1.1\r\nHost: api.sunrisesunset.io\r\n\r\n"
```

Then, rebuild and run that.

### Additional information
- It's working normally when calling from a browser, so it's not a server issue.
- It seems to be solved by forcing the usage of TLS 1.2, as previously mentioned:
`mbedtls_ssl_conf_max_version(&conf, MBEDTLS_SSL_MAJOR_VERSION_3, MBEDTLS_SSL_MINOR_VERSION_3);`

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Test the SSL sample programs (`ssl_client1`, `dtls_client`, `ssl_server`, `ssl_fork_server`, `ssl_pthread_server`, `dtls_server`) in `ssl-opt.sh`. Test against both GnuTLS and OpenSSL. Test with all relevant protocol versions (TLS 1.2/1.3; DTLS 1.2 only).

`mini_client` is excluded because it's complicated, see [this comment](https://github.com/Mbed-TLS/mbedtls/pull/9541#issuecomment-2344479846). It's also not part of the deliverable we want, which is primarily `ssl_client1` and `ssl_server` interoperabiliy with TLS 1.3, and secondarily (because that part is not much more effort) those programs and `dtls_client` and `dtls_server` with (D)TLS 1.2. (I'm still throwing in `ssl_pthread_server` and `ssl_fork_server` because they're really easy.)

The TLS 1.3 test cases are non-regression tests for https://github.com/Mbed-TLS/mbedtls/issues/9072 and https://github.com/Mbed-TLS/mbedtls/issues/8749.

Fixes #9072 in the sense that when this pull request passes the CI, it means the issue is fixed. (The actual fixes are in previous PR: #9501 and #9507.)

The sample programs hard-code port 4433, so these tests can't run concurrently. This may be a problem for CI reliability (although in principle it shouldn't be since each test run runs alone in a Docker instance). If it's a problem, the obvious solution is to make the port configurable in each program (and remove the forced-port hacks in `ssl-opt.sh`).

Prerequisites:

* [x] https://github.com/Mbed-TLS/mbedtls/pull/9546 — Sorting out the failures when some key exchanges are excluded got me into a nasty bag of worms around dependency calculations in `ssl-opt.sh` that warrants its own pull request.
* [x] https://github.com/Mbed-TLS/mbedtls/pull/9563 — fix middlebox compatibility mode, rather than figure out what depends on it and write alternative test cases when it's disabled.

## PR checklist

- [x] **changelog** not required because: test only. (I don't think the improvements in compile-time dependencies in sample programs warrant a changelog entry.)
- [x] **development PR** #9638 
- [x] **framework PR** not required
- [x] **3.6 PR** here
- [x] **2.28 PR** let's not bother given that there's likely going to be only one more 2.28.x release
- **tests**  provided

### CODE REVIEW

File: programs/ssl/ssl_fork_server.c [hunk 1]
```diff
@@ -9,22 +9,15 @@
...
 #include "mbedtls/platform.h"
 
-#if !defined(MBEDTLS_BIGNUM_C) || !defined(MBEDTLS_ENTROPY_C) ||          \
-    !defined(MBEDTLS_SSL_TLS_C) || !defined(MBEDTLS_SSL_SRV_C) ||         \
-    !defined(MBEDTLS_NET_C) || !defined(MBEDTLS_RSA_C) ||                 \
-    !defined(MBEDTLS_CTR_DRBG_C) || !defined(MBEDTLS_X509_CRT_PARSE_C) || \
-    !defined(MBEDTLS_TIMING_C) || !defined(MBEDTLS_FS_IO) ||              \
-    !defined(MBEDTLS_PEM_PARSE_C)
-int main(int argc, char *argv[])
+#if !defined(MBEDTLS_ENTROPY_C) || !defined(MBEDTLS_CTR_DRBG_C) ||      \
```
Comment (mpg) [inline programs/ssl/ssl_fork_server.c:12]: Not on this line: copy-pasta in the commit message, says pthread when it's about fork.

File: tests/opt-testcases/sample.sh [hunk 2]
```diff
@@ -27,9 +27,10 @@ run_test    "Sample: ssl_client1, gnutls server, TLS 1.2" \
             -C "error"
 
 requires_protocol_version tls13
+requires_openssl_tls1_3
```
Comment (mpg) [inline tests/opt-testcases/sample.sh:30]: Note: this is something that could be done automatically based on seeing `openssl` and `-tls1_3` in the command line. (Perhaps even automagically use `O_NEXT`, though perhaps that would be too much.)

Not insisting on it, as it's pre-existing.

File: tests/opt-testcases/sample.sh [hunk 3]
```diff
@@ -27,9 +27,10 @@ run_test    "Sample: ssl_client1, gnutls server, TLS 1.2" \
             -C "error"
 
 requires_protocol_version tls13
```
Comment (mpg) [inline tests/opt-testcases/sample.sh:29]: Looks like something we could auto-detect. (Pre-existing, so no change required.)

File: tests/opt-testcases/sample.sh [hunk 4]
```diff
@@ -38,9 +38,10 @@ run_test    "Sample: ssl_client1, openssl server, TLS 1.3" \
...
+requires_gnutls_tls1_3
```
Comment (mpg) [inline tests/opt-testcases/sample.sh:41]: Similar thoughts.

**Review by mpg — COMMENTED** [review]
Just a first pass, will make another when the pre-requisite is in, but looking pretty good to me so far!

File: tests/opt-testcases/sample.sh (hunk 2 above)
Comment (gilles-peskine-arm) [reply tests/opt-testcases/sample.sh:30]: I absolutely agree that more autodetection is desirable. But in this PR I want to avoid things that are likely to have an impact on other test cases. So another time.

File: programs/ssl/ssl_fork_server.c (hunk 1 above)
Comment (gilles-peskine-arm) [reply programs/ssl/ssl_fork_server.c:12]: Changed in my latest rebase.

Note that I intend more rebases. Both after https://github.com/Mbed-TLS/mbedtls/pull/9546 is merged, and also because my latest batch of commits has broken something (still puzzling out what).

File: tests/opt-testcases/sample.sh [hunk 5]
```diff
@@ -0,0 +1,534 @@
...
+            0 \
+            -s "Version: TLS1.2" \
+            -c "<TD>Protocol version:</TD><TD>TLS1.2</TD>" \
+            -S "Error" \
+            -C "error"
+
+requires_protocol_version tls13
+requires_openssl_tls1_3
+requires_config_enabled MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE
+run_test    "Sample: ssl_client1, openssl server, TLS 1.3" \
```
Comment (gilles-peskine-arm) [inline tests/opt-testcases/sample.sh:45]: This and some other test cases are skipped in builds with only TLS 1.3. This is due to https://github.com/Mbed-TLS/mbedtls/issues/9560, which is a preexisting bug affecting many preexisting test cases, and I will not fix it here.

**Comment by gilles-peskine-arm** [comment]
This is getting too large: 29 commits (not counting the ones from https://github.com/Mbed-TLS/mbedtls/pull/9556). So I intend to split this in two pieces. Probably all except `mini_client`, then `mini_client`, which brings in issues with PSK builds. Or maybe also do `mini_client` in the first PR, but excluding PSK builds.

File: tests/ssl-opt.sh [hunk 6]
```diff
@@ -1695,23 +1775,35 @@ run_test() {
...
-        *$DATA_FILES_PATH/*)
+    # Check if our test programs use files.
+    case "$CLI_CMD" in
+        *programs/ssl/*"$DATA_FILES_PATH/"*)
+            requires_config_enabled MBEDTLS_FS_IO;;
+    esac
+    case "$SRV_CMD" in
+        *programs/ssl/*"$DATA_FILES_PATH/"*)
             requires_config_enabled MBEDTLS_FS_IO;;
     esac
```
Comment (gilles-peskine-arm) [inline tests/ssl-opt.sh:1808]: So this innocent-looking change (at least it looked innocent to me) is causing a bunch more test cases to be executed in `config-suite-b`, `config-ccm-psk-tls1_2.h` and `config-ccm-psk-dtls1_2.h`. And some are failing because a genuine requirement isn't declared. The joys of ssl-opt.

Comment (gilles-peskine-arm) [reply tests/ssl-opt.sh:1808]: And by the way, maybe we should enable `MBEDTLS_FS_IO` in `test-ref-configs` when we run `ssl-opt` (we already add `MBEDTLS_DEBUG_C` and `MBEDTLS_ERROR_C`)?

**Comment by gilles-peskine-arm** [comment]
I've removed all the `mini_client` and I'm still at 23 commits (not counting https://github.com/Mbed-TLS/mbedtls/pull/9556), plus a few more (I think at this point all that's failing is `config-suite-b.h`). The commits are mostly small and focused, but it's still a lot. @mpg How do you feel about the length of this PR? I'm thinking of breaking out another PR of preliminaries (compatibility mode, consequences of finer `MBEDTLS_FS_IO` detection, test-ref-configs).

**Comment by mpg** [comment]
> The commits are mostly small and focused, but it's still a lot. @mpg How do you feel about the length of this PR?

I'm happy to review this PR as it is (plus the few commits needed for it to pass CI). I don't feel splitting it just for the sake of it would significantly help, unless there's a breaking point that really makes sense.

However, I'm wondering about PSK-only mode, which seems to be bringing a lot of issues. Would it make sense to have a first step where we only test the programs with cert-based (or if it helps, even signature-based, that is cert-based + ephemeral as opposed to static ECDH or RSA encryption) key exchanges, and leave PSK-only for step 2? (That's a real question, the answer might be no, you know better than me at this point.)

**Comment by gilles-peskine-arm** [comment]
> Would it make sense to have a first step where we only test the programs with cert-based (or if it helps, even signature-based, that is cert-based + ephemeral as opposed to static ECDH or RSA encryption) key exchanges, and leave PSK-only for step 2?

`mini_client` is the only sample program that can work with PSK at all. So my first split was already doing that. I only realized yesterday that some of the failures I had seen earlier were not due to https://github.com/Mbed-TLS/mbedtls/pull/9556 or to the changes I made for the sake of `mini_client` test cases, but due to changing `MBEDTLS_FS_IO` detection. Given that yesterday's CI had further failures that I hadn't expected, I'm going to split this again with another preliminary that handles `MBEDTLS_FS_IO` detection and related changes, plus possibly `MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE` changes. At this point I'm still not planning to tackle https://github.com/Mbed-TLS/mbedtls/issues/9560.

**Comment by gilles-peskine-arm** [comment]
> preliminary that handles MBEDTLS_FS_IO detection and related changes

Come to think of it, the only purpose of improving MBEDTLS_FS_IO detection was to run more tests in config-ccm-psk-dtls1_2. And that was only useful for the mini_client PSK tests. While these changes are desirable, they're technical debt, not on the critical path for the deliverable. So I'm going to remove that and its consequences, file a tech debt issue with pointers, and hopefully the delivery can converge quickly. It was already passing everything except `test-ref-configs.pl` at one point.

**Comment by mpg** [comment]
Checking changes since my last (partial review). It seems that the following change has been removed:
```diff
-    # Check if test uses files
-    case "$SRV_CMD $CLI_CMD" in
-        *$DATA_FILES_PATH/*)
+    # Check if our test programs use files.
+    case "$CLI_CMD" in
+        *programs/ssl/*"$DATA_FILES_PATH/"*)
+            requires_config_enabled MBEDTLS_FS_IO;;
+    esac
+    case "$SRV_CMD" in
+        *programs/ssl/*"$DATA_FILES_PATH/"*)
```
I thought that was a good change, why did you remove it?

File: tests/opt-testcases/sample.sh [hunk 7]
```diff
@@ -49,6 +62,22 @@ run_test    "Sample: ssl_client1, gnutls server, TLS 1.3" \
...
             -C "error"
 
+# The server complains of extra data after it closes the connection
+# because the client keeps sending data, so the server receives
+# more application data when it expects a new handshake. We consider
+# the test a success if both sides have sent and received application
+# data, no matter what happens afterwards.
+run_test    "Sample: dtls_client, ssl_server2" \
+            -P 4433 \
+            "$PROGRAMS_DIR/ssl_server2 dtls=1 server_addr=localhost" \
```
Comment (mpg) [inline tests/opt-testcases/sample.sh:72]: Out of curiosity: why do we need `server_addr=localhost` here?

File: tests/opt-testcases/sample.sh [hunk 8]
```diff
@@ -76,6 +105,30 @@ run_test    "Sample: dtls_client, gnutls server, DTLS 1.2" \
...
+            "$PROGRAMS_DIR/ssl_client2" \
+            0 \
+            -s "[1-9][0-9]* bytes read" \
+            -s "[1-9][0-9]* bytes written" \
+            -c "[1-9][0-9]* bytes read" \
+            -c "[1-9][0-9]* bytes written" \
+            -S "error" \
+            -C "error"
+
+run_test    "Sample: ssl_client1 with ssl_server" \
```
Comment (mpg) [inline tests/opt-testcases/sample.sh:130]: Minor: naming is inconsistent. Not sure it matters though.

File: tests/scripts/test-ref-configs.pl [hunk 9]
```diff
@@ -57,11 +57,19 @@
 my $config_h = 'include/mbedtls/mbedtls_config.h';
 
 system( "cp $config_h $config_h.bak" ) and die;
-sub abort {
-    system( "mv $config_h.bak $config_h" ) and warn "$config_h not restored\n";
-    # use an exit code between 1 and 124 for git bisect (die returns 255)
+
```
Comment (mpg) [inline tests/scripts/test-ref-configs.pl:60]: Note: this is going to conflict with the PR that removes this script. I'd suggest removing this commit to avoid the conflict.

**Review by mpg — COMMENTED** [review]
Incremental review since my previous partial review, not complete yet, but looking pretty good so far.

**Review by mpg — DISMISSED** [review]
I've completed my review, this looks good to me.

I've also checked that the new tests are passing locally on my machine, fwiw.

File: tests/scripts/test-ref-configs.pl (hunk 9 above)
Comment (gilles-peskine-arm) [reply tests/scripts/test-ref-configs.pl:60]: I wanted to get detailed CI feedback here for as long as `test-ref-configs` failed. Changing the script is out of scope here and I'll remove it in the next rebase (there'll be a next rebase once https://github.com/Mbed-TLS/mbedtls/pull/9563 is merged).

File: tests/opt-testcases/sample.sh (hunk 7 above)
Comment (gilles-peskine-arm) [reply tests/opt-testcases/sample.sh:72]: By default, on my machine, `ssl_server2` only listens on IPv4. I actually don't understand why: I would have thought it would prioritize IPv6. `dtls_client` connects to `localhost`, whatever it is. I remember it took me a little while to find something that would minimize changes in the test programs, have the tests pass on my machine (where `localhost` resolves to `::1`), and have the tests pass on the CI (where IPv6 is disabled).

I don't know why this isn't necessary for `ssl_client1`.

File: tests/opt-testcases/sample.sh (hunk 8 above)
Comment (gilles-peskine-arm) [reply tests/opt-testcases/sample.sh:130]: There are two naming patterns: “Sample: PROGRAM, PEER” for testing a sample program against a peer that isn't a sample program (OpenSSL, GnuTLS or Mbed TLS's fancy programs), and “Sample: PROGRAM1 with PROGRAM2” for testing two sample programs against each other. I'm open to other naming conventions if you have suggestions.

**Comment by gilles-peskine-arm** [comment]
> [FS_IO change]
>
> I thought that was a good change, why did you remove it?

It turned out to be a huge can of worms. See https://github.com/Mbed-TLS/mbedtls/pull/9541#discussion_r1757571713

File: tests/ssl-opt.sh (hunk 6 above)
Comment (mpg) [reply tests/ssl-opt.sh]: Aw, let's not do that now, then.

> The joys of ssl-opt.

Yeah, it was designed to only work in the default config, and dependency declarations were added later as an after-thought, and for some time the target was it should run in the default and full configs, then perhaps a few others that are close enough... but we never took the time to think it through, and here we are now.

> And by the way, maybe we should enable MBEDTLS_FS_IO in test-ref-configs when we run ssl-opt (we already add MBEDTLS_DEBUG_C and MBEDTLS_ERROR_C)?

Yeah, I think that would make sense. Perhaps for your other PR that splits test-ref-configs? (Unless it turns out to be another can of worms.)

**Review by davidhorstmann-arm — CHANGES_REQUESTED** [review]
One possible missing dependency, LGTM otherwise

File: tests/ssl-opt.sh [hunk 10]
```diff
@@ -491,6 +491,16 @@ detect_required_features() {
             requires_certificate_authentication;;
     esac
 
+    case " $CMD_LINE " in
+        *"programs/ssl/ssl_client1 "*)
+            requires_config_enabled MBEDTLS_CTR_DRBG_C
+            requires_config_enabled MBEDTLS_ENTROPY_C
+            requires_config_enabled MBEDTLS_PEM_PARSE_C
+            requires_config_enabled MBEDTLS_SSL_CLI_C
```
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply tests/ssl-opt.sh:500]: We currently have no dependencies on `MBEDTLS_NET_C` at all in `ssl-opt.sh`. So I didn't add one for the new programs. I think it's ok either way. I'm pretty sure the dependencies on the sample programs aren't fully correct anyway in terms of exactly what key exchanges must be enabled, possibly even crypto features; but fixing that beyond getting `all.sh` (and in particular `test-ref-configs.pl`) to pass is beyond the scope of this PR.

**Comment by mpg** [comment]
There are conflicts now that `test-ref-configs.pl` has been removed.

**Comment by gilles-peskine-arm** [comment]
This PR continues https://github.com/Mbed-TLS/mbedtls/pull/9563, so I'll need to rebase it once that PR is merged anyway.

File: tests/ssl-opt.sh (hunk 10 above)
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply tests/ssl-opt.sh:500]: To clarify my comment from yesterday: I'd prefer not to add a dependency on `MBEDTLS_NET_C` just for the sample programs, but not for `ssl_client2` and `ssl_server2`: why would we leave this inconsistent? And I'd also prefer to minimize changes to dependencies that aren't related to sample programs, after all the cans of worms I encountered when I did so (`MBEDTLS_FS_IO`, DTLS adaptation). But if you think it's better to add this dependency, I'll do it, and please let me know whether you want to also add it to `ssl_*2`.

**Comment by gilles-peskine-arm** [comment]
I've rebased on top of the merge of the prerequisite PR.

**Review by mpg — APPROVED** [review]
LGTm after rebase

File: tests/ssl-opt.sh (hunk 10 above)
[the remark this answers is not in the document]
Comment (davidhorstmann-arm) [reply tests/ssl-opt.sh:500]: Okay, I'm happy for you to leave this as-is for now with the understanding that dependencies in `ssl-opt.sh` are not perfect.

**Review by davidhorstmann-arm — APPROVED** [review]
Rebase LGTM - rebased locally and compared with `git rage-diff`

Thanks!
