### PR TITLE
check_config.h not complete about builds without CIPHER_C

### LINKED ISSUE #8646: `check_config.h` not complete about builds without `CIPHER_C`
### Summary

In some configurations without `CIPHER_C`, the build fails due to missing declarations (with `-Werror`) or linker error (without it).

### System information

Mbed TLS version (number or commit id): current development
Operating system and version: any, presumably
Configuration (if not default, please attach `mbedtls_config.h`): starting from the default config, unset MBEDTLS_CIPHER_C MBEDTLS_CMAC_C MBEDTLS_NIST_KW_C MBEDTLS_PKCS12_C MBEDTLS_PKCS5_C MBEDTLS_SSL_TLS_C MBEDTLS_SSL_TICKET_C
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): any, presumably
Additional environment information: 

### Expected behavior

On general grounds: the build should either succeed or we should get a clean error message from `check_config.h`

More specifically: in this instance, I think we should be getting an error message - PSA Crypto is enabled, as well as unauthenticated ciphers, so we need `CIPHER_C` and `check_config.h` should be checking for that.

### Actual behavior

Compile-time error with `-Werror`:
```
psa_crypto_cipher.c: In function ‘psa_cipher_setup’:
psa_crypto_cipher.c:300:19: error: implicit declaration of function ‘mbedtls_cipher_info_from_psa’; did you mean ‘mbedtls_cipher_info_from_type’? [-Werror=implicit-function-declaration]
  300 |     cipher_info = mbedtls_cipher_info_from_psa(alg, key_type,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   mbedtls_cipher_info_from_type
psa_crypto_cipher.c:300:17: error: assignment to ‘const mbedtls_cipher_info_t *’ {aka ‘const struct mbedtls_cipher_info_t *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  300 |     cipher_info = mbedtls_cipher_info_from_psa(alg, key_type,
      |                 ^
```
Link-time errors without it:
```
  CC    aes/crypt_and_hash.c
/usr/bin/ld: ../library/libmbedcrypto.a(psa_crypto_cipher.o): in function `psa_cipher_setup.isra.0':
psa_crypto_cipher.c:(.text+0x3b): undefined reference to `mbedtls_cipher_init'
/usr/bin/ld: psa_crypto_cipher.c:(.text+0x54): undefined reference to `mbedtls_cipher_info_from_psa'
/usr/bin/ld: psa_crypto_cipher.c:(.text+0x67): undefined reference to `mbedtls_cipher_setup'
/usr/bin/ld: psa_crypto_cipher.c:(.text+0xbd): undefined reference to `mbedtls_cipher_setkey'
/usr/bin/ld: psa_crypto_cipher.c:(.text+0x12d): undefined reference to `mbedtls_cipher_set_padding_mode'
/usr/bin/ld: psa_crypto_cipher.c:(.text+0x1b0): undefined reference to `mbedtls_cipher_setkey'
/usr/bin/ld: psa_crypto_cipher.c:(.text+0x22a): undefined reference to `mbedtls_cipher_set_padding_mode'
/usr/bin/ld: ../library/libmbedcrypto.a(psa_crypto_cipher.o): in function `mbedtls_psa_cipher_set_iv':
psa_crypto_cipher.c:(.text+0x559): undefined reference to `mbedtls_cipher_set_iv'
/usr/bin/ld: ../library/libmbedcrypto.a(psa_crypto_cipher.o): in function `mbedtls_psa_cipher_update':
psa_crypto_cipher.c:(.text+0x5c8): undefined reference to `mbedtls_cipher_update'
/usr/bin/ld: ../library/libmbedcrypto.a(psa_crypto_cipher.o): in function `mbedtls_psa_cipher_finish':
psa_crypto_cipher.c:(.text+0x64a): undefined reference to `mbedtls_cipher_finish'
/usr/bin/ld: ../library/libmbedcrypto.a(psa_crypto_cipher.o): in function `mbedtls_psa_cipher_abort':
psa_crypto_cipher.c:(.text+0x6eb): undefined reference to `mbedtls_cipher_free'
/usr/bin/ld: ../library/libmbedcrypto.a(psa_crypto_cipher.o): in function `mbedtls_psa_cipher_encrypt':
psa_crypto_cipher.c:(.text+0x856): undefined reference to `mbedtls_cipher_free'
/usr/bin/ld: ../library/libmbedcrypto.a(psa_crypto_cipher.o): in function `mbedtls_psa_cipher_decrypt':
psa_crypto_cipher.c:(.text+0x9ce): undefined reference to `mbedtls_cipher_free'
```

### Steps to reproduce

From a clean checkout of current development:
```
for c in MBEDTLS_CIPHER_C MBEDTLS_CMAC_C MBEDTLS_NIST_KW_C MBEDTLS_PKCS12_C MBEDTLS_PKCS5_C MBEDTLS_SSL_TLS_C MBEDTLS_SSL_TICKET_C; do scripts/config.py unset $c; done
make WARNING_CFLAGS='-Werror'
make
```

### Additional information

Originally reported by @tom-cosgrove-arm 

This bug is only present in development, not the 2.28 branch (or any released version).

### PR DESCRIPTION
**Pull request by valeriosetti**
Check if `CIPHER_C` is enabled when PSA builtin unauthenticated ciphers are enabled.
Resolves #8646

## PR checklist

- [x] **changelog** not required
- [x] **backport** not required
- [x] **tests** not required

### CODE REVIEW

File: include/mbedtls/check_config.h [hunk 1]
```diff
@@ -203,6 +203,19 @@
 #endif
 #endif
 
+#if defined(MBEDTLS_PSA_CRYPTO_C) && \
```
Comment (mpg) [inline include/mbedtls/check_config.h:206]: I think we should tell something about this in `mbedtls_config.h` as well, like "`MBEDTLS_CIPHER_C` if any unauthenticated cipher is enabled".

**Review by mpg — CHANGES_REQUESTED** [review]
Looks good but documentation needs updating as well.

File: include/mbedtls/check_config.h (hunk 1 above)
Comment (mpg) [reply include/mbedtls/check_config.h:206]: Ah, thanks for fixing my mistake: it's about being builtin not just enabled.

**Review by mpg — APPROVED** [review]
LGTM, thanks!

File: include/mbedtls/check_config.h [hunk 2]
```diff
@@ -203,6 +203,19 @@
...
+    (defined(MBEDTLS_PSA_BUILTIN_ALG_STREAM_CIPHER) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CTR) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CFB) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_OFB) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_ECB_NO_PADDING) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CBC_NO_PADDING) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CBC_PKCS7) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CCM_STAR_NO_TAG)) && \
+    !defined(MBEDTLS_CIPHER_C)
+#error "Built-in unauthenticated ciphers are enabled in PSA, but not all prerequisites"
```
Comment (tom-cosgrove-arm) [inline include/mbedtls/check_config.h:216]: While this does correctly stop the build here in the problematic configuration, it's actually not very helpful - it's not possible to just `scripts/config.py unset MBEDTLS_PSA_BUILTIN_ALG_CTR` and so on, since they are derived variables.

In other words, as a library user who tried to disable `MBEDTLS_CIPHER_C ` but keep `MBEDTLS_CCM_C` enabled, I'm now told "Built-in unauthenticated ciphers are enabled in PSA, but not all prerequisites` but it's not clear what those prerequisites might be.

Normally, I would look at the condition here in `check_config.h` and adjust the config based on the macros being tests - and if it turns out that the things I want are incompatible, that becomes clear. But this really doesn't help me as a library user

Comment (mpg) [reply include/mbedtls/check_config.h:216]: Ah good point. Error messages from `check_config.h` are usually terse and not helpful by themselves, but that's not a problem most of the time because you can just look above the line that gave the error in order to get the details - but as you point out, that doesn't really work here.

I'm thinking we should expand on the topic in some other place and then give a pointer to that place in the error message. Candidates:
- the documentation of `MBEDTLS_PSA_CRYPTO_C`;
- `docs/driver-only-builds.txt` but that's quite long, so I think pointing to `MBEDTLS_PSA_CRYPTO_C` is easier.

Unfortunately the details are a bit complex, as `BUILTIN_ALG_xxx` is auto-enabled if `ALG_xxx` is enabled and:
- `ALG_xxx` is not accelerated, or
- a key type compatible with `ALG_xxx` is enabled but not accelerated (except if `xxx` is CCM or GCM).

Perhaps we need a layered approach where the error message points to `MBEDTLS_PSA_CRYPTO_C` which gives an overview and then for details points to https://github.com/Mbed-TLS/mbedtls/pull/8641/files#diff-b6ed7355a8cfb932767f2139329ab12adc46d045ea9951d5e322371e05cee73fR293?

Comment (mpg) [reply include/mbedtls/check_config.h:216]: Hmm, OK, completely different proposal: instead PSA auto-enables `CIPHER_C` when it needs it, so we don't have to put all this complexity in the user's face. We'll still keep the details of when exactly you can disable `CIPHER_C` in `docs/driver-only-builds.md` where it's easier to explain because it's in context - and only in the face of people who are trying to take advantage of drivers to compile out builtins.

Wdyt?

Comment (tom-cosgrove-arm) [reply include/mbedtls/check_config.h:216]: My concern with auto-enabling `CIPHER_C` is that potential code-size savings won't be achieved by people who don't realise exactly what they need to disabled when all they really need is CCM or GCM. There are now enough things to disable that "just disable what you don't need" gets to be cumbersome.

Maybe we should document in the comments for `CIPHER_C`, because the current description "Enable the generic cipher layer" is particularly unhelpful these days.

At a high level we could say "enable if you need the mbedtls_cipher_xxx()` APIs", along with "can be disabled if PSA is enabled and all ciphers except CCM and GCM are enabled", or something like that?

So I guess I prefer your first option ("expand on the topic") but suggesting we do that in the documentation for `MBEDTLS_CIPHER_C`.

How does that sound?

Comment (mpg) [reply include/mbedtls/check_config.h:216]: When A depends on B, we usually mention that in A's documentation rather than B's... That said, I wouldn't object to documenting at B as long as A's documentation has a pointer to it.

> My concern with auto-enabling `CIPHER_C` is that potential code-size savings won't be achieved by people who don't realise exactly what they need to disable when all they really need is CCM or GCM. There are now enough things to disable that "just disable what you don't need" gets to be cumbersome.

Yeah, I was concerned about that too. It's the usual trade-off of "making it harder to get the damn thing to build, but once it builds you have more confidence it does what you mean" - if it were about security or correctness I wouldn't hesitate for a second of course, but about code size?

Also, as a matter of principle, the fact that PSA Crypto depends on `CIPHER_C` for some things is an implementation detail that can and will change in the future, so I'm not super happy about exposing users to it. But OTOH that's how our historic config system works.

> At a high level we could say "enable if you need the mbedtls_cipher_xxx()` APIs", along with "can be disabled if PSA is enabled and all ciphers except CCM and GCM are enabled", or something like that?

This is ambiguous: does "enabled" mean `PSA_WANT_xxx` or `MBEDTLS_yyy_C` and `MBEDTLS_CIPHER_MODE_zzz`? Documenting this in a way that's unambiguous, correct and complete is not easy - that's why we have `docs/driver-only-builds.md`.

Suggestion: "Can be disabled if either PSA crypto is disabled, or PSA is enabled but no unauthenticated cipher is enabled on the PSA side, or PSA is enabled with unauthenticated ciphers but they're all fully provided by a driver (see `docs/driver-only-builds.md` for details about that case)."

But even then, "no unauthenticated cipher is enabled on the PSA side" is not trivial as there are two cases:
- with `MBEDTLS_PSA_CRYPTO_CONFIG` disabled (default) it means no `MBEDTLS_CIPHER_MODE_xxx` is enabled;
- with `MBEDTLS_PSA_CRYPTO_CONFIG` enabled (non-default, but needed for driver-only builds, in particular, enabled by TF-M) it means no `PSA_WANT_ALG_xxx` where xxx represents an unauthenticated cipher.

Also, that's not complete: if you want to disable `CIPHER_C` currently you also need to disable `PKCS5_C`, `PKCS12_C`, `CMAC_C` and `NIST_KW_C`. Which circles back to my point that we usually document "A needs B" at A's, and I don't think switching to the opposite would make things easier.

Comment (mpg) [reply include/mbedtls/check_config.h:216]: I hate making things that are that hard to document properly. Unfortunately I'm afraid until we've switched to the crypto config being fully based on `PSA_WANT` macros and additive, we're stuck with some complexity. And here, some more related to the fact that we're doing some things only partially due to lack of time.

Comment (tom-cosgrove-arm) [reply include/mbedtls/check_config.h:216]: > if you want to disable `CIPHER_C` currently you also need to disable `PKCS5_C`, ...

Those are discoverable from the `check_config.h` errors quite easily. I was hoping this would do the same for the cipher pieces.

> This is ambiguous: does "enabled" mean `PSA_WANT_xxx` or `MBEDTLS_yyy_C` and `MBEDTLS_CIPHER_MODE_zzz`?

Yes, and I don't really know the answer to that :)  It was more a suggestion as to "this is the kind of thing I would like to be told as a library user"

Documenting this solely in `docs/driver-only-builds.md` seems to be wrong since the built-in CCM and GCM can be used in driver-less builds without `CIPHER_C` providing XXX (where XXX is exactly what I'm looking for from this!)

Comment (mpg) [reply include/mbedtls/check_config.h:216]: > Documenting this solely in `docs/driver-only-builds.md` seems to be wrong since the built-in CCM and GCM can be used in driver-less builds without `CIPHER_C` providing XXX (where XXX is exactly what I'm looking for from this!)

Ah, excellent point. It's all tied up in my mind because its "this quarter's EPIC" but of course from a user's perspective they're different things!

Comment (gilles-peskine-arm) [reply include/mbedtls/check_config.h:216]: > > My concern with auto-enabling CIPHER_C is that potential code-size savings won't be achieved by people who don't realise exactly what they need to disable when all they really need is CCM or GCM. There are now enough things to disable that "just disable what you don't need" gets to be cumbersome.
>
> Yeah, I was concerned about that too. It's the usual trade-off of "making it harder to get the damn thing to build, but once it builds you have more confidence it does what you mean" - if it were about security or correctness I wouldn't hesitate for a second of course, but about code size?

My take on this is that people who care a lot about code size will start from an empty configuration and enumerate their needs, rather than take the default configuration and remove what they don't need. With that approach, the additive method (declare what you need, and its dependencies are automatically enabled) is easier!

The explicit method is only easier in rare circumstances, for example if you have a code size budget and are trying to provide as much functionality as you can within that budget. That's not a common case, so I think it's reasonable that it's harder and will take some fiddling. It's not even really more fiddling than the additive method: the difference is not how hard it is to find a suitable build, but whether you find problems because `check_config.h` complains or because `size` gives a number that's too large.

Comment (mpg) [reply include/mbedtls/check_config.h:216]: So is that two in favour of additive/auto-enable and one against?

I'll note that even if we go for additive, we'll probably want some documentation in `mbedtls_config.h` - as Tom notes, `driver-only-builds.md` can't be the only place where this is documented, since removing `CIPHER_C` is not just about drivers. Some modules already have an `Auto-enables` line in their documentation, so `MBEDTLS_PSA_CRYPTO_C` could have:
```
Auto-enables: MBEDTLS_CIPHER_C if some unauthenticated is enabled in PSA (unless it's fully accelerated, see docs/driver-only-builds.md about that).
```

@tom-cosgrove-arm Wdyt?

Comment (tom-cosgrove-arm) [reply include/mbedtls/check_config.h:216]: I'm okay with auto-enable as long as there's a back-link to it. I'd like a bit more clarity on the message; have discussed off-line with @mpg

Comment (mpg) [reply include/mbedtls/check_config.h:216]: Suggested resolution based on the discussion with @tom-cosgrove-arm:
* Remove the check in `check_config.h` and instead auto-enable `CIPHER_C` based on PSA needs in `mbedtls/config_adjust_legacy_from_psa.h`.
* Add an `Auto-enables` comment to the documentation of `PSA_CRYPTO_C` with content like "MBEDTLS_CIPHER_C if any unauthenticated (ie, non-AEAD) cipher is enabled in PSA (unless it's fully accelerated, see docs/driver-only-builds.md about that)."
* Add a back-link in the documentation of `CIPHER_C`, like "Auto-enabled by: MBEDTLS_PSA_CRYPTO_C depending on which ciphers are enabled (see the documentation of that option for details)."

File: include/mbedtls/config_adjust_legacy_crypto.h [hunk 3]
```diff
@@ -29,6 +29,20 @@
...
+#if defined(MBEDTLS_PSA_CRYPTO_C) && \
+    (defined(MBEDTLS_PSA_BUILTIN_ALG_STREAM_CIPHER) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CTR) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CFB) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_OFB) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_ECB_NO_PADDING) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CBC_NO_PADDING) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CBC_PKCS7) || \
+    defined(MBEDTLS_PSA_BUILTIN_ALG_CCM_STAR_NO_TAG))
+#define MBEDTLS_CIPHER_C
```
Comment (mpg) [inline include/mbedtls/config_adjust_legacy_crypto.h:43]: Ideally this should go before the block above which checks if `CIPHER_C` is defined.

**Review by mpg — APPROVED** [review]
LGTM, just one suggestion for improvement.

File: include/mbedtls/config_adjust_legacy_crypto.h (hunk 3 above)
Comment (mpg) [reply include/mbedtls/config_adjust_legacy_crypto.h:43]: (It's not a big problem as the worse that can happen with both will be enabled and we'll waste a bit of code size.)

**Review by mpg — APPROVED** [review]
LGTM, thanks!

**Comment by mpg** [comment]
@tom-cosgrove-arm I think this is ready for you to review again.

**Review by tom-cosgrove-arm — DISMISSED** [review]
Conflict in include/mbedtls/config_adjust_legacy_crypto.h

(Sorry, my fault for taking so long to review)

**Comment by valeriosetti** [comment]
> Conflict in include/mbedtls/config_adjust_legacy_crypto.h 
> (Sorry, my fault for taking so long to review)

No problem, I just did the rebase now ;)
The code wasn't changed during the rebase, but the last (old) commit was removed as it was not doing anything useful.

File: include/mbedtls/config_adjust_legacy_crypto.h (hunk 3 above)
Comment (tom-cosgrove-arm) [reply include/mbedtls/config_adjust_legacy_crypto.h:36]: Marking this resolved as it has been done

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM -thanks

**Review by mpg — APPROVED** [review]
LGTM, thanks!
