### PR TITLE
Fix issue in handling legacy_compression_methods in ssl_tls13_parse_client_hello()

### LINKED ISSUE #9243: ssl_tls13_parse_client_hello() does not handle legacy_compression_methods properly
### Summary
ssl_tls13_parse_client_hello() assumes legacy_compression_methods length will always be zero which is true for TLS 1.3 However if TLS 1.3 is enabled by default all clientHello requests (including TLS 1.2 requests) will go to ssl_tls13_parse_client_hello()  first and then passed to TLS 1.2 parsing function later but processing legacy_compression_methods happens earlier so it might be not zero if it's a TLS 1.2 request. 

### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: all
Configuration (if not default, please attach `mbedtls_config.h`): defualt
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): N/A
Additional environment information: 

### Expected behavior
ssl_tls13_parse_client_hello() returns SSL_CLIENT_HELLO_TLS1_2 if legacy_compression_methods wasn't zero

### Actual behavior
ssl_tls13_parse_client_hello() continues normally but parsing of subsequent data is wrong.

### Steps to reproduce
send TLS 1.2 ClientHello request with non zero legacy_compression_methods

### PR DESCRIPTION
**Pull request by waleed-elmelegy-arm**
## Description

Please write a few sentences describing the overall goals of the pull request's commits.
fixes #9243 & #8995

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [X] **changelog** provided
- [X] **3.6 backport** done: #9499 
- [x] **2.28 backport** not required (feature not in 2.28)
- [X] **tests** provided

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the
checklist for PR contributors.

Help make review efficient:
* Multiple simple commits
  - please structure your PR into a series of small commits, each of which does one thing
* Avoid force-push
  - please do not force-push to update your PR - just add new commit(s)
* See our [Guidelines for Contributors](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) for more details about the review process.

### CODE REVIEW

**Comment by Aethedor** [comment]
Yes, that seems to fix the issue with ssllabs.com failing its test. While I used to get an A+ score for my server, now I only get an A. I think it has to do with the fact that my server now doesn't support TLS_FALLBACK_SCSV. Any comment on that?

**Comment by gilles-peskine-arm** [comment]
> server now doesn't support TLS_FALLBACK_SCSV. Any comment on that?

`FALLBACK_SCSV` is about avoiding a downgrade from TLS 1.2. Since Mbed TLS no longer supports earlier protocol versions (TLS 1.0 and 1.1 were removed in Mbed TLS 3.0), `FALLBACK_SCSV` has no effect when either side is Mbed TLS ≥3.0.

**Comment by Aethedor** [comment]
> `FALLBACK_SCSV` has no effect when either side is Mbed TLS ≥3.0.
Okay, thanks. So ssllabs.com should fix that in their scan I guess.

Anyway, the issue seems fixed. Thanks for the patch!

**Comment by tom-cosgrove-arm** [comment]
CI is green

**Review by tom-cosgrove-arm — APPROVED** [review]

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
There is a misleading comment that I would prefer to fix. Otherwise, did you think about a non-regression test using  GnuTLS or OpenSSL?

**Comment by waleed-elmelegy-arm** [comment]
> There is a misleading comment that I would prefer to fix. Otherwise, did you think about a non-regression test using GnuTLS or OpenSSL?

OpenSSL needs to be recompiled with a flag to allow for legacy compression methods and GnuTLS discontinued legacy compression methods in 3.6 so the test won't work in next version so it's going to be difficult to do a regression test unless we can send the ClientHello message hardcoded.

**Comment by ronald-cron-arm** [comment]
> > There is a misleading comment that I would prefer to fix. Otherwise, did you think about a non-regression test using GnuTLS or OpenSSL?
> 
> OpenSSL needs to be recompiled with a flag to allow for legacy compression methods and GnuTLS discontinued legacy compression methods in 3.6 so the test won't work in next version so it's going to be difficult to do a regression test unless we can send the ClientHello message hardcoded.

Thus I would say that a test with our current version of GnuTLS (3.4.6) would do the job for some time at least. As far as I know we still plan to base some tests on rather old versions of OpenSSL, GnuTLS for that kind of situation. As it is a situation we can encounter in real life (worth saying it in a comment associated to the tests by the way) it is better to have a non-regression test.

**Comment by gilles-peskine-arm** [comment]
> As far as I know we still plan to base some tests on rather old versions of OpenSSL, GnuTLS for that kind of situation

That's right. We do plan to keep some old versions of OpenSSL and GnuTLS around in our test environment for a long time, as long as there is at least one maintained version of Mbed TLS that has a feature that has been dropped from recent OpenSSL/GnuTLS. Even if we change the default versions that we test against, we are not going to remove GnuTLS 3.3.8 for at least as long as 2.28 is around (I'm don't know offhand if it's still relevant for 3.6), and I think we'll keep 3.4.6 for at least as long as 3.6 is around. It's not a problem to keep it as long as 4.x is around.

File: tests/ssl-opt.sh [hunk 1]
```diff
@@ -14135,6 +14135,17 @@ run_test    "TLS 1.3: no HRR in case of PSK key exchange mode" \
...
+# Legacy_compression_methods testing
+
+requires_gnutls
+requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
+requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_3
+run_test    "ClientHello parse handle Legacy_compression_methods" \
+            "$P_SRV debug_level=3" \
+            "$G_CLI  --priority=NORMAL:-VERS-ALL:+VERS-TLS1.2:+COMP-DEFLATE localhost" \
+            0 \
+            -c "Handshake was completed"
```
Comment (ronald-cron-arm) [inline tests/ssl-opt.sh:14147]:
```suggestion
            -c "Handshake was completed" \
            -s "dumping .client hello, compression. (2 bytes)"
```

File: tests/ssl-opt.sh [hunk 2]
```diff
@@ -14135,6 +14135,17 @@ run_test    "TLS 1.3: no HRR in case of PSK key exchange mode" \
             -c "Selected key exchange mode: psk$" \
             -c "HTTP/1.0 200 OK"
 
+# Legacy_compression_methods testing
+
+requires_gnutls
+requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
+requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_3
+run_test    "ClientHello parse handle Legacy_compression_methods" \
```
Comment (ronald-cron-arm) [inline tests/ssl-opt.sh:14143]:
```suggestion
run_test    "TLS 1.2 ClientHello indicating support for deflate compression method" \
```

File: tests/ssl-opt.sh [hunk 3]
```diff
@@ -14135,6 +14135,17 @@ run_test    "TLS 1.3: no HRR in case of PSK key exchange mode" \
             -c "Selected key exchange mode: psk$" \
             -c "HTTP/1.0 200 OK"
 
+# Legacy_compression_methods testing
+
+requires_gnutls
+requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
+requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_3
```
Comment (ronald-cron-arm) [inline tests/ssl-opt.sh:14142]:
```suggestion
requires_config_enabled MBEDTLS_SSL_SRV_C
requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
```
It makes sense to me to run it also when only TLS 1.2 is enabled.

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
The non-regression test is operational, thanks. Some suggestions for improvement about it.

File: tests/ssl-opt.sh [hunk 4]
```diff
@@ -14135,6 +14135,29 @@ run_test    "TLS 1.3: no HRR in case of PSK key exchange mode" \
...
+run_test    "TLS 1.2 ClientHello indicating support for deflate compression method (fallback from TLS 1.3)" \
+            "$P_SRV debug_level=3" \
+            "$G_CLI  --priority=NORMAL:-VERS-ALL:+VERS-TLS1.2:+COMP-DEFLATE localhost" \
+            0 \
+            -c "Handshake was completed" \
+            -s "dumping .client hello, compression. (2 bytes)"
+
+requires_gnutls
+requires_config_enabled MBEDTLS_SSL_SRV_C
+requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_2
```
Comment (ronald-cron-arm) [inline tests/ssl-opt.sh:14153]: I think we only need this one that will run when TLS 1.3 is enabled (with fallback because TLS 1.3 gets precedence) and when it is disabled (no fallback on server side, directly TLS 1.2 parsing).

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
I think we only need the second test case, otherwise LGTM.

**Review by ronald-cron-arm — DISMISSED** [review]
LGTM, thanks.

**Comment by ronald-cron-arm** [comment]
@tom-cosgrove-arm this looks good to me now, please have another look, thanks.

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Comment by tom-cosgrove-arm** [comment]
@waleed-elmelegy-arm Can you confirm if a 3.6 backport is needed? #8995 was raised against v3.6, suggesting one might be required

File: library/ssl_tls13_server.c [hunk 5]
```diff
@@ -1355,19 +1355,23 @@ static int ssl_tls13_parse_client_hello(mbedtls_ssl_context *ssl,
      * compression methods and the length of the extensions.
      *
      * cipher_suites                cipher_suites_len bytes
-     * legacy_compression_methods                   2 bytes
-     * extensions_len                               2 bytes
+     * legacy_compression_methods length            1 byte
      */
-    MBEDTLS_SSL_CHK_BUF_READ_PTR(p, end, cipher_suites_len + 2 + 2);
+    MBEDTLS_SSL_CHK_BUF_READ_PTR(p, end, cipher_suites_len + 1);
```
Comment (gilles-peskine-arm) [inline library/ssl_tls13_server.c:1360]: This is a bug fix, so please add a changelog entry.

File: ChangeLog.d/fix-legacy-compression-issue.txt [hunk 6]
```diff
@@ -0,0 +1,7 @@
+Bugfix
+   * Fix an issue where ssl_tls13_parse_client_hello() assumed legacy_compression_methods
+     length would always be zero, which is true for TLS 1.3. However, with TLS 1.3 enabled
+     by default, all ClientHello requests (including TLS 1.2 requests) are initially
+     processed by ssl_tls13_parse_client_hello() before being passed to the TLS 1.2
+     parsing function. This caused an issue where legacy_compression_methods
+     might not be zero for TLS 1.2 requests, as it is processed earlier.
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/fix-legacy-compression-issue.txt:7]: This explains how the code was wrong, but in a way that is meaningless for users. For example, if the name of an internal functions appears in a changelog entry, you're probably doing it wrong.

See https://github.com/Mbed-TLS/mbedtls/issues/9223 for a short write-up of this bug from a user's perspective.

Comment (gilles-peskine-arm) [reply ChangeLog.d/fix-legacy-compression-issue.txt:7]: Also please indicate the issue number(s) in the changelog entry: “Fixes #9243.” at the end. Or “Fixes #8995, #9243” if we are happy that #8995 is the same issue.

Comment (gilles-peskine-arm) [reply ChangeLog.d/fix-legacy-compression-issue.txt:7]: OK with “an issues” → “an issue”

Comment (tom-cosgrove-arm) [reply ChangeLog.d/fix-legacy-compression-issue.txt]: Oops :)

File: ChangeLog.d/fix-legacy-compression-issue.txt [hunk 7]
```diff
@@ -0,0 +1,7 @@
+Bugfix
+   * Fix an issue where TLS 1.2 clients who send a ClientHello message with
+     legacy_compression_methods get a failure in connection because TLS 1.3
+     is enabled by default and the server rejects the ClientHello packet as
+     malformed for TLS 1.3 in a way that stops the fallback to TLS 1.2.
+     fixes #8995, #9243.
```
Comment (tom-cosgrove-arm) [inline ChangeLog.d/fix-legacy-compression-issue.txt:6]: (minor) should be `Fixes`.

(not sure what others think) That's a very long sentence! ChangeLog entries are normally more succinct.

But I don't know if we want to carry on polishing this at this point...

Comment (gilles-peskine-arm) [reply ChangeLog.d/fix-legacy-compression-issue.txt:5]: We normally do a pass of polishing changelog entries in the release. The changelog entry needs to be technically accurate but we can do editorial corrections like capitalization at that point.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM
